- bower.json
> chore: Bump WebRTC adapter to version '5.0.1'

- package.json
> staging bump 2017-08-31

- app/script/conversation/EventMapper.js
- app/script/util/ValidationUtil.js
> fix: Ensure asset key for link preview images

- app/script/conversation/ConversationRepository.js
- app/script/conversation/ConversationService.js
- app/script/conversation/EventMapper.js
- app/script/cryptography/CryptographyMapper.js
- app/script/event/Backend.js
- app/script/event/Client.js
- app/script/event/EventTypeHandling.js
- app/script/message/MessageCategorization.js
- app/script/storage/StorageService.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/cryptography/CryptographyMapperSpec.js
> fix: File transfers missing from conversation history and collection (WEBAPP-4302)

- bower.json
> chore: Bump WebRTC to version '5.0.2'

- app/page/auth.html
- app/script/auth/AuthError.js
- app/script/auth/AuthView.js
- app/script/localization/translations/webapp-de.js
- app/script/localization/webapp.js
- app/script/main/app.js
- app/script/view_model/AuthViewModel.js
> feat: Check for support of cookies (WEBAPP-4310)

- bower.json
> chore: Bump WebRTC adapter to version '5.0.3'

- app/script/localization/translations/webapp-de.js
- app/script/localization/translations/webapp-hu.js
- app/script/localization/translations/webapp-ro.js
- app/script/localization/translations/webapp-ru.js
- app/script/localization/webapp.js
- app/script/service/BackendClientError.js
- app/script/view_model/AuthViewModel.js
> feat: Add error for login with suspended account (WEBAPP-4290)

- app/script/conversation/ConversationRepository.js
> fix: Canceling an upload results in "Upload failed" message

- app/script/calling/CallingRepository.js
- app/script/conversation/ConversationRepository.js
- app/script/util/DebugUtil.js
- app/script/view_model/ImageDetailViewViewModel.js
- app/script/view_model/content/ContentViewModel.js
> refactor: Remove deprecated non-async 'get_conversation_by_id'

- app/page/template/_dist/app.htm
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventBuilder.js
- app/script/conversation/EventMapper.js
- app/script/cryptography/CryptographyMapper.js
- app/script/event/Backend.js
- app/script/event/Client.js
- app/script/event/EventRepository.js
- app/script/event/EventType.js
- app/script/event/EventTypeHandling.js
- app/script/message/MessageCategorization.js
- app/script/view_model/ImageDetailViewViewModel.js
- test/unit_tests/cryptography/CryptographyMapperSpec.js
> refactor: Align event type naming

- app/script/conversation/ConversationRepository.js
> refactor: Conversation archive behavior

- app/script/calling/CallingRepository.js
- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/TimestampType.js
- app/script/entity/Conversation.js
- app/script/entity/message/Message.js
- app/script/entity/message/MissedMessage.js
- app/script/entity/message/VerificationMessage.js
- app/script/system_notification/SystemNotificationRepository.js
- app/script/view_model/AuthViewModel.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/entity/ConversationSpec.js
> fix: Change conversation timestamp behavior (WEBAPP-3907, WEBAPP-4139)

- app/script/conversation/ConversationRepository.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
> fix: File upload / cancellation behaviour (WEBAPP-4307)

- app/script/components/asset/linkPreviewAsset.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventMapper.js
- app/script/entity/message/LinkPreview.js
- app/style/components/asset/link-preview-asset.less
- test/unit_tests/conversation/EventMapperSpec.js
> fix: Removed link from expired previews from self (WEBAPP-4313)

- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
> fix: Update server timestamp on sent message (WEBAPP-4316)

- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
> fix: Enable clearing of empty conversation (WEBAPP-4316)

- app/page/template/content/conversation/participants.htm
- app/page/template/list/start-ui.htm
- app/page/template/partials/template-user-profile.htm
- app/script/components/userList.js
- app/script/team/TeamRepository.js
- app/script/user/UserRepository.js
> fix: Show guest tag when connection request was accepted (WEBAPP-4194)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Call.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/ConversationService.js
- app/script/conversation/ConversationVerificationStateHandler.js
- app/script/conversation/EventBuilder.js
- app/script/entity/Conversation.js
- app/script/entity/message/Message.js
- app/script/entity/message/MissedMessage.js
- app/script/entity/message/VerificationMessage.js
- app/script/event/EventRepository.js
- app/script/event/WebApp.js
- app/script/view_model/list/ListViewModel.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/conversation/EventBuilderSpec.js
- test/unit_tests/entity/ConversationSpec.js
- ensures messages deletion in database if conversation was cleared remotely
- fix timestamp content and updates for outgoing messages
- update conversation order on backend timestamps only
> fix: Conversation timestamp issues (WEBAPP-4318, WEBAPP-4319)

- app/script/conversation/ConversationRepository.js
> fix: Update local link preview only if original message still present (WEBAPP-3179)

- app/script/conversation/ConversationRepository.js
> fix: Send link preview only if matching text content (WEBAPP-4244)

- app/script/calling/entities/Call.js
- app/script/calling/entities/Flow.js
> fix: Firefox fails to reset flow of established call (WEBAPP-4304)

- app/script/conversation/ConversationRepository.js
> fix: Archive conversation if left by self user (WEBAPP-4166)

- bower.json
> chore: Bump url-search-params-polyfill to version '2.0.1'

- bower.json
> chore: Bump WebRTC-adapter to version '5.0.4'

- app/script/calling/entities/Flow.js
> fix: Remove offerToReceiveVideo from audio call (WEBAPP-4322)

- app/page/template/_dist/app.htm
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventMapper.js
- app/script/entity/Conversation.js
- app/script/util/TimeUtil.js
- app/script/view_model/MessageListViewModel.js
- app/script/view_model/list/ListViewModel.js
> fix: Ensure archiving of left conversation (WEBAPP-4166, WEBAPP-4325)

- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/list/ListViewModel.js
> fix: Leave conversation uses remove member (WEBAPP-4328)

- .eslintrc.yaml
> chore: Disallow trailing whitespace

- bower.json
> chore: Update pako to version '1.0.6'

- app/script/conversation/ConversationMapper.js
- app/script/event/EventRepository.js
- test/unit_tests/conversation/ConversationMapperSpec.js
- test/unit_tests/event/EventRepositorySpec.js
> fix: Reject link preview with non-matching text content

- app/script/extension/GiphyService.js
- test/unit_tests/extension/GiphyRepositorySpec.js
> feat: Proxy requests for random GIFs

- app/script/conversation/ConversationRepository.js
> fix: Set is_team_member on self user (WEBAPP-4350)

- app/page/index.html
- app/page/template/graph.htm
Sync claims with latest messaging copy.
> Align page titles & descriptions

- app/page/index.html
- app/page/template/_deploy/vendor.htm
- app/page/template/_dist/app.htm
- app/page/template/_dist/vendor.htm
- app/page/template/graph.htm
- app/script/auth/URLParameter.js
- app/script/conversation/ConversationRepository.js
- app/script/event/WebApp.js
- app/script/main/app.js
- app/script/tracking/EventName.js
- app/script/tracking/EventTrackingRepository.js
- app/script/tracking/SuperProperty.js
- app/script/ui/WindowHandler.js
- app/script/user/UserRepository.js
- app/script/view_model/AuthViewModel.js
- aws/main.py
- bower.json
- grunt/config/clean.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/tracking/EventTrackingRepositorySpec.js
- test/unit_tests/util/UtilSpec.js
> staging bump 2017-09-21

- app/script/team/TeamRepository.js
- app/script/tracking/EventTrackingRepository.js
- app/script/user/UserRepository.js
> fix: Use members as contacts in teams (WEBAPP-4353)

- app/script/tracking/EventTrackingRepository.js
- app/script/user/UserRepository.js
> fix: Update number of contacts in teams (WEBAPP-4353)

- app/script/tracking/EventTrackingRepository.js
- app/script/tracking/SuperProperty.js
- app/script/tracking/attribute/PlatformType.js
> feat: Add desktop identification properties (WEBAPP-4338)

- app/script/calling/CallingRepository.js
- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/event/WebApp.js
- app/script/team/TeamRepository.js
- app/script/tracking/EventTrackingRepository.js
- app/script/tracking/SuperProperty.js
- app/script/tracking/attribute/PlatformType.js
- app/script/user/UserRepository.js
- test/unit_tests/conversation/ConversationMapperSpec.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/conversation/ConversationServiceNoCompoundSpec.js
- test/unit_tests/conversation/ConversationServiceSpec.js
- test/unit_tests/entity/ConversationSpec.js
- test/unit_tests/system_notification/SystemNotificationRepositorySpec.js
- test/unit_tests/util/DebugUtilSpec.js
> staging bump 2017-09-22

- app/page/template/content/conversation/participants.htm
- app/script/view_model/ParticipantsViewModel.js
- bower.json
Depends on https://github.com/wireapp/webapp-module-bubble/pull/2
Will cut a new bubble version when merged.
> fix: Show participants to add when using shortcut (WEBAPP-2428)

- app/script/conversation/ConversationService.js
- app/script/conversation/ConversationServiceNoCompound.js
- app/script/entity/message/ContentMessage.js
- app/script/user/UserConnectionMapper.js
> refactor: Cleanup array filter

- app/script/storage/StorageService.js
- bower.json
Prepared this as a test upgrade for the impending release of Dexie 2.0.0 (https://github.com/dfahlander/Dexie.js/releases/tag/v2.0.0)
> chore: Bump Dexie to version '2.0.0'

- app/script/view_model/ParticipantsViewModel.js
> fix: Fall back to group participants for guest conversations (WEBAPP-4356)

- app/script/tracking/EventTrackingRepository.js
> feat: Reset Mixpanel super properties on logout

- app/page/template/content/conversation/participants.htm
- app/script/conversation/ConversationService.js
- app/script/conversation/ConversationServiceNoCompound.js
- app/script/entity/message/ContentMessage.js
- app/script/lifecycle/UpdateSource.js
- app/script/storage/StorageService.js
- app/script/tracking/EventTrackingRepository.js
- app/script/user/UserConnectionMapper.js
- app/script/view_model/ParticipantsViewModel.js
- bower.json
- package.json
> staging bump 2017-09-25

- .eslintrc.yaml
- .travis.yml
- bin/deployment_notification.js
> refactor: Using latest web app core for deployment notifications

- .travis.yml
> chore: Updated Node.js version for Travis CI

- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventMapper.js
> fix: Handle failed mapping of event on adding to conversation

- app/script/util/util.js
- test/unit_tests/util/UtilSpec.js
> fix: Improve 'z.util.trim_file_extension' for unexpected input

- app/script/conversation/ConversationRepository.js
> fix: Add self to conversation on mapping

- app/script/cryptography/CryptographyRepository.js
> fix: Type of UserError not part of prototype

- app/page/template/_prod/vendor.htm
> fix: Load Mixpanel from local sources

- app/script/user/UserRepository.js
- app/script/view_model/content/PreferencesAccountViewModel.js
> fix: Skip availability check for invalid handles

- app/script/search/SearchRepository.js
> fix: Always search perfect match for valid username

- app/page/template/list/conversations.htm
> feat: Change order of conversation list action icons (WEBAPP-4362)

- app/page/template/content/preferences-account.htm
- app/style/content/preferences/account.less
> feat: Preferences - Account page tweaks (WEBAPP-4363)

- app/script/view_model/content/PreferencesAccountViewModel.js
- test/unit_tests/user/UserHandleGeneratorSpec.js
> fix: Username input verification in automation (WEBAPP-4364)

- app/script/event/WebApp.js
- app/script/main/app.js
- app/script/properties/PropertiesRepository.js
- app/script/team/TeamRepository.js
- app/script/tracking/EventTrackingRepository.js
- app/script/tracking/SuperProperty.js
- test/api/TestFactory.js
> feat: Add team related event properties (WEBAPP-4334)

- app/script/util/KeyboardUtil.js
- app/script/view_model/AuthViewModel.js
> fix: InputEvents are different from KeyboardEvents

- app/page/template/modals.htm
- app/script/bot/BotRepository.js
- app/script/localization/webapp.js
- app/script/view_model/ModalsViewModel.js
> feat: Add bot unavailable modal (WEBAPP-4367)

- app/page/template/_dist/app.htm
- app/script/auth/AccessTokenError.js
- app/script/auth/AuthRepository.js
- app/script/auth/AuthService.js
- app/script/conversation/ConversationRepository.js
- app/script/event/WebSocketService.js
- app/script/service/BackendClient.js
- app/script/service/QueueState.js
- app/script/util/PromiseQueue.js
- test/unit_tests/service/BackendClientSpec.js
> fix: Unblock request queue immediately after access token refresh (WEBAPP-4093)

- app/script/components/userInput.js
- app/script/util/KeyboardUtil.js
> fix: Allow selection removal with backspace and del keys (WEBAPP-4370)

- app/script/util/DebugUtil.js
> refactor: Cleanup of DebugUtil

- bower.json
> chore: Update dexie to version 2.0.1

- app/script/auth/AuthRepository.js
- app/script/event/WebSocketService.js
> refactor: Move reconnect trigger to WebSocketService

- app/script/auth/AuthRepository.js
- app/script/components/userInput.js
- app/script/event/WebSocketService.js
- app/script/util/DebugUtil.js
- app/script/util/KeyboardUtil.js
- bower.json
- package.json
> staging bump 2017-10-04

- app/script/tracking/EventTrackingRepository.js
> feat: Enable Mixpanel on auth page (WEBAPP-4324, WEBAPP-4332)

- aws/config.py
- aws/util.py
> chore: Increase required browser versions

- app/page/template/partials/template-user-profile.htm
- app/script/assets/AssetService.js
- app/script/audio/AudioRepository.js
- app/script/calling/CallingRepository.js
- app/script/calling/SDPMapper.js
- app/script/calling/entities/Flow.js
- app/script/calling/entities/FlowAudio.js
- app/script/entity/message/Message.js
- app/script/event/EventRepository.js
- app/script/ui/ContextMenu.js
- app/script/util/PromiseQueue.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/bindings/SearchBindings.js
- app/script/view_model/content/ContentViewModel.js
> cleanup: Remove explicit true/false

- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/event/EventRepository.js
> fix: Update server timestamp on link preview update (WEBAPP-4374)

- app/page/template/partials/template-user-profile.htm
- app/script/assets/AssetService.js
- app/script/audio/AudioRepository.js
- app/script/calling/CallingRepository.js
- app/script/calling/SDPMapper.js
- app/script/calling/entities/Flow.js
- app/script/calling/entities/FlowAudio.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/entity/message/Message.js
- app/script/event/EventRepository.js
- app/script/telemetry/calling/CallTelemetry.js
- app/script/tracking/EventTrackingRepository.js
- app/script/ui/ContextMenu.js
- app/script/util/PromiseQueue.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/bindings/SearchBindings.js
- app/script/view_model/content/ContentViewModel.js
- app/style/common/variables.less
- aws/config.py
- aws/util.py
- package.json
> staging bump 2017-10-05

- app/script/calling/CallingRepository.js
> fix: Confirm PROPSYNC message only as call participant (WEBAPP-4376)

- app/script/calling/CallingRepository.js
- app/script/telemetry/calling/CallTelemetry.js
> fix: Use proper video call events (WEBAPP-4375, WEBAPP-4377)

- app/script/auth/AuthService.js
- app/script/calling/CallingRepository.js
- app/script/localization/translations/webapp-es.js
- app/script/localization/translations/webapp-pt.js
- app/script/localization/translations/webapp-uk.js
- app/script/telemetry/calling/CallTelemetry.js
> staging bump 2017-10-05#2

- app/page/template/partials/template-message.htm
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventBuilder.js
- app/script/conversation/EventMapper.js
- app/script/entity/message/MemberMessage.js
- app/script/entity/message/RenameMessage.js
- app/script/localization/webapp.js
> fix: Show name in team member leave message (WEBAPP-4378)

- app/page/template/_dist/app.htm
- app/page/template/content/preferences-account.htm
- app/script/config.js
- app/script/entity/User.js
- app/script/localization/webapp.js
- app/script/team/TeamMapper.js
- app/script/team/TeamPermission.js
- app/script/team/TeamRepository.js
- app/script/team/TeamRole.js
- app/script/util/Environment.js
- app/script/view_model/content/PreferencesAccountViewModel.js
Also exposes the role to https://github.com/wireapp/wire-desktop
> feat: Add option to manage teams (WEBAPP-4380)

- bower.json
> chore: Update moment to version 2.19.0

- bower.json
> chore: Update webrtc-adapter to version 5.0.5

- aws/main.py
> chore: Update X-Wire header

- app/page/template/content/preferences-account.htm
> feat: Move team create and manage in preferences (WEBAPP-4384)

- app/page/template/partials/template-user-profile.htm
> fix: Localize privacy link (WEBAPP-4387)

- app/script/view_model/AuthViewModel.js
- app/script/view_model/content/PreferencesAccountViewModel.js
> fix: URLUtil is part of z.util (WEBAPP-4388)

- app/script/localization/translations/webapp-fr.js
- app/script/localization/translations/webapp-hu.js
- app/script/localization/translations/webapp-lt.js
- app/script/localization/translations/webapp-ru.js
> chore: Sync translations

- bower.json
> chore: Update moment to version 2.19.1

- bower.json
> chore: Update raygun4js to version 2.8.1

- app/page/template/list/takeover.htm
- app/script/localization/translations/webapp-cs.js
- app/script/localization/translations/webapp-da.js
- app/script/localization/translations/webapp-de.js
- app/script/localization/translations/webapp-el.js
- app/script/localization/translations/webapp-es.js
- app/script/localization/translations/webapp-et.js
- app/script/localization/translations/webapp-fi.js
- app/script/localization/translations/webapp-fr.js
- app/script/localization/translations/webapp-hr.js
- app/script/localization/translations/webapp-hu.js
- app/script/localization/translations/webapp-it.js
- app/script/localization/translations/webapp-lt.js
- app/script/localization/translations/webapp-nl.js
- app/script/localization/translations/webapp-pl.js
- app/script/localization/translations/webapp-pt.js
- app/script/localization/translations/webapp-ro.js
- app/script/localization/translations/webapp-ru.js
- app/script/localization/translations/webapp-sk.js
- app/script/localization/translations/webapp-sl.js
- app/script/localization/translations/webapp-tr.js
- app/script/localization/translations/webapp-uk.js
- app/script/localization/webapp.js
- app/style/list/takeover.less
> feat: Remove username takeover headline (WEBAPP-4395)

- app/script/cryptography/CryptographyMapper.js
- app/script/cryptography/CryptographyRepository.js
> fix: Show proper error for broken external message (WEBAPP-4394)

- app/page/template/list/archive.htm
- app/page/template/list/conversations.htm
- app/page/template/list/preferences.htm
- app/page/template/list/start-ui.htm
- app/style/list/list.less
> fix: Truncate long team name on conversation list (WEBAPP-4383)

- app/script/view_model/content/ContentViewModel.js
- app/script/view_model/list/ConversationListViewModel.js
- app/script/view_model/list/ListViewModel.js
> fix: Enable switching to call with next/prev conversation shortcut (WEBAPP-4295)

- app/script/event/Backend.js
- app/script/team/TeamRepository.js
- app/script/team/TeamService.js
> feat: Update and publish team role of self on team.member-update (WEBAPP-4398)

- app/script/tracking/EventTrackingRepository.js
> fix: Events on auth are missing super properties (WEBAPP-4405)

- .github/ISSUE_TEMPLATE.md
> chore: Update issue template

- app/script/view_model/list/StartUIViewModel.js
> fix: Only hide existing invite bubbles

- app/script/conversation/ConversationRepository.js
> fix: Ensure payload for known clients in targeted messages

- app/script/tracking/EventTrackingRepository.js
- app/script/tracking/SuperProperty.js
> feat: Add app versions to analytics events (WEBAPP-4415)

- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
> fix: Do not mark conversation as verified without mapped participants (WEBAPP-4404)

- app/script/view_model/AuthViewModel.js
> fix: Add login event for team settings redirect

- app/script/tracking/SuperProperty.js
> fix: Super property name is 'App Version'

- app/script/assets/AssetService.js
> chore: Cleanup asset URL generation

- app/script/user/UserService.js
Instead of `UserService.URL.PROPERTIES` we are using `PropertiesService.CONFIG.URL_PROPERTIES`.
> chore: Removed unused "UserService.URL.PROPERTIES"

- bower.json
> chore: Update js-cookie to version 2.2.0

- app/script/telemetry/calling/CallTelemetry.js
> fix: Use get_number_of_participants for conversation (WEBAPP-4442)

- .travis.yml
- bin/deployment_notification.js
> chore: Updating lockfiles with Greenkeeper

- app/script/view_model/content/ContentViewModel.js
> fix: Validate input in show conversation

- .travis.yml
- package.json
> fix: Webapp Bot reportings

- .eslintrc.yaml
- app/page/auth_new.html
- app/script/auth/configureStore.js
- app/script/auth/main.js
- app/script/auth/module/reducer/index.js
- app/script/auth/page/Root.js
- package.json
- webpack.config.dev.js
- yarn.lock
> refactor: React + HMR + Redux

- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventBuilder.js
- app/script/main/app.js
- app/script/team/TeamRepository.js
> fix: Use backend time for team member removal message (WEBAPP-4452)

- app/script/config.js
> chore: Update URL of staging website

- app/script/conversation/ConversationRepository.js
- app/script/event/EventRepository.js
- app/script/localization/translations/webapp-cs.js
- app/script/localization/translations/webapp-da.js
- app/script/localization/translations/webapp-de.js
- app/script/localization/translations/webapp-el.js
- app/script/localization/translations/webapp-es.js
- app/script/localization/translations/webapp-et.js
- app/script/localization/translations/webapp-fi.js
- app/script/localization/translations/webapp-fr.js
- app/script/localization/translations/webapp-hr.js
- app/script/localization/translations/webapp-hu.js
- app/script/localization/translations/webapp-it.js
- app/script/localization/translations/webapp-lt.js
- app/script/localization/translations/webapp-nl.js
- app/script/localization/translations/webapp-pl.js
- app/script/localization/translations/webapp-pt.js
- app/script/localization/translations/webapp-ro.js
- app/script/localization/translations/webapp-ru.js
- app/script/localization/translations/webapp-sk.js
- app/script/localization/translations/webapp-sl.js
- app/script/localization/translations/webapp-tr.js
- app/script/localization/translations/webapp-uk.js
- app/script/localization/webapp.js
- app/script/main/app.js
- app/script/view_model/LoadingViewModel.js
> feat: Show load progress messages on production (WEBAPP-4450)

- package.json
- yarn.lock
> chore(package): update sinon to version 4.1.1

- app/script/tracking/EventTrackingRepository.js
> chore: Updated to latest Raygun API

- package.json
- yarn.lock
> chore(package): update @wireapp/core to version 0.0.5

- package.json
> chore: Update moment to version 2.19.2

- app/script/conversation/ConversationRepository.js
- yarn.lock
> fix: Retrieve messages from the future from the database (WEBAPP-4480)

- app/script/view_model/content/PreferencesAccountViewModel.js
> fix: Allow name with minimum length (WEBAPP-4481)

- package.json
> chore: Update webrtc-adapter to version 6.0.2

- app/script/auth/page/CreateAccount.js
- app/script/auth/page/TeamName.js
Adds data-uie-names for automation on
* Name Your Team page
* Create Account page
> data-uie-names for new auth flow

- app/script/auth/page/Verify.js
Adds datat-uie-names for automation on verified page
> data-uie-names for verify page

- .eslintrc.yaml
- app/script/auth/Environment.js
- app/script/auth/config.js
- app/script/auth/configureStore.js
- app/script/auth/configureTracking.js
- app/script/auth/main.js
- app/script/auth/module/action/TrackingAction.js
- app/script/auth/module/action/creator/TrackingActionCreator.js
- app/script/auth/page/Index.js
- app/script/tracking/EventTrackingRepository.js
- package.json
- yarn.lock
> feat: Start page tracking (WEBAPP-4486)

- app/page/login.html
- app/script/view_model/AuthViewModel.js
- app/style/auth/base.less
> feat: Back button to new onboarding experience

- app/page/login.html
- app/script/view_model/AuthViewModel.js
- app/style/auth/account.less
- app/style/auth/base.less
> fix: Adjust login page behavior

- app/script/auth/page/CreateAccount.js
- app/script/auth/page/InitialInvite.js
- app/script/auth/page/Verify.js
Adding data-uie-names for error-messages on account setup, verification and invite page.
> data-uie-names for error messages

- bin/deployment_notification.js
> chore: Notify about edge deployments

- app/script/auth/page/TeamName.js
> chore: Update what is link in team creation flow (WEBAPP-4504)

- app/script/auth/configureEnvironment.js
- app/script/auth/page/Index.js
- app/script/auth/util/RuntimeUtil.js
> feat: Added platform detection for Start screen tracking (WEBAPP-4502)

- app/script/auth/module/action/TrackingAction.js
- app/script/auth/page/Index.js
- app/script/auth/page/Verify.js
> feat: Adding platform attributes to all tracking events (WEBAPP-4502) (WEBAPP-4509)

- bin/deployment_notification.js
> chore: Update to latest "core" API

- package.json
> chore: Update webRTC-adapter to version 6.0.3

- app/script/auth/page/Index.js
- app/script/auth/page/Verify.js
window.location will be replaced with a workaround for selenium webdriver. Otherwise the chromedriver gets stuck with "Timed out receiving message from renderer", because the renderer process gets unattached.
> Workaround for webdriver

- app/script/components/list/conversationListCell.js
- app/script/components/userList.js
Use special data-uie-name for items in search and contact list to avoid conflict with status in header.
> Use special data-uie-name for items in search and contact list

- app/script/extension/GiphyService.js
> refactor(giphy): Remove dependencies to jQuery & Lodash

- app/script/components/availabilityState.js
> style: Improve svg for availability state busy

- README.md
> docs: Update login page URL

- crowdin.yaml
https://github.com/crowdin/crowdin-cli-2#changed-strings-update
> fix: Crowdin - Update as unapproved

- app/style/components/device-card.less
> fix: Margins for fingerprints in client info

- app/script/components/availabilityState.js
> refactor: Use text binding for availability label

- app/script/auth/util/RuntimeUtil.js
> fix: Add z.util.Environment namespace (WEBAPP-4570)

- app/script/components/deviceCard.js
> fix: Use plain client ID for "data-uie-uid"

- app/script/extension/GiphyService.js
- test/unit_tests/extension/GiphyRepositorySpec.js
Implements https://github.com/zinfra/hegemony/pull/1064
> chore: Move all /giphy API requests to /proxy/giphy

- app/page/template/content/conversation/participants.htm
> chore: Add data-uie-names for adding services in people

- app/page/template/content/conversation/participants.htm
- app/script/components/serviceList.js
> chore: data-uie-names for service items and service confirmation

- app/page/login.html
- app/page/template/content/collection-details.htm
- app/page/template/content/collection.htm
- app/page/template/content/connect-requests.htm
- app/page/template/content/conversation/conversation-titlebar.htm
- app/page/template/content/conversation/giphy.htm
- app/page/template/content/conversation/participants.htm
- app/page/template/content/preferences-about.htm
- app/page/template/content/preferences-device-details.htm
- app/page/template/content/preferences-devices.htm
- app/page/template/list/start-ui.htm
- app/page/template/partials/template-confirm.htm
- app/page/template/partials/template-message.htm
- app/page/template/partials/template-user-profile.htm
- app/script/auth/page/CreateAccount.js
- app/script/auth/page/CreatePersonalAccount.js
- app/script/auth/page/Index.js
- app/script/auth/page/InitialInvite.js
- app/script/auth/page/TeamName.js
- app/script/components/asset/controls/mediaButton.js
- app/script/components/asset/fileAsset.js
- app/script/components/asset/linkPreviewAsset.js
- app/script/components/asset/locationAsset.js
- app/script/components/asset/videoAsset.js
- app/script/components/availabilityState.js
- app/script/components/deviceCard.js
- app/script/components/fullSearch.js
- app/script/components/list/conversationListCallingCell.js
- app/script/components/list/conversationListCell.js
- app/script/components/userAvatar.js
Search: `(data-uie-name="[^"]+")([ \\n]*)([a-z][^/>]*)( */?>)`
Replace: `$3$2$1$4`
(Thanks @AndyLnd)
> Move data-uie to the end

- app/page/index.html
- app/page/template/graph.htm
- aws/main.py
> Remove period from the title

- app/script/view_model/content/GroupCreationViewModel.js
> fix: Disable autoclose on modal

- app/script/calling/CallMessageMapper.js
> fix: Destructuring of spec calling message (WEBAPP-4723)

- app/script/auth/page/InitialInvite.js
- app/script/components/userProfile.js
- app/script/event/EventRepository.js
- app/script/view_model/list/StartUIViewModel.js
> chore: Change Boolean to !!

- app/page/template/panel/group-participant.htm
- app/script/components/icons.js
Services still need to get a proper design.
> feat: group-participant (w/o services)

- app/style/content/conversation/title-bar.less
- app/style/framework.less
> fix: Guest badge BG color & Z-axis positioning

- app/page/template/panel/conversation-details.htm
- app/style/panel/conversation-details.less
> fix: Break word in conversation name

- app/style/components/list/participant-item.less
- app/style/panel/conversation-details.less
- app/style/panel/panel.less
> fix: Action-item & icon margins

- app/page/template/panel/conversation-details.htm
- app/style/panel/conversation-details.less
> fix: Panel counter margins

- app/page/template/panel/conversation-details.htm
- app/page/template/panel/group-participant.htm
- app/script/view_model/panel/ConversationDetailsViewModel.js
- app/style/panel/conversation-details.less
Add the expected icon behavior. Partially unstyled.
> feat: Add verified icon to panel views

- app/page/template/panel/conversation-details.htm
- app/style/panel/conversation-details.less
> fix: Devices action margin

- app/page/template/content/conversation/title-bar.htm
- app/page/template/panel/conversation-details.htm
- app/style/content/conversation/title-bar.less
- app/style/panel/conversation-details.less
> fix: Verified state styles

- app/page/template/panel/conversation-details.htm
- app/style/panel/panel.less
Fixes left aligned close icon when mute toggle was not shown.
> fix: Reverse order of panel header icons

- app/script/view_model/VideoCallingViewModel.js
> fix: Screensharing from call

- bin/deployment_notification.js
> chore: Permanent client for Webapp Bot

- bin/deployment_notification.js
> fix: Add missing import for Webapp Bot

- bin/deployment_notification.js
**Note to myself:** Create a `travis-bot` npm package to avoid these kind of fixes. This could also make use of `'generate-changelog'`.
> fix: Login for Webapp Bot

- bin/deployment_notification.js
> fix: Revert to temporary clients for Webapp Bot

- app/script/cryptography/CryptographyRepository.js
- app/script/event/EventRepository.js
Added `eventType` to decryption error logs.
> chore: Log type of event, which could not be decrypted

- app/script/auth/component/AppAlreadyOpen.jsx
I tried to use the same data-uie-names as for the other modals.
> chore: data-uie-names for already-open modal

- app/script/telemetry/calling/CallLogger.js
- error log level is 1000
- set default logger level if called without log level
> fix: Set and respect logger level in call logger

- app/demo/demo.html
- app/page/template/list/start-ui.htm
- app/style/auth/base.less
- app/style/common/modal.less
- app/style/components/asset/video-asset.less
- app/style/components/calling/choose-screen.less
- app/style/components/search-list.less
- app/style/components/user-profile.less
- app/style/content/conversation.less
- app/style/content/conversation/title-bar.less
- app/style/list/invite-bubble.less
- app/style/list/list.less
- app/style/list/start-ui.less
- app/style/loading-screen.less
- app/style/modal/giphy.less
- app/style/panel/add-participants.less
- app/style/panel/participant-devices.less
- yarn.lock
> fix: Create group icon alignment (WEBAPP-4891)

- app/style/common/badge.less
- app/style/common/button-round.less
- app/style/common/button.less
- app/style/common/checkbox.less
- app/style/common/colors.less
- app/style/common/input.less
- app/style/common/modal.less
- app/style/components/asset/controls/seek-bar.less
- app/style/components/availability-state.less
- app/style/components/device-card.less
- app/style/components/device-remove.less
- app/style/components/ephemeral-timer.less
- app/style/components/input-element.less
- app/style/components/participant-avatar.less
- app/style/components/search-list.less
- app/style/components/user-input.less
- app/style/components/user-profile.less
- app/style/content/connect-requests.less
- app/style/content/conversation/input-bar.less
- app/style/content/conversation/message-list.less
- app/style/content/conversation/title-bar.less
- app/style/content/preferences/account.less
- app/style/list/conversations.less
- app/style/list/invite-bubble.less
- app/style/list/list.less
- app/style/list/start-ui.less
- app/style/modal/group-creation.less
- app/style/video-calling.less
It was inconsistent.. so let's go with the less is more version :)
> refactor: Remove parenthesis from mixins in Less

- app/script/entity/message/ContentMessage.js
- app/script/event/EventRepository.js
- app/script/localization/Localizer.js
- app/script/util/util.js
- truthy first
- += 1
- forgotten Localization camelCase
> fix: Random stuff

- app/script/auth/configureStore.js
- package.json
- yarn.lock
https://github.com/wireapp/wire-web-packages/pull/427
> chore: Enable core library logging in dev environment

- app/i18n/webapp-de.json
> fix: Gästezimmer -> Gästebereich

- app/script/auth/component/AccountForm.js
- app/script/auth/module/action/AuthAction.js
- app/script/auth/page/ConversationJoin.jsx
- app/script/auth/util/AccentColor.js
> feat: Random accent colors for Wireless, Personal & Organisation registrations (WEBAPP-4983)

- app/script/backup/BackupRepository.js
according to https://github.com/wireapp/architecture/tree/master/topics/backup#metadata-file
> Fix metadata filename

- app/script/backup/BackupRepository.js
- app/script/backup/Error.js
- app/script/view_model/content/HistoryImportViewModel.js
previously metadata check wouldn't actually stop the import and the UI would show up in a weird state
> fix: improve import errors 

- app/script/backup/BackupRepository.js
regression introduced in https://github.com/wireapp/wire-webapp/pull/3217
> fix: filter metadata file in the import process

- app/script/view_model/content/HistoryExportViewModel.js
Use the `deflate` algorithm to compress the export archive file
> fix: compress export archive file (WEBAPP-5008)

- app/script/tracking/EventName.js
- app/script/view_model/content/HistoryExportViewModel.js
- app/script/view_model/content/HistoryImportViewModel.js
> feat: Add tracking for history backup/restore (WEBAPP-4923)

- app/script/auth/module/action/RuntimeAction.js
- app/script/util/Environment.js
Adds missing check around `indexedDB` access
This, alone, will not fix `WEPAPP-4988`. It's still missing a patch from `dexie`
> fix: Wrap all accesses to indexedDB in try-catch blocks (WEBAPP-4988)

- app/page/template/content/preferences-options.htm
@lucilacaranza 🙈  Sorry about that one. Will be part of the next public release.
> fix: Enable calling logs on production

- .travis.yml
> fix: Downgrade "travis-bot" to stable version

- app/page/template/_dist/app.htm
- app/page/template/video-calling.htm
- app/script/components/groupVideoGrid.js
- app/script/view_model/VideoCallingViewModel.js
- app/style/components/group-video-grid.less
- app/style/main.less
- test/unit_tests/components/groupVideoGridSpec.js
Adds the `group-video-grid` component. Able to display all the participants streams in a standalone grid
> feat: group video UI grid

- app/script/auth/component/AcceptNewsModal.jsx
- app/script/auth/page/ChooseHandle.js
- app/script/auth/page/Login.js
- app/script/strings.js
> feat: Accept news modal

- app/script/components/groupVideoGrid.js
wrap the `groupVideoGrid` component in an IIFE to avoid adding functions to the root scope
> fix: avoid global scope pollution

- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/entity/message/Message.js
- app/script/view_model/ActionsViewModel.js
- app/script/view_model/ListViewModel.js
- test/unit_tests/entity/ConversationSpec.js
> fix: Unarchive conversation on call (WEBAPP-5105)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/CallEntity.js
- app/script/calling/entities/FlowEntity.js
- app/script/media/MediaDevicesHandler.js
- app/script/media/MediaError.js
- app/script/media/MediaStreamHandler.js
- app/script/media/MediaStreamInfo.js
- app/script/view_model/VideoCallingViewModel.js
- app/script/view_model/content/PreferencesAVViewModel.js
- test/unit_tests/media/MediaStreamHandlerSpec.js
> fix: Allow audio toggling on incoming audio call (WEBAPP-5113)

- app/script/components/groupVideoGrid.js
The tag data-uie-name was added for being able to automatically check if the video is paused
> chore: data-uie-name for paused video

- app/script/components/availabilityState.js
We need to grab the label directly to not get the initials from the avatar on accident.
> chore: data-uie-name for label in call participants list

- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/ConversationService.js
- app/script/view_model/panel/TimedMessagesViewModel.js
- test/unit_tests/conversation/ConversationMapperSpec.js
includes:
- client updating the server
- client slow sync with the server on app load
doesn't include:
- handling the new `message-timer-update` server event
> feat: Server and client synchronization

- aws/config.py
https://github.com/wireapp/wire-team-settings/pull/790
https://github.com/wireapp/wire-website/pull/558
> chore: Increase required Firefox to ESR version 60 (WEBAPP-5214)

- app/page/login.html
- app/page/template/content/collection-details.htm
- app/page/template/content/collection.htm
- app/page/template/list/archive.htm
- app/page/template/panel/timed-messages.htm
- app/page/template/partials/template-message.htm
- app/script/components/calling/chooseScreen.js
- app/script/components/calling/deviceToggleButton.js
- app/script/components/inputLevel.js
- app/script/components/list/groupAvatar.js
I inlined all possible knockout foreach bindings. Review with `Hide whitespace changes` enabled to see the minimal changes.
> refactor: Cleanup of foreach bindings

- app/script/components/messageTimerButton.js
> chore: Adjust messageTimerButton code indentation

- app/script/ui/ViewportObserver.js
Here is a quick suggestion, let's use a map to handle the association element => callback.
Also, this might not have any impact, but with this new version the IntersectionObserver is instantiated only once and is idle when there is no node to observe.
> refactor: simplifies viewport observer using Map

- app/script/main/app.js
- app/script/util/DebugUtil.js
Open any conversation and execute `await wire.app.util.debug.getLastMessagesFromDatabase()` to retrieve the last 10 messages from the database (latest is on top). The amount of messages and targeted conversation can be changed.
> chore: Debug utility to retrieve recent messages from database

- app/script/util/Environment.js
> fix: Add safeguard to platform checks

- app/script/auth/module/action/AuthAction.js
- app/script/auth/module/action/BackendError.js
- app/script/auth/module/action/ClientAction.js
- app/script/auth/module/action/ConversationAction.js
- app/script/auth/module/action/InviteAction.js
- app/script/auth/module/action/SelfAction.js
- app/script/auth/module/action/UserAction.js
- app/script/auth/module/action/creator/AuthActionCreator.js
- app/script/auth/module/action/creator/ClientActionCreator.js
- app/script/auth/module/action/creator/ConversationActionCreator.js
- app/script/auth/module/action/creator/InviteActionCreator.js
- app/script/auth/module/action/creator/SelfActionCreator.js
- app/script/auth/module/action/creator/UserActionCreator.js
This is part 1 for removing the application side error handling
> refactor: Leave error transformation to @wireapp/core

- app/script/components/ephemeralTimer.js
- app/style/components/ephemeral-timer.less
This makes the animated pie a little easier on the GPU by not animating at 60 fps but only updating it in 40 steps.
> fix: take a little strain off the GPU, add border (WEBAPP-5235)

- app/script/conversation/ConversationRepository.js
https://github.com/wireapp/wire-team-settings/pull/971
> feat: Increase group size to 300 participants (WEBAPP-5318)

- app/script/conversation/ConversationRepository.js
Before the change we parallelized the generation of the optimistic event and the actual sending of the message.
Thing is, because of the single-threaded nature of JavaScript, if a crypto operation started before the optimistic event is generated, it would block this same generation.
Instead of parallelizing, we now generate the optimistic event, add it to the view and only then start sending the message (which will trigger all the crypto operations needed)
Time to show optimistic message (on my machine) when from `~100ms` down to `~20ms`
> fix: improve perceived performance by un-parallelizing crypto operations (WEBAPP-5328)

- app/page/template/content/conversation/title-bar.htm
- app/script/localization/webapp.js
- app/script/team/TeamRepository.js
- app/script/user/UserRepository.js
- app/script/view_model/content/TitleBarViewModel.js
- app/style/content/conversation/title-bar.less
1. Bots will no longer be considered guests in conversations.
2. In order to visualize their existence in a group the "Bots are present" badge has been added.
> feat: Add badge if bot is present in conversation

- karma.conf.js
- test/api/TestFactory.js
- test/unit_tests/cache/CacheRepositorySpec.js
- test/unit_tests/cryptography/CryptographyMapperSpec.js
- test/unit_tests/extension/GiphyRepositorySpec.js
- test/unit_tests/service/BackendClientSpec.js
- test/unit_tests/tracking/EventTrackingRepositorySpec.js
- test/unit_tests/user/UserMapperSpec.js
- test/unit_tests/user/UserServiceSpec.js
> refactor: Less verbose unit test logs

- test/api/TestFactory.js
- test/unit_tests/conversation/ClientMismatchHandlerSpec.js
- test/unit_tests/cryptography/CryptographyRepositorySpec.js
- test/unit_tests/event/EventRepositorySpec.js
from `~1min 15s` to `~15s`  for the tests to run
> chore: Mock cryptobox by default to speedup test dependencies creation

- app/script/view_model/AuthViewModel.js
Regression introduced with https://github.com/wireapp/wire-webapp/pull/4312
> fix: Add missing EventService from the EventRepo constructor (WEBAPP-5363)

- app/page/template/_dist/app.htm
- app/script/conversation/ConversationRepository.js
- app/script/event/EventRepository.js
- app/script/event/preprocessor/ServiceMiddleware.js
- app/script/main/app.js
- test/unit_tests/event/preprocessor/ServiceMiddlewareSpec.js
Simple mechanism to be able to plug custom event processors before the EventRepository actually processes the event
> feat: Preprocess services related events (WEBAPP-5353)

- app/script/conversation/ConversationRepository.js
- app/script/conversation/ConversationService.js
- app/script/event/EventService.js
- app/script/event/EventServiceNoCompound.js
- test/unit_tests/conversation/ConversationServiceSpec.js
- test/unit_tests/event/EventServiceNoCompoundSpec.js
- test/unit_tests/event/EventServiceSpec.js
> refactor: Move methods to load events (WEBAPP-5372)

- test/unit_tests/audio/AudioRepositorySpec.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/media/MediaEmbedsSpec.js
- test/unit_tests/team/TeamRepositorySpec.js
- test/unit_tests/user/UserRepositorySpec.js
Current status:
- 1 flaky test re-enabled (second chance)
- `915` tests, `0` skipped
> fix: Revisit skipped tests

- app/script/conversation/ClientMismatchHandler.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventBuilder.js
- app/script/util/ArrayUtil.js
- test/unit_tests/conversation/ClientMismatchHandlerSpec.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
> fix: Add missing participant to conversation (WEBAPP-5381)

- README.md
> fix: Update local URLs in readme

- app/script/auth/page/ConversationJoin.jsx
> fix: Open in Wire button wrap

- app/script/strings.js
See related ticket WEBAPP-5424 & 71f6418 for color change.
> Use Personal/Pro on account/team creation screen

- app/script/view_model/content/InputBarViewModel.js
- test/unit_tests/view_model/InputBarViewModelSpec.js
This is just the method for parsing the mentions from the input. Nothing happens with that for now.
> feat: Parse mentions from message input (WEBAPP-5443)

- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventMapper.js
- app/script/message/MentionEntity.js
- test/unit_tests/message/MentionEntitySpec.js
- checks validity of mentions before sending
- add new validation case: mention has to start with @ in message text
- adds test for new validation case
>  fix: Check mention validity on message sending (WEBAPP-5532)

- app/page/template/content/conversation/input-bar.htm
- app/script/view_model/bindings/CommonBindings.js
Will prevent reflow operations to block the thread while typing in the textarea
> refactor: Run textarea resizing asynchronously (WEBAPP-5548)

- app/script/localization/webapp.js
- app/script/notification/NotificationRepository.js
- app/script/ui/Shortcut.js
- app/script/ui/ShortcutType.js
- app/script/view_model/ContentViewModel.js
- app/script/view_model/ListViewModel.js
- app/script/view_model/content/CollectionViewModel.js
This PR doesn't take care of the shortcuts yet. It has to be determined how they should behave.
> feat: Open notification settings from context menu (WEBAPP-5559)

- .travis.yml
Updating to a version which includes error reporting.
> chore: Update @wireapp/changelog-bot to version 1.0.35

- app/page/template/_dist/app.htm
- app/script/event/EventRepository.js
- app/script/main/app.js
- app/script/server/ServerTimeOffsetRepository.js
- app/script/user/UserMapper.js
- app/script/user/UserRepository.js
- test/api/TestFactory.js
- test/unit_tests/server/ServerTimeOffsetRepositorySpec.js
Will migrate all the place that depend on the server time offset to consume this new class in a followup PR
> refactor: Create the server time offset repository (WEBAPP-5588)

- app/page/template/_dist/app.htm
- app/script/calling/CallingRepository.js
- app/script/conversation/ClientMismatchHandler.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/ConversationVerificationStateHandler.js
- app/script/conversation/EventBuilder.js
- app/script/entity/Conversation.js
- app/script/event/EventRepository.js
- app/script/event/WebApp.js
- app/script/main/app.js
- app/script/server/ServerTimeOffsetRepository.js
- app/script/time/ServerTimeRepository.js
- app/script/user/UserMapper.js
- app/script/user/UserRepository.js
- app/script/util/TimeUtil.js
- app/script/view_model/AuthViewModel.js
- test/api/TestFactory.js
- test/unit_tests/conversation/ClientMismatchHandlerSpec.js
- test/unit_tests/conversation/EventBuilderSpec.js
- test/unit_tests/entity/ConversationSpec.js
- test/unit_tests/time/ServerTimeRepositorySpec.js
- test/unit_tests/user/UserMapperSpec.js
> refactor: Migrate client/server timestamp diff computation

- .gitignore
- app/script/client/ClientRepository.js
- app/script/view_model/ActionsViewModel.js
> fix: Remove password check when removing client from settings (WEBAPP-5639)

- app/page/template/content/conversation/input-bar.htm
- app/script/view_model/content/InputBarViewModel.js
- app/style/content/conversation/input-bar.less
- your name is shown as a name instead of 'You' in the reply preview
- the message list now respects the height of the input bar including the reply preview
- input gets focus when clicking 'reply'
> fix: input bar behaviour and appearance

- app/script/conversation/ConversationCellState.js
This PR will
* show the reply text for multiple replies in the second line
* show the reply icon for new replies in conversations whose notification settings are set to "Mentions and replies"
> fix: Second line behavior with multiple replies (WEBAPP-5656)

- app/script/calling/CallMessageMapper.js
- app/script/calling/CallingRepository.js
- app/script/calling/entities/CallEntity.js
- app/script/calling/entities/FlowEntity.js
- app/script/client/ClientRepository.js
- app/script/connect/ConnectRepository.js
- app/script/conversation/ConversationEphemeralHandler.js
- app/script/conversation/ConversationRepository.js
- app/script/cryptography/CryptographyMapper.js
- app/script/telemetry/app_init/AppInitTimings.js
- app/script/user/UserRepository.js
- app/script/util/Crypto.js
- app/script/util/DebugUtil.js
- app/script/view_model/panel/ConversationParticipantsViewModel.js
- app/script/view_model/panel/GuestsAndServicesViewModel.js
- app/script/view_model/panel/NotificationsViewModel.js
- app/script/view_model/panel/TimedMessagesViewModel.js
- test/unit_tests/conversation/ConversationMapperSpec.js
- test/unit_tests/media/MediaEmbedsSpec.js
> refactor: Don't destructure single properties

- app/script/view_model/content/MessageListViewModel.js
Because of a change in the way we compute scroll position, we now need to keep track of the scroll position **before** the array of messages change.
> fix: Compute the scrolling position before adding new messages

- app/page/template/_dist/app.htm
- app/page/template/_dist/component.htm
- app/page/template/content/conversation/input-bar.htm
- app/page/template/content/conversation/message-list.htm
- app/page/template/panel/conversation-details.htm
- app/script/components/messageQuote.js
- app/script/conversation/ConversationRepository.js
- app/script/event/preprocessor/QuotedMessageMiddleware.js
- app/script/ui/Modal.js
- app/script/view_model/AuthViewModel.js
- app/script/view_model/ImageDetailViewViewModel.js
- app/script/view_model/ModalsViewModel.js
- app/script/view_model/content/GiphyViewModel.js
- app/script/view_model/content/GroupCreationViewModel.js
- app/script/view_model/content/InputBarViewModel.js
- app/script/view_model/content/MessageListViewModel.js
- app/style/auth/auth.less
- app/style/common/like.less
- app/style/common/modal.less
- app/style/components/asset/video-asset.less
- app/style/content/conversation/input-bar.less
- app/style/content/conversation/message-quote.less
- app/style/main.less
- package.json
- yarn.lock
**fixes**
- general cosmetic improvements of direct replies 
- fix user names in quoted messages that could disappear when editing the original message 
- fix replies validation issue when quoting a link preview
- improve general behavior of the scroll in messages list
- fix a bug where the image viewer could be overlaying the app making it unresponsive to interactions
> Staging bump 2018-11-14

- app/page/template/detail-view.htm
- app/script/components/message.js
- app/script/conversation/EventMapper.js
- app/script/entity/message/Message.js
- test/unit_tests/entity/message/MemberMessageSpec.js
- test/unit_tests/entity/message/MessageEntitiesSpec.js
Unavailable assets (uploading and failed uploading) assets should not be available for reply and reacting. Furthermore all messages which are not in a sending state should be deletable.
> fix: Improve interactions for unavailable assets (WEBAPP-5729)

- package.json
- yarn.lock
Resolves https://github.com/wireapp/wire-desktop/issues/1861
> feat: Increase volume of audio files by 6dB

- .eslintrc.json
- app/script/auth/AuthService.js
- app/script/auth/main.tsx
- app/script/service/BackendClient.js
- package.json
- test/unit_tests/service/BackendClientSpec.js
- yarn.lock
Removing Pako as:
- The browser already manage compression
- See ticket WEBAPP-4292
> fix: Removal of Pako (WEBAPP-4292)

- package.json
- yarn.lock
I hope next time @dependabot will bump this :slightly_smiling_face:
> chore(deps): Bump @wireapp/protocol-messaging to 1.23.0

- app/script/conversation/ConversationRepository.js
Broken since the format of the websocket event changed
> runfix: receipt mode sync between participants of a conversation

- app/style/list/start-ui.less
> fix: Line height for start ui invite section (WEBAPP-5679)

- app/script/localization/webapp.js
> fix: Add 'You' to guest removal message

- app/style/common/modal.less
- app/style/common/variables.less
- app/style/components/asset/video-asset.less
- app/style/components/full-search.less
- app/style/components/input-level.less
- app/style/content/conversation/message-list.less
- app/style/content/preferences.less
- app/style/content/preferences/av.less
- app/style/content/preferences/devices.less
- app/style/list/start-ui.less
> chore: Fix typo in 'seperator'

- app/page/template/content/preferences-about.htm
- app/script/view_model/content/PreferencesAboutViewModel.js
- app/script/view_model/panel/MessageDetailsViewModel.js
This fixes also a small issue with the terms of use url
> runfix: Fix no likes for ephemeral (WEBAPP-5842)

- app/script/assets/AssetTransferState.js
- app/script/components/asset/audioAsset.js
- app/script/components/asset/controls/mediaButton.js
- app/script/components/asset/fileAsset.js
- app/script/components/asset/videoAsset.js
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventMapper.js
- app/script/entity/Conversation.js
- app/script/entity/message/File.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/entity/message/FileSpec.js
This is a preparation for the fix regarding video upload.
> refactor: Add a proper asset state for when upload is pending (WEBAPP-5852)

- app/script/conversation/ConversationRepository.js
> fix: Enable video upload cancelation as soon as preview is being uploaded (WEBAPP-5852)

- app/script/user/UserRepository.js
Reverts wireapp/wire-webapp#5575
> runfix: Attach marketing consent subscriber (revert)

- src/page/template/list/start-ui.htm
- src/page/template/panel/conversation-details.htm
- src/page/template/panel/group-participant-service.htm
- src/page/template/panel/group-participant-user.htm
- src/script/entity/User.js
- src/script/main/app.js
- src/script/team/TeamMapper.js
- src/script/user/UserPermission.js
- test/unit_tests/user/UserPermissionSpec.js
In the future, this helper will host all the permissions for any user of the app. 
So better head toward that direction already ;)
> refactor: rename TeamPermission to UserPermission

- src/page/template/content/preferences-account.htm
- src/page/template/list/start-ui.htm
- src/page/template/panel/add-participants.htm
- src/page/template/panel/conversation-details.htm
- src/page/template/panel/group-participant-service.htm
- src/page/template/panel/group-participant-user.htm
- src/script/main/app.js
This will allow the view to refresh when roles are changed from the admin panel'
> runfix: Make the user's permission observable

- src/script/auth/page/SingleSignOn.tsx
- src/script/auth/route.ts
This PR makes it possible to prefill the SSO code by entering a URL like this:
- http://localhost:8081/auth/?sso_code=wire-26233198-77f3-4aac-97ad-03de41168ab7#sso
> feat: Prefill SSO code via URL query

- package.json
- yarn.lock
@dependabot didn't catch this one :slightly_frowning_face:
> chore(deps-dev): Bump @wireapp/copy-config from 0.2.4 to 0.3.0

- src/page/template/content/conversation/message-list.htm
- src/script/components/message.js
- src/script/components/messageQuote.js
- src/script/view_model/content/MessageListViewModel.js
- test/unit_tests/components/messageSpec.js
as of #5802 the locationRepository is not used anymore.
There still was traces of it in components.
> refactor: Clean deprecated references to locationRepo

- package.json
- src/script/auth/main.tsx
- src/script/main/SingleInstanceHandler.js
- src/script/main/globals.js
- src/script/util/TimeUtil.js
- tsconfig.json
This PR uses a JS file (`/util/LoggerUtil.js`) inside a TSX file (`/auth/main.tsx`). Because of that we need to tell the `tsconfig.json` to use JS (`"allowJs": true`).
With `"allowJs": true` the TypeScript compiler checks our JavaScript code (which is a good thing!) and fails if it sees type mismatches. I resolved the type mismatches and made the PR compile.
> feat: Enable logging on auth page via parameter

- .gitignore
- server/.nycrc.json
- server/jasmine.json
- server/package.json
- server/yarn.lock
> refactor: Use nyc to check types

- src/style/content/preferences/av.less
This fixes https://github.com/wireapp/wire-webapp/issues/5852.
> fix: Make dropdown readable in dark mode (WEBAPP-5933)

- src/script/links/LinkPreviewRepository.js
Connected to https://github.com/wireapp/wire-desktop/pull/2328.
> chore: Log OpenGraph fetching errors

- src/page/auth.html
- src/script/auth/AuthRepository.js
- src/script/auth/AuthService.js
- src/script/auth/Environment.ts
- src/script/auth/main.tsx
- src/script/auth/module/action/RuntimeAction.ts
- src/script/auth/page/ConversationJoin.tsx
- src/script/config/dependenciesGraph.js
- src/script/event/WebSocketService.js
- src/script/main/app.js
- src/script/main/auth.js
- src/script/main/globals.js
- src/script/main/login.js
- src/script/service/BackendClient.js
- src/script/storage/StorageService.js
- src/script/util/LoggerUtil.js
- src/script/view_model/AuthViewModel.js
- test/api/TestFactory.js
Reverts wireapp/wire-webapp#6083
> Revert "refactor: Read env config from the most recent config spec"

- src/script/main/app.js
- src/script/view_model/ListViewModel.js
- src/script/view_model/MainViewModel.js
- src/script/view_model/PanelViewModel.js
- src/script/view_model/content/ConnectRequestsViewModel.js
- src/script/view_model/list/ArchiveViewModel.js
- src/script/view_model/list/ConversationListViewModel.js
- src/script/view_model/list/StartUIViewModel.js
- src/script/view_model/list/TakeoverViewModel.js
- src/script/view_model/list/TemporaryGuestViewModel.js
This will allow those variables to be garbage collected and help reading/refactoring the code in the future
> refactor: Limit scope of variables in root components of the app

- src/script/media/MediaConstraintsHandler.js
- src/script/media/MediaDevicesHandler.js
- src/script/media/MediaStreamHandler.js
- src/script/util/Environment.js
- src/script/view_model/VideoCallingViewModel.js
> feat: Enable screensharing in Chrome v72+ (WEBAPP-6083)

- src/script/components/list/conversationListCallingCell.js
Only clicking the avatar or conversation name in the call UI is supposed to switch the conversation.
> fix: Don't switch the conversation when interacting with the call (WEBAPP-6092)

- src/script/auth/component/AccountForm.tsx
Effectively we allowed spaces in password as long as the password reaches the required length without spaces.
> fix: Do not trim passwords on registration (WEBAPP-6123)

- package.json
- src/page/login.html
- src/script/components/deviceRemove.js
- src/script/view_model/AuthViewModel.js
- src/style/auth/base.less
- yarn.lock
https://github.com/wireapp/wire-web-config-default/pull/34
> feat: Add password policy when login with phone number (WEBAPP-6122)

- src/script/main/app.js
- src/script/user/UserRepository.js
- src/script/view_model/MainViewModel.js
- src/script/view_model/ModalsViewModel.js
This PR also changes the warning modal implementation a little bit. It now has a queue and relies on a singleton.
> feat: Show info modal on availability change

- src/script/view_model/AuthViewModel.js
> fix: Wrong error message on phone login with password (WEBAPP-6131)

- src/script/components/participantAvatar.js
> runfix: Don't report unavailable assets to Raygun (WEBAPP-6133)

- src/script/calling/CallingRepository.js
This is the proper fix that should have been done here https://github.com/wireapp/wire-webapp/pull/6387
> runfix: Remove duplicate error message (WEBAPP-6108)

- README.md
> docs: Add staging bump documentation

- src/script/main/app.js
- src/script/user/AvailabilityModal.js
- src/script/user/UserRepository.js
This will implement the availability modals in such a way that:
1. They only show once on app start if they have never been shown before and the status is set to anything else then NONE
2. if the status is changed on the local device and hasn't been marked as 'never show again' before
> runfix: Implement proper Modal behaviour

- src/page/template/content/collection-details.htm
> feat: Display videos in collection details

- src/page/template/content/preferences-account.htm
This enables SCIM-Users to change their avatar.
> feat: Enable avatar upload for all users

- src/script/auth/page/SingleSignOnForm.tsx
Related: https://github.com/wireapp/wire-webapp/pull/6480
> chore: Print SSO errors to console

- app-config/package.json
- server/ServerConfig.ts
- server/config.ts
- src/script/auth/component/AcceptNewsModal.tsx
- src/script/auth/component/AppAlreadyOpen.tsx
- src/script/auth/component/UnsupportedBrowser.tsx
- src/script/auth/config.ts
- src/script/auth/page/ClientManager.tsx
- src/script/auth/page/ConversationJoin.tsx
- src/script/auth/page/ConversationJoinInvalid.tsx
- src/script/auth/page/HistoryInfo.tsx
- src/script/strings.ts
> chore: Add BRAND_NAME to react part

- src/script/auth/component/AccountForm.tsx
- src/script/auth/page/HistoryInfo.tsx
- src/script/auth/page/SingleSignOnForm.tsx
- tslint.json
This one got embezzled in [#6432](https://github.com/wireapp/wire-webapp/pull/6432/files#diff-ace19bd0c04529e685320269e3c05de9L8).
> chore: Remove console output

- src/script/auth/config.ts
- src/script/auth/configureEnvironment.ts
- src/script/auth/page/Login.tsx
- src/script/global.d.ts
In some places we have more fine grained `global` definitions than in other places. That's why I would like to collect them in a dedicated file.
> refactor: Share global definitions

- src/script/broadcast/BroadcastRepository.js
- src/script/user/UserRepository.js
Reverts wireapp/wire-webapp#6667
> Revert "feat: Don't broadcast availability to LH clients"

- src/script/auth/page/ChooseHandle.tsx
- src/script/auth/page/ClientManager.tsx
- src/script/auth/page/ConversationJoinInvalid.tsx
- src/script/auth/page/CreatePersonalAccount.tsx
- src/script/auth/page/HistoryInfo.tsx
- src/script/auth/page/Index.tsx
- src/script/auth/page/InitialInvite.tsx
- src/script/auth/page/Login.tsx
- src/script/auth/page/Root.tsx
- src/script/auth/page/TeamName.tsx
- src/script/auth/page/Verify.tsx
> chore: isAuthenticatedCheck to more private endpoints

- babel.config.js
- package.json
- src/script/main/app.js
- webpack.config.common.js
- yarn.lock
First attempt with the DebugUtil
> chore: Enable lazy loading of bundles

- src/script/event/preprocessor/ReceiptsMiddleware.js
- test/unit_tests/cryptography/CryptographyMapperSpec.js
> runfix: Don't override legal hold state for outgoing messages

- .env.localhost
> test: Enable debugging by default on localhost

- src/script/util/Environment.js
Fixes crash on startup when media devices are disabled.
> Check media devices support before calling them

- src/script/main/app.js
Reverts wireapp/wire-webapp#7120
> runfix: Revert check for transient client on connectivity error

- karma.conf.js
- src/script/auth/page/Login.tsx
- src/script/util/valueStore.test.ts
- src/script/util/valueStore.ts
- src/worker/sw-value-store.js
This will allow passing values from the login page to the rest of the app without any writings on the disk
> feat: Add the single value store 

- README.md
> docs: How to automatically generate release notes

- src/script/auth/module/action/RuntimeAction.ts
Increasing the connection timeout from 500ms to 5s (The request can take up to 3s on my computer)
Using events to resolve the promise
> fix: Improve private mode detection for Firefox

- src/script/conversation/ConversationRepository.js
- src/script/event/EventRepository.js
- test/unit_tests/event/EventRepositorySpec.js
> test: Check return values of notification stream interactions

- package.json
- src/script/event/EventRepository.js
- src/script/event/EventSource.ts
- src/script/event/EventValidation.ts
- src/script/event/EventValidator.test.ts
- src/script/event/EventValidator.ts
- src/script/user/UserRepository.ts
- test/unit_tests/event/EventRepositorySpec.js
- yarn.lock
**Previously**
1. Event validation is part of the gigantic `EventRepository.js`
1. Event validation throws custom errors or returns the event on validation success
1. Logging is done inside of the validator
1. Custom errors have been analyzed to decide if the application shall proceed or bubble up the error. All custom erros thrown by the validation will tell the application to proceed.
**Now (this PR)**
1. Event validation is outsourced to `EventValidator.ts`
1. Well-defined enumerations will be used instead of throwing custom errors. There is no need to return the original event as it won't be changed during the validation process and the caller has already access to the event.
1. The validator only validates. Logging is done outside of the validator based on the validation result.
1. …
> refactor: Reimplement event validation

- src/script/event/EventRepository.js
- src/script/event/EventValidator.test.ts
- src/script/event/EventValidator.ts
> runfix: Always process OTR messages

- src/script/conversation/ConversationRepository.js
- src/script/event/preprocessor/ReceiptsMiddleware.js
> runfix: Check if conversation exists (WEBAPP-6424)

- README.md
> docs: Describe changelog generation semi-automatic

- src/style/components/list/participant-item.less
> fix: Truncate service descriptions which are too long (WEBAPP-6440)

- src/style/list/conversations.less
> fix: Do not allow user select for in conversations

- src/script/view_model/list/StartUIViewModel.js
> fix: Don't create multiple 1on1 conversations in slow connections

- src/script/broadcast/BroadcastService.ts
- src/script/config/dependenciesGraph.js
- src/script/main/app.js
> refactor: Migrate 'BroadcastService' to TypeScript

- src/script/config/dependenciesGraph.js
- src/script/conversation/ConversationLabelRepository.ts
- src/script/properties/PropertiesService.ts
- test/unit_tests/properties/PropertiesRepositorySpec.js
> refactor: Migrate PropertiesService to TypeScript

- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- src/script/self/SelfService.ts
- src/script/view_model/AuthViewModel.js
- test/api/TestFactory.js
- test/unit_tests/self/SelfServiceSpec.js
> refactor: Migrate SelfService to TypeScript

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#7437
> Revert "chore(deps): bump phoneformat.js from 1.0.8 to 1.0.9"

- test/unit_tests/components/asset/controls/mediaButtonSpec.js
> test: Use context in media button spec

- src/script/config/dependenciesGraph.js
- src/script/links/LinkPreviewRepository.js
- test/api/TestFactory.js
- test/unit_tests/links/LinkPreviewRepositorySpec.js
Reverts wireapp/wire-webapp#7512
> Revert "refactor: Remove LinkPreviewRepository from dependencies"

- src/script/client/ClientRepository.js
This was introduced in [#6499](https://github.com/wireapp/wire-webapp/pull/6499/files#diff-46c8541c11d5dbe2a9b5ab0d76b3ab02L406).
> fix: Store cookie in ClientRepository

- src/script/audio/AudioRepository.ts
- src/script/auth/page/ClientManager.tsx
> refactor: Convert AudioRepository to TypeScript

- src/script/client/ClientEntity.ts
- src/script/client/ClientMapper.ts
- src/script/client/ClientRepository.ts
- src/script/client/ClientService.ts
- src/script/event/EventRepository.js
- src/script/user/UserRepository.ts
- test/unit_tests/client/ClientMapperSpec.js
- test/unit_tests/client/ClientRepositorySpec.js
- test/unit_tests/user/UserRepositorySpec.js
Best viewed [without whitespace changes](https://github.com/wireapp/wire-webapp/pull/7521/files?w=1).
> refactor: Convert 'client' to TypeScript

- src/script/audio/AudioPlayingType.ts
> refactor: Migrate AudioPlayingType to TypeScript

- src/script/audio/AudioRepository.ts
- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- src/script/view_model/AuthViewModel.js
- test/unit_tests/audio/AudioRepositorySpec.js
> refactor: Remove AudioRepository from dependencies

- src/script/components/copyToClipboard.ts
- src/script/main/globals.js
> refactor: Migrate CopyToClipboard to TypeScript

- src/script/config/dependenciesGraph.js
> refactor: Remove SelfService from dependencies

- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- src/script/view_model/AuthViewModel.js
- test/api/TestFactory.js
- test/api/testResolver.js
- test/unit_tests/user/UserServiceSpec.js
> refactor: Remove UserService from dependencies

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#7589
> chore: Revert "Update AVS to 5.3.14"

- src/script/config/dependenciesGraph.js
- src/script/extension/GiphyRepository.ts
- test/unit_tests/extension/GiphyRepositorySpec.js
> refactor: Remove Giphy* from dependenciesGraph

- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- test/api/TestFactory.js
- test/unit_tests/media/MediaStreamHandlerSpec.js
> refactor: Remove MediaRepository from dependenciesGraph

- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- test/api/TestFactory.js
- test/unit_tests/media/MediaStreamHandlerSpec.js
> refactor: Remove PermissionRepository from dependenciesGraph

- src/script/components/asset/AbstractAssetTransferStateTracker.js
- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- src/script/view_model/content/InputBarViewModel.js
- test/unit_tests/assets/AssetUploaderSpec.js
> refactor: Remove AssetUploader from dependenciesGraph

- src/script/components/asset/AbstractAssetTransferStateTracker.js
- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- src/script/view_model/content/InputBarViewModel.js
- test/api/TestFactory.js
- test/unit_tests/assets/AssetUploaderSpec.js
> refactor: Remove AssetService from dependenciesGraph

- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- test/unit_tests/extension/GiphyRepositorySpec.js
> refactor: Remove GiphyRepository from dependenciesGraph

- src/script/auth/AuthRepository.ts
- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- src/script/view_model/AuthViewModel.js
- test/api/TestFactory.js
> refactor: Remove Auth* from dependenciesGraph

- src/script/config/dependenciesGraph.js
- src/script/main/app.js
- test/unit_tests/extension/GiphyRepositorySpec.js
> refactor: Remove GiphyService from dependenciesGraph

- server/package.json
- server/yarn.lock
Reverts wireapp/wire-webapp#7719
> chore(deps): Revert "bump geolite2 from 1.3.0 to 2.0.0 in /server"

- src/script/auth/component/AcceptNewsModal.tsx
- src/script/auth/component/WirelessContainer.tsx
- src/script/auth/page/TeamName.tsx
- src/script/externalRoute.js
> feat: Include locale to the website URLs

- src/script/auth/component/AccountForm.tsx
> feat: Add locale to Terms during creation of the accounts

- src/script/main/app.js
> fix: Use AssetService variable in the App

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#7798
> Revert "chore(deps): bump @wireapp/avs from 5.1.40 to 5.3.44"

- src/script/conversation/ConversationMapper.js
- src/script/conversation/ConversationRepository.js
- src/script/conversation/ConversationRole.ts
- src/script/entity/Conversation.js
> feat: Add roles to conversation entity

- src/script/main/app.js
> runfix: Don't throw error on logout with permanent device

- src/script/storage/StorageService.ts
> runfix: Read records with error correction

- bin/push_docker.js
- server/bin/create_commit_sha_file.js
Follow-up to https://github.com/wireapp/wire-webapp/pull/7987.
This fixes https://github.com/wireapp/wire-webapp/issues/7985 (again).
> chore: Run scripts without git

- src/page/auth.html
- src/page/index.html
> fix: Render templates with relative urls

- .travis.yml
> chore: Test deployment on AWS S3

- package.json
- src/script/storage/StorageService.ts
- yarn.lock
This uses the fixed JSON mapping, see https://github.com/wireapp/wire-web-packages/pull/2913.
> fix: Use JSON mapping from SQLeet (WEBAPP-6765)

- src/page/auth.html
- src/page/index.html
- src/page/template/graph.htm
- src/page/template/meta.htm
> chore: Add whitespace to the metadata sites

- src/script/broadcast/BroadcastRepository.ts
- src/script/conversation/ClientMismatchHandler.ts
This partly reverts https://github.com/wireapp/wire-webapp/pull/8574.
> feat: Request only receiver's missing clients for broadcast

- bin/release_tag.ts
For some reason we were searching GIFs and not using random GIFs when releasing :thinking:
> chore: Send a random GIF to the chat when releasing

- server/package.json
- server/yarn.lock
Reverts wireapp/wire-webapp#8813
> Revert "chore(deps-dev): bump @types/fs-extra from 8.1.0 to 9.0.0 in /server"

- src/page/template/content/preferences-options.htm
- src/script/components/list/conversationListCallingCell.ts
- src/style/components/list/conversation-list-calling-cell.less
> runfix: Adjust constant bit rate ui

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#8985
> Revert "chore(deps): bump @wireapp/core from 16.9.15 to 16.10.1"

- src/script/components/groupVideoGrid.ts
- src/script/components/list/conversationListCallingCell.ts
- src/script/components/list/participantItem.ts
- src/style/components/list/participant-item.less
> feat: Show screen share icon in the participant item and grid view

- src/script/components/list/participantItem.ts
> fix: Update the icon order in participant item

- app-config/package.json
- src/script/components/list/participantItem.ts
> style: Update icons for mute/unmute in participant item

- src/style/content/conversation/message-list.less
> fix: Remove extra space under the image when uploading it

- src/i18n/en-US.json
- src/script/view_model/ActionsViewModel.js
> feat: Offer the option clear content when leaving conversation

- src/script/view_model/CallingViewModel.ts
> fix: Remove alert and use call function

- src/script/view_model/CallingViewModel.ts
> fix: Don't accept calls when the browser is not supported

- src/script/components/message.ts
> runfix: Don't show empty context menu during file upload (WEBAPP-6970)

- src/page/template/list/conversations.htm
- src/page/template/list/temporary-guest.htm
- src/script/components/list/conversationListCallingCell.ts
- src/script/view_model/CallingViewModel.ts
- src/script/view_model/ListViewModel.ts
- src/script/view_model/MainViewModel.js
- src/script/view_model/list/ConversationListViewModel.ts
- src/script/view_model/list/TemporaryGuestViewModel.ts
- src/style/components/list/participant-item.less
- test/unit_tests/components/list/conversationListCallingCellSpec.js
> fix: Correctly pass external role to call UI and remove video icon animation (WEBAPP-6931, WEBAPP-6937)

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#9388
> Revert "chore(deps-dev): Bump babel-plugin-react-intl from 7.9.2 to 8.0.0"

- src/script/auth/component/ClientItem.tsx
> runfix: Selected Input border for too many devices delete selection

- src/script/util/messageRenderer.ts
- src/style/content/conversation/message-list.less
> feat: Support ordered and unordered lists when rendering messages

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#9419
> runfix: Use uppercase error messages

- src/script/extension/GiphyRepository.ts
- src/script/view_model/content/GiphyViewModel.ts
This closes https://github.com/wireapp/wire-webapp/issues/5571.
> feat: Don't randomize Giphy search results

- src/page/template/modal/group-creation.htm
- src/script/components/userList.ts
This fixes https://github.com/wireapp/wire-webapp/issues/9344.
> fix: Don't suggest unconnected users when creating a group with private account (WEBAPP-7059)

- src/script/util/messageRenderer.ts
> feat: Enable escaping in Markdown renderer

- src/script/calling/CallingRepository.ts
- src/script/view_model/CallingViewModel.ts
Reverts wireapp/wire-webapp#9476
> Revert "fix: Ask for screen media before changing video state to screen sharing (WEBAPP-7061)"

- server/tsconfig.json
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46917
> chore: Enable esnext for /server

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#9495
> Revert "chore(deps-dev): Bump babel-plugin-react-intl from 7.9.2 to 8.1.8"

- Gruntfile.js
https://wearezeta.atlassian.net/browse/WEBAPP-7081
> chore: Change the format of the version to match the rest

- tsconfig.json
> runfix: Use Node.js 13 compatible imports to execute release scripts

- src/script/conversation/ConversationRepository.ts
> runfix: Use audio-video instead of file for contributed event action type

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#9590
> Revert "chore(deps): Bump @wireapp/avs from 6.2.30 to 6.3.1"

- src/script/util/Environment.ts
Follow-up to https://github.com/wireapp/wire-webapp/pull/9553.
> runfix: Set correct environment version (WEBAPP-7081)

- src/script/cryptography/CryptographyRepository.ts
Reverts wireapp/wire-webapp#9792
> refactor: Revert "CryptographyRepository - Stronger encapsulation"

- src/script/components/panel/userActions.ts
- src/script/connection/ConnectionRepository.ts
- src/script/conversation/ConversationRepository.ts
- src/script/entity/Conversation.ts
- src/script/view_model/ActionsViewModel.ts
- src/script/view_model/content/MessageListViewModel.ts
- src/script/view_model/content/UserModalViewModel.ts
Preparation to fix https://wearezeta.atlassian.net/browse/SQCORE-39
> refactor: Add user action typings

- src/script/connection/ConnectionRepository.ts
- src/script/user/UserRepository.ts
Reverts wireapp/wire-webapp#10013
> Revert "runfix: Don't duplicate connection requests"

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#10071
> Revert bump @wireapp/react-ui-kit

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#10010
> Revert emotion/babel-preset-css-prop update

- src/script/components/groupList.ts
- src/style/components/group-list.less
- src/style/foundation/main.less
- src/style/list/start-ui.less
Reverts wireapp/wire-webapp#10136
> Revert "refactor: Omit unsed group-list knockout component"

- src/script/components/ButtonGroup.test.tsx
- src/script/components/ButtonGroup.tsx
- src/script/components/calling/FullscreenVideoCall.tsx
> feat: Add ButtonGroup react component

- package.json
- src/script/broadcast/BroadcastRepository.ts
- src/script/broadcast/BroadcastService.ts
- src/script/conversation/ClientMismatchHandler.ts
- src/script/conversation/ConversationService.ts
- src/script/conversation/MessageRepository.ts
- src/script/cryptography/CryptographyRepository.ts
- test/unit_tests/cryptography/CryptographyRepositorySpec.js
- yarn.lock
This reverts commit aa7dc6de3f577322639c1d7ce332286c434ee7f2.
> chore: Revert "refactor: Use @wireapp/core 17.0 (#10371)"

- src/page/template/content/preferences-account.htm
- src/script/user/UserRepository.ts
- src/script/view_model/content/PreferencesAccountViewModel.ts
- test/unit_tests/user/UserRepositorySpec.js
Mobile clients allow up to 256 characters for the user handle so we should allow that same number.
> fix: Increase user handle limit to 256

- src/script/event/EventRepository.ts
- src/script/event/EventValidator.test.ts
- src/script/event/EventValidator.ts
Duplicated events will be handled directly by cryptobox with this PR.
> refactor: Simplify event validation (SQCORE-270)

- server/package.json
- server/yarn.lock
Reverts wireapp/wire-webapp#10714
> Revert "chore: bump @types/fs-extra from 9.0.7 to 9.0.8 in /server"

- src/script/event/EventRepository.ts
- src/script/event/EventValidator.test.ts
- src/script/event/EventValidator.ts
Reverts wireapp/wire-webapp#10653
> Revert "refactor: Simplify event validation (SQCORE-270)"

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#10787
> Revert "chore(deps-dev): bump ts-jest from 26.5.2 to 26.5.4"

- src/page/template/content/preferences-account.htm
- src/script/user/UserRepository.ts
- src/script/view_model/content/PreferencesAccountViewModel.ts
New backend limits make it possible: https://github.com/wireapp/wire-server/blob/73b47fce0d53a56b81cf17b7c4e60d0f9f0c80ed/libs/wire-api/src/Wire/API/User/Profile.hs#L83-L85
> feat: Allow display names up to 128 characters

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#11021
> Revert "chore: Bump @wireapp/avs from 7.1.4 to 7.1.5"

- package.json
- yarn.lock
Reverts wireapp/wire-webapp#11024
> Bump @wireapp/avs to 7.1.5

- server/ServerConfig.ts
- server/config.ts
- src/script/main/globals.ts
- src/script/media/MediaEmbeds.test.ts
- src/script/media/MediaParser.ts
Requires config version `>=0.28.19`
> feat: Add client feature flag for rendering media embeds (SQSERVICES-620)

- src/i18n/en-US.json
- src/script/components/asset/RestrictedAudio.tsx
- src/script/components/asset/audioAsset.ts
- src/script/components/message.ts
- src/style/components/asset/audio-asset.less
> feat: Prevent receiving audio messages based on feature config (SQSERVICES-614)

- src/i18n/en-US.json
- src/script/view_model/content/InputBarViewModel.ts
> feat: Show info modal when sending file via drag & drop or clipboard when feature is disabled (SQSERVICES-614)

- src/i18n/en-US.json
- src/page/template/content/conversation/input-bar.htm
- src/script/components/Image.tsx
- src/script/components/asset/FileAssetComponent.tsx
- src/script/components/asset/RestrictedImage.tsx
- src/script/components/asset/imageAsset.ts
- src/script/components/message.ts
- src/script/components/message/messageQuote.ts
- src/style/components/image.less
- src/style/content/conversation/message-quote.less
> runfix: Handle restricted image quotes (SQSERVICES-614)

- src/script/components/asset/RestrictedVideo.tsx
- src/script/components/asset/VideoAsset.tsx
- src/script/components/message.ts
- src/style/components/asset/video-asset.less
- src/style/components/image.less
- src/style/content/conversation/message-quote.less
> feat: Placeholder for restricted video assets (SQSERVICES-677)

- src/page/template/content/conversation/input-bar.htm
- src/script/components/asset/RestrictedVideo.tsx
- src/style/components/asset/video-asset.less
- src/style/content/conversation/input-bar.less
> feat(services): Input bar reply video thumbnail

- src/script/components/asset/FileAssetComponent.test.tsx
- src/script/components/asset/FileAssetComponent.tsx
- src/script/util/util.ts
- test/unit_tests/util/UtilSpec.js
> fix(services): File asset size information (SQSERVICES-678)

- src/script/components/calling/CallingOverlayContainer.tsx
- src/script/components/list/ConversationListCallingCell.tsx
- src/script/components/list/ConversationListCell.tsx
> fix(core): Don't display array length 0 in container

- src/script/connection/ConnectionRepository.ts
- src/script/conversation/ConversationRepository.ts
- src/script/main/app.ts
- src/script/notification/NotificationRepository.ts
- src/script/view_model/ActionsViewModel.ts
- src/script/view_model/ContentViewModel.ts
- src/script/view_model/ImageDetailViewViewModel.ts
- src/script/view_model/ListViewModel.ts
- src/script/view_model/content/GroupCreationViewModel.ts
- src/script/view_model/list/ArchiveViewModel.ts
- src/script/view_model/list/StartUIViewModel.ts
- src/script/view_model/list/TakeoverViewModel.ts
Reverts wireapp/wire-webapp#11619
> Revert "runfix: Give options param default value (SQCALL-376)"

- src/script/components/message.ts
- src/script/components/message/MessageFooterLike.test.tsx
- src/script/components/message/MessageFooterLike.tsx
- src/script/components/message/MessageLike.tsx
> refactor: Migrate message likes to React

- src/script/conversation/ConversationMapper.ts
- src/script/conversation/ConversationRepository.ts
- src/script/conversation/EventBuilder.ts
- src/script/conversation/EventMapper.ts
- src/script/cryptography/CryptographyMapper.ts
- src/script/entity/Conversation.ts
- src/script/entity/message/MemberMessage.ts
- src/script/storage/record/ConversationRecord.ts
- src/script/user/UserRepository.ts
- src/script/user/UserService.ts
Reverts wireapp/wire-webapp#11624
> Revert "feat: Display qualified users in federated conversation"

- src/script/auth/SignOutReason.ts
- src/script/auth/route.ts
- src/script/error/TeamError.ts
- src/script/main/app.ts
- src/script/strings.ts
- src/script/team/TeamRepository.ts
- src/script/team/TeamService.ts
> runfix: Redirect to login when app config can not be loaded (SQSERVICES-710)

- src/script/conversation/ConversationRepository.ts
- test/unit_tests/conversation/ConversationRepositorySpec.js
Reverts wireapp/wire-webapp#11741
> Revert "feature(core): Map domain from conversation creation event"

- .github/workflows/check-pr-title.yml
See: https://github.com/thehanimo/pr-title-checker/issues/4#issuecomment-917225376
> chore: Don't fail PR title check with Dependabot
