wireapp/wire-webapp

- .gitignore
- aws/templates/aws/base_error.html
- aws/templates/aws/debug.html
- aws/templates/aws/error.html
The root folder is ignored by default and we missed those :)
> Added missing templates

- app/page/template/video-calling.htm
- app/script/calling/CallCenter.coffee
- app/script/calling/entities/Flow.coffee
- app/script/localization/strings-de.coffee
- app/script/telemetry/calling/FlowTelemetry.coffee
- app/style/components/calling/device-toggle-button.less
- app/style/video-calling.less
- automation testing fix
- device toggle button color on white background
- modal translations
- enable on prod
> Screen sharing tweaks

- app/script/calling/handler/CallStateHandler.coffee
- app/script/conversation/ConversationRepository.coffee
- test/unit_tests/conversation/ConversationRepositorySpec.coffee
Resolves https://wearezeta.atlassian.net/browse/WEBAPP-2947
> Separate actions with bots in media tracking 

- app/style/components/asset/link-preview-asset.less
> lower link preview title top margin

- app/page/template/video-calling.htm
- app/script/view_model/VideoCallingViewModel.coffee
This is a pretty common feature in most video chat applications.
Screenshots: http://imgur.com/a/CEEUO
> remote video: double click to switch video between contain and cover view

- app/page/template/video-calling.htm
- app/script/view_model/VideoCallingViewModel.coffee
- app/style/video-calling.less
- we only have handler for the object-fit of the remote video element
- fixed portrait videos from mobile showing in proper mode before user interaction
> Handle object-fit of remote video

- app/page/template/_dist/app.htm
- app/page/template/partials/template-message.htm
- app/script/components/contextMenu.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/entity/message/ContentMessage.coffee
- app/script/entity/message/Message.coffee
- app/script/event/WebApp.coffee
- app/script/localization/strings.coffee
- app/script/view_model/MessageListViewModel.coffee
- app/style/common/bubble.less
- app/style/components/context-menu.less
- app/style/conversation/message-list.less
- app/style/main.less
This adds the new message context menu to the UI. 
The basic idea is that the context menu emits a custom event once its clicked and the data is updated. This way you can listen to the custom event and stop the propagation to e.g. display a different element with the data.
> message context menu (WEBAPP-2861)

- app/script/main/app.coffee
- app/script/storage/StorageRepository.coffee
- app/script/storage/StorageService.coffee
To track down https://wearezeta.atlassian.net/browse/WEBAPP-3141 (DatabaseClosedError happened unexpectedly) I want to log the reason why we close the database.
> Showing reason why we close the database

- app/page/template/partials/template-message.htm
- app/style/common/like.less
- app/style/common/mixins.less
- app/style/conversation/message-list.less
- app/style/main.less
> Like animation

- trans.py
https://www.python.org/dev/peps/pep-0008/#imports
(Even though I also prefer the `from subprocess import Popen, PIPE` to be on separate lines)
> Imports on separate lines

- .travis.yml
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
> Use latest stable node

- app/script/util/Environment.coffee
- aws/config.py
Blocking very outdated browser versions
> Bump required browser versions

- app/script/localization/strings-de.coffee
- app/script/localization/strings.coffee
- app/script/system_notification/SystemNotificationRepository.coffee
> Add notification for shared location (WEBAPP-3223)

- app/script/calling/handler/CallStateHandler.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/tracking/SessionEventName.coffee
- remove duplicate session event counters
- unify `media.completed_media_action` event sending
> 'media.completed_media_action' on text message (WEBAPP-3227, WEBAPP-3233)

- app/script/auth/AuthRepository.coffee
- app/script/calling/handler/CallStateHandler.coffee
- app/script/entity/message/DecryptErrorMessage.coffee
> Less curly brackets

- app/script/system_notification/SystemNotificationRepository.coffee
The MD5 of the generated JS is the same as before :)
> Removed curly brackets from SystemNotificationRepository

- app/page/template/content/preferences-device-details.htm
> Add data-uie-names for device details

- app/script/client/ClientService.coffee
- app/script/entity/Conversation.coffee
There is no need to wrap all these promises
> [RFC] clean up client service

- app/demo/template/avatars.htm
- app/page/template/content/connect-requests.htm
- app/page/template/content/preferences-account.htm
- app/page/template/partials/template-message.htm
- app/page/template/partials/template-user-profile.htm
- app/script/components/groupList.coffee
- app/script/components/userProfile.coffee
- app/style/common/common.less
- app/style/common/variables.less
- app/style/components/user-avatar.less
- app/style/components/user-profile.less
- app/style/content/connect-requests.less
In order to support v3 profile images, i used user-avatar component in all places where the preview url was used. This makes it easier to switch later and fixes WEBAPP-1936 as well. Needed to introduce a new user-avatar size to cover all cases.
> use user-avatar component where possible

- app/page/template/partials/template-message.htm
- app/script/util/Emoji.coffee
- test/unit_tests/util/EmojiSpec.coffee
I also  aligned naming with String.includes()
> Ignore whitespaces in emoji only string check (WEBAPP-3274)

- app/script/conversation/ConversationRepository.coffee
- app/script/system_notification/SystemNotificationRepository.coffee
- test/unit_tests/conversation/ConversationRepositorySpec.coffee
Let's be more error resistant. Switching conversations, clear the message content and we thus might not find the message anymore.
> Use Promise to get message

- app/script/system_notification/SystemNotificationRepository.coffee
- test/unit_tests/system_notification/SystemNotificationRepositorySpec.coffee
> Notification usability improvements (WEBAPP-2944, WEBAPP-2945)

- app/script/util/util.coffee
- test/unit_tests/util/UtilSpec.coffee
Merge only after comment on ticket from @shumengye
> Improve file size bucketing (WEBAPP-2980)

- app/script/storage/StorageService.coffee
https://github.com/dfahlander/Dexie.js/wiki/Deprecations
> Remove deprecated error handler

- app/script/components/userProfile.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/event/WebApp.coffee
- app/script/main/app.coffee
- app/script/user/UserRepository.coffee
- app/script/view_model/ParticipantsViewModel.coffee
- app/script/view_model/list/StartUIViewModel.coffee
- test/unit_tests/conversation/ConversationRepositorySpec.coffee
> Connection cleanup (WEBAPP-3380)

- .github/PULL_REQUEST_TEMPLATE.md
Removed check boxes for "Type of change" because if you only tick 1, then it looks like you fulfilled 1/3 objectives which gives a wrong impression.
> Simplified Pull Request Template

- app/script/conversation/ConversationRepository.coffee
> Conversation loading fails with when paging (WEBAPP-3385)

- app/script/conversation/ConversationService.coffee
- test/unit_tests/conversation/ConversationServiceSpec.coffee
Turning timestamps into ISO strings.
> Fix for invalid key

- app/page/auth.html
- app/page/template/content/conversation/participants.htm
- app/script/components/userInput.coffee
Related: https://github.com/wireapp/wire-desktop/pull/207
> Disabling spellcheck whenever is not needed

- app/page/index.html
- app/page/template/partials/template-user-profile.htm
- app/page/template/prevent-onbeforeunload.htm
- app/script/util/util.coffee
- test/unit_tests/util/UtilSpec.coffee
Preventing "onbeforeunload" on "mailto" links.
> Preventing "onbeforeunload" on "mailto" links

- app/script/calling/entities/FlowAudio.coffee
> Ensure MediaType information on wrapped MediaStreams

- app/script/conversation/ConversationRepository.coffee
Does not fix the underlying database update race condition problem the sequential update check was intended to solve. But we will no longer end up in a loop. Investigating to improve the solution.
> Prevent infinite reaction update loop

- app/script/tracking/EventTrackingRepository.coffee
> Disable error tracking of Raygun on detach (WEBAPP-3354)

- app/script/conversation/ConversationService.coffee
> Additional logging for database queries

- app/script/auth/AuthService.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/conversation/ConversationService.coffee
- app/script/entity/Conversation.coffee
- app/script/service/Client.coffee
- app/script/user/UserService.coffee
- app/script/util/util.coffee
- app/style/components/user-profile.less
- test/unit_tests/conversation/ConversationMapperSpec.coffee
- test/unit_tests/conversation/ConversationServiceSpec.coffee
- test/unit_tests/entity/ConversationSpec.coffee
> staging bump 2016-11-29

- app/script/util/util.coffee
> Tooltip of ephemeral timer not only shows seconds (WEBAPP-3408)

- app/script/main/app.coffee
- app/script/system_notification/SystemNotificationRepository.coffee
- test/api/TestFactory.js
- test/unit_tests/system_notification/SystemNotificationRepositorySpec.coffee
> Properly hide notifications while in active conversation (WEBAPP-3409)

- app/script/view_model/content/PreferencesAVViewModel.coffee
> Not everything is a permission issue when MediaStreams fails

- .travis.yml
https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
> remove yarn installation

- app/script/conversation/ConversationMapper.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/conversation/ConversationService.coffee
- app/script/conversation/ConversationUpdateType.coffee
- app/script/entity/Conversation.coffee
- app/script/event/WebApp.coffee
- test/unit_tests/conversation/ConversationServiceSpec.coffee
> Persist ephemeral timer selected for conversation (WEBAPP-3304)

- bower.json
Added a slightly faster cryptobox which uses a faster curve conversion.
> Updated cryptobox

- app/page/template/content/conversation/message-list.htm
- app/script/components/userAvatar.coffee
- app/script/util/ArrayUtil.coffee
- app/script/view_model/MessageListViewModel.coffee
- app/script/view_model/bindings/CommonBindings.coffee
- app/script/view_model/bindings/MessageListBindings.coffee
> Introduce in_viewport binding

- app/page/template/_dist/app.htm
- app/page/template/video-calling.htm
- app/script/calling/CallCenter.coffee
- app/script/calling/CallError.coffee
- app/script/calling/entities/Call.coffee
- app/script/calling/entities/Flow.coffee
- app/script/calling/enum/CallState.coffee
- app/script/calling/handler/CallStateHandler.coffee
- app/script/components/calling/deviceToggleButton.coffee
- app/script/main/app.coffee
- app/script/media/MediaDeviceType.coffee
- app/script/media/MediaDevicesHandler.coffee
- app/script/media/MediaElementHandler.coffee
- app/script/media/MediaError.coffee
- app/script/media/MediaRepository.coffee
- app/script/media/MediaStreamHandler.coffee
- app/script/media/MediaStreamInfo.coffee
- app/script/media/MediaStreamSource.coffee
- app/script/media/MediaType.coffee
- app/script/telemetry/calling/AudioStreamStats.coffee
- app/script/telemetry/calling/FlowTelemetry.coffee
- app/script/util/Environment.coffee
- app/script/view_model/ConversationTitlebarViewModel.coffee
- app/script/view_model/VideoCallingViewModel.coffee
- app/script/view_model/content/ContentViewModel.coffee
- app/script/view_model/content/PreferencesAVViewModel.coffee
- test/api/TestFactory.js
- test/unit_tests/media_devices/MediaStreamHandlerSpec.coffee
> Decoupling media handling from calling

- app/script/conversation/ConversationRepository.coffee
> ClientMismatch response sometimes contains clients of the self user (WEBAPP-3405, WEBAPP-3427)

- app/page/template/_dist/app.htm
- app/script/conversation/ConversationRepository.coffee
- app/script/storage/StorageRepository.coffee
- app/script/util/PromiseQueue.coffee
> Add Promise queue util and use for session deserialization

- app/script/client/Client.coffee
- app/script/client/ClientRepository.coffee
- app/script/client/ClientService.coffee
- test/unit_tests/client/ClientMapperSpec.coffee
- test/unit_tests/client/ClientSpec.coffee
Added default properties for client details in case that someone registers a client without these properties.
> Default properties for client details

- app/script/calling/entities/Call.coffee
> Stop call sound when aborting unaccepted call (WEBAPP-3442)

- app/script/client/Client.coffee
- app/script/client/ClientRepository.coffee
- app/script/storage/StorageRepository.coffee
- app/script/view_model/AuthViewModel.coffee
- test/api/TestFactory.js
- test/unit_tests/client/ClientMapperSpec.coffee
- test/unit_tests/client/ClientSpec.coffee
> Remove clients locally if non-existent on backend (WEBAPP-3435)

- app/script/storage/StorageRepository.coffee
- app/script/user/UserRepository.coffee
> staging bump 2016-12-13#2

- app/script/localization/strings-cs.coffee
- app/script/localization/strings-de.coffee
- app/script/localization/strings-es.coffee
- app/script/localization/strings-fi.coffee
- app/script/localization/strings-pt.coffee
- app/script/localization/strings-ru.coffee
- app/script/localization/strings-sl.coffee
- app/script/localization/strings.coffee
> staging bump 2016-12-13#3

- app/script/announce/AnnounceRepository.coffee
- app/script/auth/URLParameter.coffee
- app/script/main/app.coffee
- app/script/main/auth_init_dist.coffee
- app/script/main/auth_init_staging.coffee
- app/script/view_model/AuthViewModel.coffee
> Rename asset v3 URL parameter and streamline code

- app/script/assets/AssetRemoteData.coffee
- app/script/assets/AssetService.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/conversation/EventMapper.coffee
- app/script/main/app.coffee
- app/script/user/UserMapper.coffee
- app/sw.coffee
- aws/application.py
- grunt/config/copy.coffee
- grunt/config/watch.coffee
Cache assets remote data using service worker.
> 🖼 cache image assets

- app/script/media/MediaDevicesHandler.coffee
> Fix changing audio output from preferences (WEBAPP-3466)

- app/page/template/_dist/app.htm
- app/script/components/asset/controls/audioSeekBar.coffee
- app/script/components/asset/controls/seekBar.coffee
- app/script/components/asset/linkPreviewAsset.coffee
- app/script/components/contextMenu.coffee
- app/script/components/ephemeralTimer.coffee
- app/script/components/image.coffee
- app/style/components/asset/link-preview-asset.less
- app/style/components/image.less
- app/style/main.less
- coffeelint.json
- grunt/config/coffeelint.coffee
Outsource image logic into image component
> introduce image-component

- app/script/media/MediaElementHandler.coffee
MediaStreams that only contain video do not need an invisible AudioElement to output its the audio
> Improved MediaElement handling

- app/script/conversation/ConversationRepository.coffee
- app/script/view_model/GiphyViewModel.coffee
- app/script/view_model/ParticipantsViewModel.coffee
- app/script/view_model/list/ActionsViewModel.coffee
> Remove additional callback from ConversationRepository

- app/script/entity/Conversation.coffee
- test/unit_tests/entity/ConversationSpec.coffee
> Change 'Conversation.is_with_bot' to rely on handle/username (WEBAPP-3497)

- app/style/components/asset/controls/media-button.less
> Tweak upload progress bar

- app/page/auth.html
- app/script/view_model/AuthViewModel.coffee
- app/style/auth/account.less
Reverts wireapp/wire-webapp#631
> Revert "Enabled WebKit prefill (WEBAPP-3210)"

- app/page/template/detail-view.htm
Adds data-uie elements to picture detail view for testing
> Adds data-uie-elements for picture detail view

- app/page/template/_dist/app.htm
- app/script/localization/strings-da.coffee
- app/script/localization/strings-init.coffee
- trans.py
https://github.com/wireapp/wire-desktop/pull/325
> 🇩🇰 Added Danish 🇩🇰

- app/script/user/UserRepository.coffee
> Ensure we have the user before adding/removing client (WEBAPP-3499)

- app/page/template/_dist/app.htm
- app/page/template/content/collection-details.htm
- app/script/util/moment.coffee
- app/script/util/util.coffee
- app/script/view_model/content/CollectionDetailsViewModel.coffee
- app/style/content/collection.less
- test/unit_tests/util/MomentSpec.coffee
separate items in collection by date
> 🚧 collections #5

- app/page/template/partials/template-message.htm
Respecting ephemeral expired status for data-uie-visible attribute within images
> Respecting ephemeral expiring status in data-uie-attribute

- app/page/template/partials/template-message.htm
- app/style/content/conversation/message-list.less
PR goes to branch `dev_next` as all features for the release are on `dev` locking it essentially.
> Add accent color to sender name in message header (WEBAPP-3481)

- app/script/view_model/AuthViewModel.coffee
**Email/password login**
- email
- username with  @
- username without  @
- phone number in e164 format
- if geoip available : plain phone number if geoip matches with origin of phone number
- otherwise: plain phone number if navigator.language matches with origin of phone number
> Secretly enable login with username from email field (WEBAPP-3545)

- app/script/util/util.coffee
Still working on the image asset rewrite and there a some things left. But this should make its way into dev regardless of the image asset PR.
> Use svg for dummy images

- app/page/template/content/collection.htm
- app/script/components/image.coffee
> Open image detail view only when image is loaded (WEBAPP-3547)

- app/page/template/_dist/app.htm
- app/script/localization/strings-hu.coffee
- app/script/localization/strings-init.coffee
- trans.py
https://github.com/wireapp/wire-desktop/pull/345
> 🇭🇺 Add Hungarian 🇭🇺

- app/style/content/conversation/message-list.less
Adjusting red colored names in Conversation
> Adjust the opacity of red accent in Conversation

- app/style/components/device-card.less
> Make the fingerprint selectable

- app/page/template/partials/template-message.htm
- app/script/components/asset/linkPreviewAsset.coffee
- app/style/common/label.less
- app/style/components/asset/asset-header.less
- app/style/components/asset/link-preview-asset.less
- app/style/content/conversation/message-list.less
Make names 12px remove uppercase
> Text styling tweaks in Conversation

- app/script/ui/WindowHandler.coffee
> Catching degraded cancellation errors

- app/page/auth.html
- app/script/auth/AuthService.coffee
- app/script/client/ClientRepository.coffee
- app/script/localization/strings-de.coffee
- app/script/localization/strings.coffee
- app/script/main/app.coffee
- app/script/storage/StorageRepository.coffee
- app/script/storage/StorageService.coffee
- app/script/view_model/AuthViewModel.coffee
- app/script/view_model/content/PreferencesAccountViewModel.coffee
- test/unit_tests/client/ClientRepositorySpec.coffee
> Ensure removal of crypto related info from database on client deletion (WEBAPP-2629, WEBAPP-3567)

- app/script/client/ClientRepository.coffee
- app/script/client/ClientService.coffee
- app/script/view_model/AuthViewModel.coffee
> Never add the current client to the self user devices (WEBAPP-3552)

- app/script/client/ClientRepository.coffee
> Database deletion procedure cleanup

- app/script/client/ClientRepository.coffee
> Ensure database reinit after client deletion (WEBAPP-3575)

- app/script/calling/handler/CallStateHandler.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/telemetry/calling/CallTelemetry.coffee
- app/script/tracking/EventName.coffee
> Add video flag to call initiation event (WEBAPP-3478)

- app/script/view_model/list/StartUIViewModel.coffee
The selected file was released since the timeout was to long. so i lowered the timeout and aligned it with the other actions.
> selected image from search not send (WEBAPP-3506)

- app/script/tracking/EventName.coffee
> Rename established call event (WEBAPP-3583)

- app/page/template/content/preferences-options.htm
- app/page/template/list/start-ui.htm
- app/script/connect/ConnectRepository.coffee
- https://github.com/wireapp/node-addressbook/pull/3
- https://github.com/wireapp/wire-desktop/pull/332
> Asynchronous address book

- .gitignore
- .idea/wire-webapp.iml
- docs/calling/calling_v3.md
> Added documentation about calling v3

- app/script/view_model/VideoCallingViewModel.coffee
> Repaired TOGGLE constant

- app/script/cryptography/CryptographyRepository.coffee
> Fixed error when trying to encrypt for already deleted clients

- app/script/cryptography/CryptographyRepository.coffee
- app/script/event/EventRepository.coffee
- bower.json
> Added Cryptobox with disabled logging

- app/page/template/_dist/vendor.htm
- app/script/cryptography/CryptographyRepository.coffee
- app/script/event/EventRepository.coffee
- app/script/storage/StorageService.coffee
- app/script/tracking/EventTrackingRepository.coffee
- app/script/util/util.coffee
- bower.json
- test/api/TestFactory.js
> Removed bazinga64 & Logdown

- app/script/calling/CallingRepository.coffee
- test/unit_tests/calling/CallingRepositorySpec.coffee
> Turn on calling v3 by default (on internal builds)

- app/script/audio/AudioRepository.coffee
- app/script/calling/entities/FlowAudio.coffee
> Don't execute "createMediaStreamSource" on a closed AudioContext

- app/script/calling/entities/EFlow.coffee
- app/script/calling/entities/FlowAudio.coffee
- app/script/calling/v3/CallCenter.coffee
> Catching DOMException when AudioContext has been closed

- app/page/template/modals.htm
- app/script/entity/User.coffee
- app/script/event/WebApp.coffee
- app/script/user/UserRepository.coffee
- app/script/view_model/content/PreferencesAccountViewModel.coffee
- test/unit_tests/user/UserRepositorySpec.coffee
> Fixed duplication of own clients

- app/script/client/ClientRepository.coffee
> Noticing when a client was added (while being logged out)

- app/script/view_model/AuthViewModel.coffee
> Initialize user repository with client repository

- app/script/event/EventRepository.coffee
Related to wireapp/proteus.js#36
> Log error message from Proteus "RemoteIdentityChanged" error

- app/script/util/DebugUtil.coffee
Convenience function for @Yserz.
Usage:
```javascript
wire.app.util.debug.block_all_connections().then(function(blocks){console.log(`Blocked ${blocks.length} users.`, blocks);});
```
> Added "wire.app.util.debug.block_all_connections"

- package.json
Closes #765
https://greenkeeper.io/
> chore(package): update autoprefixer to version 6.7.4

- app/script/entity/User.coffee
- app/script/tracking/EventTrackingRepository.coffee
- app/script/user/UserMapper.coffee
- test/api/TestFactory.js
- test/api/payloads.js
- test/unit_tests/user/UserMapperSpec.coffee
> Removed Localytics ID

- app/page/template/_dist/vendor.htm
- app/script/conversation/ConversationRepository.coffee
- app/script/conversation/EventMapper.coffee
- bower.json
Implements sending of video previews within asset v3
> Video previews

- app/page/template/_dist/app.htm
- app/script/event/WebApp.coffee
- app/script/main/app.coffee
- app/script/tracking/DimensionName.coffee
- app/script/tracking/EventTrackingRepository.coffee
> Added custom dimension "contacts"

- app/page/template/_dist/vendor.htm
- app/script/links/LinkPreviewHelpers.coffee
- app/script/util/util.coffee
- bower.json
Reverts wireapp/wire-webapp#785
> Revert "Replace twitter-text with linkify"

- app/script/conversation/ConversationRepository.coffee
Image orientation information is removed by the image compression
> Skip compression for video previews

- app/page/template/_dist/vendor.htm
- bower.json
> Cryptobox v4

- app/script/telemetry/calling/FlowTelemetry.coffee
- bower.json
- update webRTC Adapter to v3.1.6 which supports standards compliant RTCPeerConnection.getStats()
> Update to standards compliant RTCPeerConnection.getStats() handling

- app/script/util/DebugUtil.coffee
> New debug code to break sessions

- app/script/storage/StorageService.coffee
> Removed "conversation_events" object store

- app/script/calling/entities/ECall.coffee
- app/script/calling/entities/ECallMessage.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/conversation/EventBuilder.coffee
- use event builder to create events
- ensure use of otr calling message timestamp
> Rework missed call messages (WEBAPP-3698)

- app/script/event/EventRepository.coffee
> More explicit error messages on session errors

- bower.json
- update Raygun4js to version '2.5.3'
> Update Raygun dependency

- app/page/template/_dist/app.htm
- app/script/config.coffee
- app/script/event/WebApp.coffee
- app/script/main/app.coffee
- app/script/tracking/CustomDimension.coffee
- app/script/tracking/EventTrackingRepository.coffee
- app/script/ui/WindowHandler.coffee
- app/script/user/UserRepository.coffee
- test/unit_tests/tracking/EventTrackingRepositorySpec.coffee
> Localytics custom dimensions and sessions regressions (WEBAPP-3610, WEBAPP-3707)

- app/script/storage/StorageService.coffee
> Defined database schema v13

- app/page/template/_dist/app.htm
- app/script/localization/strings-init.coffee
- app/script/localization/strings-sk.coffee
- trans.py
https://github.com/wireapp/wire-desktop/pull/496
> 🇸🇰 Add Slovak 🇸🇰

- app/script/storage/StorageService.coffee
> Removed database version 14

- app/script/calling/rtc/StatsType.coffee
https://groups.google.com/forum/#!topic/discuss-webrtc/OXqm0tjg8hs
> Rename stats types to adjust to standard (WEBAPP-3720)

- app/script/calling/CallingRepository.coffee
- test/unit_tests/calling/CallingRepositorySpec.coffee
> Backend call protocol version should prevail unless URL param is set (WEBAPP-3722)

- app/script/system_notification/SystemNotificationRepository.coffee
- test/unit_tests/system_notification/SystemNotificationRepositorySpec.coffee
> Show notifications while in preferences and collections (WEBAPP-3585)

- app/script/audio/AudioRepository.coffee
- app/script/calling/entities/ECall.coffee
- app/script/calling/entities/EFlow.coffee
- app/script/calling/entities/Flow.coffee
- app/script/calling/handler/CallSignalingHandler.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/main/app.coffee
- app/script/media/MediaRepository.coffee
- app/script/media/MediaStreamHandler.coffee
- app/script/view_model/content/ContentViewModel.coffee
- app/script/view_model/content/PreferencesAVViewModel.coffee
- moving AudioContext to z.media.MediaRepository
Thanks Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1233447
> Improve media resource release (WEBAPP-3206, WEBAPP-3406, WEBAPP-3579)

- app/script/conversation/EventBuilder.coffee
- app/script/event/EventRepository.coffee
> Improve check for ongoing calls

- app/script/tracking/EventTrackingRepository.coffee
- in order to enable for internal builds, the check is moved to SLD
> Disable Localytics based on domain

- .eslintrc.yaml
- package.json
> Added ESLint to build pipeline

- app/script/config.js
> Fixed uglify issues with ES6 syntax

- app/script/conversation/ConversationRepository.coffee
> Fixed parameters for message deletion

- Gruntfile.js
> No need for newer in the copy task

- package.json
> Using UglifyJS which supports ES6

- app/script/conversation/ConversationRepository.coffee
Can be tested with:
```js
wire.app.repository.conversation.send_location(wire.app.repository.conversation.active_conversation(), 13.402135848999023, 52.52390670776367, "Rosenthaler Straße 40 -41", 15);
```
> Exposing Location API

- app/script/conversation/ConversationRepository.coffee
- app/script/util/util.coffee
- test/unit_tests/util/UtilSpec.coffee
since the timestamp issue was resolved we can remove the deferred hack when sending files
> remove deferred hack and unused code

- app/script/calling/CallingService.coffee
- app/script/calling/entities/ECall.coffee
- app/script/calling/entities/EFlow.coffee
- app/script/calling/entities/Flow.coffee
- app/script/calling/v2/CallError.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/calling/v3/CallError.coffee
- app/script/media/MediaStreamHandler.coffee
- app/script/service/Client.coffee
- app/script/view_model/VideoCallingViewModel.coffee
- force cache bypass for calls config
- trigger renegotiation on remote update offer
- prevent call termination reason for drops to be overwritten by manual interaction
> Call reliability improvements (WEBAPP-3718)

- app/script/entity/Conversation.coffee
- test/unit_tests/entity/ConversationSpec.coffee
> Improve add message check (WEBAPP-3751)

- app/script/components/userInput.coffee
> Disabled autocomplete on user input (WEBAPP-3771)

- app/script/calling/entities/Flow.coffee
- app/script/calling/v3/CallCenter.coffee
> staging bump 2017-03-27

- app/script/announce/AnnounceRepository.js
> Fixed bug within AnnounceRepository

- app/script/calling/entities/EFlow.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/calling/v3/CallError.coffee
> Improve data channel lifecycle handling

- app/page/template/list/start-ui.htm
- app/script/view_model/list/StartUIViewModel.coffee
- enable add contacts to group
- sort contacts alphabetically
> start ui improvements

- app/script/calling/v3/CallCenter.coffee
> Request MediaStream for video calls only when incoming via websocket (WEBAPP-3776)

- app/script/calling/v3/CallCenter.coffee
> Fixed leaving a call with no participants left (WEBAPP-3783)

- app/script/calling/CallingRepository.coffee
- app/script/calling/handler/CallStateHandler.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/conversation/ConversationRepository.coffee
- app/script/util/DebugUtil.coffee
- app/script/view_model/ImageDetailViewViewModel.coffee
- app/script/view_model/content/ContentViewModel.coffee
> Rename 'get_conversation_by_id' for wrapper compatibility (WEBAPP-3792)

- app/script/conversation/ConversationRepository.coffee
> Do not start encrypting messages before notification stream is handled (WEBAPP-3687)

- app/style/common/like.less
- app/style/common/mixins.less
> like bug (WEBAPP-3218)

- app/script/calling/entities/ECall.coffee
- app/script/calling/entities/EFlow.coffee
- app/script/calling/rtc/MediaStreamError.coffee
- app/script/calling/rtc/MediaStreamErrorTypes.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/media/MediaStreamHandler.coffee
- app/script/telemetry/calling/FlowTelemetry.coffee
> Delay renegotiation on PeerConnection disconnect (WEBAPP-3774)

- app/script/calling/entities/ECall.coffee
- app/script/calling/entities/EParticipant.coffee
> Reset flow when removing participant (WEBAPP-3759)

- app/script/calling/v3/CallCenter.coffee
> Ensure call ended event (WEBAPP-3759)

- bower.json
> Updated Cryptobox to v5.0.4

- app/script/event/EventRepository.coffee
> Prevent "undefined" error code

- app/script/calling/entities/EFlow.coffee
- app/script/view_model/VideoCallingViewModel.coffee
- app/script/view_model/list/ConversationListViewModel.coffee
> Enable renegotiation calling features

- app/script/event/EventRepository.coffee
> Change decryption error reporting

- app/script/conversation/ConversationRepository.coffee
> Update users on message before handling it (WEBAPP-3812, WEBAPP-3813)

- app/script/calling/entities/EFlow.coffee
- app/script/calling/v3/CallCenter.coffee
> Improve media state handling and renegotiation (WEBAPP-3774, WEBAPP-3809)

- app/script/calling/entities/EFlow.coffee
- app/script/calling/v3/CallCenter.coffee
> Toggling local video state disabled incoming screenshare (WEBAPP-3815)

- .eslintrc.yaml
- app/script/audio/AudioRepository.js
- app/script/auth/AuthRepository.js
- app/script/auth/AuthService.js
- test/api/TestFactory.js
We don't need to use JSDoc everywhere but when we do we should do it right. 😃
> Enforce valid JSDoc 3 syntax

- app/script/calling/entities/EFlow.coffee
- app/script/calling/entities/Flow.coffee
- app/script/media/MediaStreamHandler.coffee
> Set mute state after stream change (WEBAPP-3781)

- app/style/common/common.less
- app/style/common/label.less
> Selectable name & username

- app/script/tracking/EventTrackingRepository.coffee
- test/unit_tests/tracking/EventTrackingRepositorySpec.coffee
Precautions for unintentional error loops.
> Raygun error reporting throttling

- app/script/connect/ConnectGoogleService.js
- app/script/connect/ConnectRepository.js
- app/script/search/SearchRepository.coffee
- app/script/view_model/list/StartUIViewModel.coffee
- aws/main.py
> GMail contact import es6 support (WEBAPP-3816)

- app/script/conversation/ConversationRepository.coffee
> staging bump 2017-04-11#2

- app/page/template/list/start-ui.htm
- app/script/connect/ConnectRepository.js
- app/script/search/SearchRepository.coffee
> Gmail import with no suggestions (WEBAPP-3823)

- app/script/connect/ConnectRepository.js
> macOS contact import (WEBAPP-3670)

- Gruntfile.js
- app/page/template/_dist/app.htm
- app/script/conversation/ConversationRepository.coffee
- app/script/location/GeoLocation.js
- app/script/util/ObjectUtil.js
- grunt/config/watch.coffee
- test/unit_tests/location/GeoLocationSpec.js
- test/unit_tests/util/ObjectUtilSpec.js
> staging 2017-04-13#2

- app/script/conversation/ConversationRepository.coffee
> Show unsent picture as unsent (WEBAPP-3828)

- app/script/view_model/ConversationInputEmojiViewModel.js
> Emoji autocomplete popup fix for Firefox

- app/script/conversation/ConversationRepository.coffee
- app/script/view_model/ConversationInputEmojiViewModel.js
> staging bump 2017-04-13#3

- app/script/properties/PropertiesRepository.js
- app/script/properties/PropertiesType.js
> Save updated preferences (WEBAPP-3839, WEBAPP-3840, WEBAPP-3841, WEBAPP-3842, WEBAPP-3843, WEBAPP-3844)

- app/script/util/keycode.coffee
- app/script/view_model/ConversationInputEmojiViewModel.js
> Sort emoji in autocomplete

- .eslintrc.yaml
- app/script/auth/AccessTokenError.js
- app/script/connect/ConnectRepository.js
- app/script/cryptography/CryptographyError.js
- app/script/cryptography/CryptographyMapper.js
- app/script/media/MediaDevicesHandler.js
- app/script/media/MediaError.js
- app/script/media/MediaStreamHandler.js
- app/script/properties/PropertiesRepository.js
- app/script/system_notification/SystemNotificationRepository.js
- app/script/telemetry/calling/FlowTelemetry.js
- bin/deployment_notification.js
> Add default-case linting rule

- app/script/conversation/ConversationRepository.coffee
- app/script/conversation/ConversationService.coffee
> Add receiving queue for decrypted events

- app/script/auth/AuthService.js
- app/script/main/app.coffee
- app/script/service/Client.coffee
- app/script/view_model/WarningsViewModel.coffee
- test/unit_tests/service/ClientSpec.coffee
> Add connectivity check queue

- aws/util.py
> Block Franz based on UA string

- app/script/system_notification/SystemNotificationRepository.js
> Adjusted context for permission state request

- app/script/components/asset/fileAsset.coffee
- app/script/entity/message/File.js
> Fixed context for file download

- app/script/cryptography/CryptographyMapper.js
- test/unit_tests/cryptography/CryptographyMapperSpec.coffee
> Fixed IDs for generic messages within external messages

- app/script/calling/entities/EFlow.coffee
- app/script/calling/entities/Flow.coffee
- app/script/calling/v3/CallCenter.coffee
- app/script/system_notification/SystemNotificationRepository.js
> Calling improvements

- app/script/media/MediaDevicesHandler.js
> Match stored device ID for media devices

- app/script/view_model/content/PreferencesAVViewModel.coffee
> Show video preview in preferences (WEBAPP-3853)

- package.json
> Update "UglifyJS" to "harmony-v2.8.22"

- app/script/util/Environment.js
- aws/config.py
> Enforcing "Firefox 52 (ESR)"

- app/script/media/MediaStreamHandler.js
Small additional safeguard from error reporting
> Change MediaStreamTrack enabled state only if found

- app/script/conversation/ConversationRepository.coffee
Fixes: https://github.com/wireapp/wire-webapp/issues/1012
> Partially revert #990 to show empty conversation

- app/script/auth/AuthRepository.js
- app/script/event/WebSocketService.js
- app/script/service/BackendClient.js
> ES6 'auth' cleanup (WEBAPP-3877)

- app/script/ui/Shortcut.js
> Use correct topic for event shortcuts (WEBAPP-3879)

- app/script/announce/AnnounceRepository.js
> Skip version and announcement check if offline (WEBAPP-3882)

- app/script/event/EventRepository.js
> Fixed destructuring

- app/script/util/DebugUtil.js
> Safety net for using debug function

- app/script/conversation/ConversationRepository.coffee
- app/script/service/BackendClient.js
- app/script/util/PromiseQueue.js
> Only Promises should be added to PromiseQueues (WEBAPP-3889)

- .gitignore
- app/script/conversation/ConversationRepository.coffee
- app/script/service/BackendClient.js
- app/script/util/PromiseQueue.js
> staging bump 2017-05-20#2

- aws/main.py
> Added missing https for domain "1-ps.googleusercontent.com"

- app/script/view_model/list/StartUIViewModel.coffee
fixes https://github.com/wireapp/wire-desktop/issues/619
> dont display blocked top people

- package.json
Closes #1077
https://greenkeeper.io/
> chore(package): update eslint-plugin-jsdoc to version 3.0.2

- app/page/template/_dist/app.htm
- app/script/user/UserRepository.js
> Fixed invisible connections (connect requests which don't show up in UI)

- app/script/entity/Conversation.js
- app/script/main/app.js
> Fixed webapp login

- app/script/bot/BotRepository.js
- app/script/conversation/ConversationRepository.js
- app/script/event/EventRepository.js
- app/script/system_notification/SystemNotificationRepository.js
- app/script/view_model/ParticipantsViewModel.coffee
- app/script/view_model/list/StartUIViewModel.coffee
- test/unit_tests/conversation/ConversationServiceNoCompoundSpec.js
> Hide notifications during stream handling (WEBAPP-3913)

- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- app/script/calling/v3/CallCenter.js
- app/script/calling/v3/CallError.js
> Handle SDP state conflicts in group calls

- app/script/conversation/ConversationRepository.js
> Event handling errrors

- app/script/conversation/ConversationRepository.js
> Improve event handling on startup

- app/script/audio/AudioRepository.js
- app/script/calling/CallingRepository.js
- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- app/script/calling/enum/SDPNegotiationMode.js
- app/script/calling/v3/CallCenter.js
- app/script/client/ClientRepository.js
- app/script/connect/ConnectGoogleService.js
- app/script/connect/ConnectRepository.js
- app/script/conversation/ConversationRepository.js
- app/script/main/app.js
- app/script/media/MediaDevicesHandler.js
- app/script/media/MediaStreamHandler.js
- app/script/system_notification/SystemNotificationRepository.js
- app/script/util/DebugUtil.js
> v3 calling for groups: Improved SDP state collision handling

- app/script/conversation/ConversationRepository.js
This ensure that when the conversation was deleted, archive can still be performed locally. I also removed the callback in `clear_conversation`
> archive conversation when previously deleted (WEBAPP-3862)

- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- app/script/calling/entities/Flow.coffee
- app/script/calling/rtc/SignalingState.js
- app/script/calling/v3/CallCenter.js
> Group calling v3: Missed call message

- app/page/template/_dist/app.htm
- app/script/conversation/ConversationRepository.js
- app/script/cryptography/CryptographyMapper.js
- app/script/cryptography/GenericMessageType.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/cryptography/CryptographyMapperSpec.js
- test/unit_tests/cryptography/CryptographyRepositorySpec.js
> Add generic message type

- app/script/conversation/ConversationRepository.js
- app/script/view_model/bindings/CommonBindings.js
unarchive should also take into account that there could be an 404 if you left the conversation. Also fixed the viewport binding
> fix in_viewport binding and unarchive (WEBAPP-3933)

- app/script/calling/entities/EFlow.js
- app/script/calling/v3/CallCenter.js
- app/script/conversation/ConversationRepository.js
- app/script/event/EventRepository.js
- app/script/system_notification/SystemNotificationRepository.js
> Explicitly forward event source

- .npmrc
- https://devcenter.heroku.com/articles/node-best-practices#use-a-smart-npmrc
> Locking down dependencies

- app/script/calling/CallingRepository.js
- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- app/script/calling/entities/FlowAudio.js
- app/script/calling/v3/CallCenter.js
- app/script/event/EventRepository.js
- app/script/media/MediaRepository.js
> Group calling v3: Leave state improvements

- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- enable rejoin
- store data channel state per flow
- improved group check implementation
> Group calling v3: Rejoin behavior

- app/script/view_model/list/ArchiveViewModel.js
> Fixed unarchiving conversations

- app/script/view_model/content/CollectionViewModel.js
> Fixed CollectionViewModel bindings

- app/script/calling/CallingRepository.js
- test/unit_tests/calling/CallingRepositorySpec.js
> Enabling v3 group calls by default

- app/script/view_model/AuthViewModel.js
- app/script/view_model/ConversationInputViewModel.js
- app/script/view_model/ImageDetailViewViewModel.js
- app/script/view_model/MessageListViewModel.js
- app/script/view_model/ParticipantsViewModel.js
> ES6 migration regressions

- app/script/calling/entities/EFlow.js
- app/script/telemetry/calling/FlowTelemetry.js
- bower.json
> Group Calling v3: Fix MediaStream changes (WEBAPP-3947, WEBAPP-3966, WEBAPP-3967)

- app/script/calling/entities/ECallMessage.js
- app/script/calling/mapper/ECallMessageMapper.js
- app/script/calling/v3/CallCenter.js
- app/script/calling/v3/CallError.js
> Group Calling v3: Target UPDATE messages

- app/script/conversation/ConversationRepository.js
- app/script/user/UserRepository.js
- app/script/view_model/ConversationInputViewModel.js
- app/script/view_model/WindowTitleViewModel.js
> staging bump 2017-05-24#2

- app/script/view_model/ConversationInputViewModel.js
- app/script/view_model/GiphyViewModel.js
- app/script/view_model/MessageListViewModel.js
- app/script/view_model/VideoCallingViewModel.js
- app/script/view_model/list/StartUIViewModel.js
> staging bump 2017-05-26

- app/script/auth/URLParameter.js
- app/script/calling/CallingRepository.js
- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- app/script/calling/v3/CallCenter.js
- app/script/main/app.js
- app/script/view_model/AuthViewModel.js
- test/unit_tests/util/UtilSpec.js
> Calling v3: Improve reliability of config retrieval (WEBAPP-3958)

- app/script/view_model/list/StartUIViewModel.js
> Prevent duplicate conversation creation

- app/script/auth/ValidationError.js
- app/script/client/ClientRepository.js
- app/script/components/userInput.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/entity/message/CallMessage.js
- app/script/entity/message/DecryptErrorMessage.js
- app/script/entity/message/MemberMessage.js
- app/script/entity/message/PingMessage.js
- app/script/entity/message/RenameMessage.js
- app/script/entity/message/VerificationMessage.js
- app/script/localization/Localizer.js
- app/script/user/UserRepository.js
- app/script/util/LocalizerUtil.js
- app/script/util/util.js
- test/unit_tests/view_model/WindowTitleViewModelSpec.js
> Decrease dependency on deprecated localizer

- app/script/team/TeamRepository.js
* Update team instead of removing and adding it.
* Remove error messages for now
> Team update

- app/script/localization/Localizer.js
- app/script/view_model/ImageDetailViewViewModel.js
> Label object in collection (WEBAPP-4007)

- app/script/view_model/content/ContentViewModel.js
> Show watermark if no conversation in team

- app/script/conversation/ConversationRepository.js
> Only return active conversations with team members (WEBAPP-4009)

- app/script/components/userAvatar.js
- app/script/view_model/list/StartUIViewModel.js
> The first conversation created in a team always jumps to personal space (WEBAPP-4026)

- app/script/user/UserRepository.js
> Decrease number of connections dimension updates

- app/script/bot/BotRepository.js
> Fix adding bot to existing conversation

- app/script/calling/entities/EFlow.js
- use local variable to avoid errors
> SDP types in log messages

- app/script/calling/entities/ECall.js
- app/script/calling/entities/EFlow.js
- app/script/calling/mapper/SDPMapper.js
- app/script/calling/v3/CallCenter.js
- app/script/components/list/conversationListCell.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- test/unit_tests/entity/ConversationSpec.js
> Identify 1to1 conversation in teams (WEBAPP-4012, WEBAPP-4013, WEBAPP-4014)

- app/script/calling/v3/CallCenter.js
> Simplify call setup handling (WEBAPP-4014)

- app/script/components/userProfile.js
> Team members can now directly talk to other people from people popover

- app/page/template/partials/template-message.htm
- app/script/conversation/ConversationRepository.js
- app/script/conversation/EventBuilder.js
- app/script/conversation/EventMapper.js
- app/script/entity/message/MemberMessage.js
- app/script/event/Client.js
- app/script/event/EventRepository.js
- app/script/localization/translations/webapp-de.js
- app/script/localization/webapp.js
> Show removal from team system message (WEBAPP-4033)

- app/script/conversation/ConversationRepository.js
- app/script/event/WebApp.js
- app/script/system_notification/SystemNotificationRepository.js
- app/script/user/UserRepository.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/content/ContentViewModel.js
- app/script/view_model/list/ConversationListViewModel.js
- app/script/view_model/list/ListViewModel.js
> Context menu from archive do not close archive

- app/page/template/partials/template-user-profile.htm
- app/script/components/userProfile.js
> Show proper people footer in team 1to1 conversation (WEBAPP-4036)

- app/script/view_model/list/ListViewModel.js
> Show block option in correct cases only (WEBAPP-2866, WEBAPP-4037)

- app/script/user/UserRepository.js
> Exclude bots from connected user dimension (WEBAPP-3819)

- app/script/view_model/content/PreferencesAccountViewModel.js
> Trim new name of user before changing it (WEBAPP-3542)

- app/script/conversation/ConversationRepository.js
- app/script/user/UserRepository.js
> Block fetching the same user in parallel (WEBAPP-4030)

- app/script/components/list/conversationListCell.js
- app/script/entity/Conversation.js
- test/unit_tests/entity/ConversationSpec.js
- test/unit_tests/system_notification/SystemNotificationRepositorySpec.js
> Show name and group icon for named 1to1 team conversations (WEBAPP-4038)

- app/script/event/EventRepository.js
- app/script/event/NotificationService.js
- test/unit_tests/event/EventRepositorySpec.js
> Fallback if last notification ID got lost (WEBAPP-3974)

- app/script/components/list/conversationListCell.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/content/ContentViewModel.js
> Add Conversation.is_team_group() (WEBAPP4019)

- app/script/config.js
- app/script/user/UserError.js
- app/script/user/UserRepository.js
- app/script/view_model/AuthViewModel.js
- app/script/view_model/content/PreferencesAccountViewModel.js
> Prevent short name for user

- app/script/service/BackendClient.js
> Ignore 'invalid-credentials' error label

- app/script/conversation/ConversationRepository.js
> Add safeguard to upload failed update

- app/script/config.js
- app/script/user/UserRepository.js
- app/script/view_model/content/PreferencesAccountViewModel.js
> Fix user picture update on Edge

- app/script/client/Client.js
> Set client properties by default

- app/script/view_model/content/PreferencesAccountViewModel.js
> Allow changing the name of the user (WEBAPP-4040)

- app/page/template/partials/template-user-profile.htm
- app/script/components/userProfile.js
- app/script/view_model/ParticipantsViewModel.js
- app/style/components/user-profile.less
> Show back button for user profile in groups (WEBAPP-4041)

- app/script/event/EventRepository.js
- app/script/event/NotificationService.js
> Reset last notification ID if missing (WEBAPP-3974)

- app/page/template/content/conversation/participants.htm
- app/page/template/partials/template-user-profile.htm
- app/script/components/userProfile.js
- app/script/view_model/MessageListViewModel.js
- app/script/view_model/ParticipantsViewModel.js
> Only show back button if opened from title bar (WEBAPP-4041)

- app/script/conversation/ConversationRepository.js
> Ensure deletion of conversation when team is deleted (WEBAPP-4025)

- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
> Update guest mapping on team changes (WEBAPP-4011)

- app/script/components/userProfile.js
- app/script/conversation/ConversationRepository.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/list/StartUIViewModel.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
> Reset cleared timestamp locally when getting 1to1 conversation (WEBAPP-4031)

- app/script/client/Client.js
> Set device label and model only for own devices (WEBAPP-4048)

- app/script/client/Client.js
- app/script/conversation/ConversationCellState.js
- app/script/view_model/VideoCallingViewModel.js
> release 2017-06-07#2

- app/script/view_model/list/StartUIViewModel.js
> Handle search input on enter

- app/page/template/_dist/app.htm
- app/script/calling/CallError.js
- app/script/calling/CallingRepository.js
- app/script/calling/SDPMapper.js
- app/script/calling/entities/Call.js
- app/script/calling/entities/Participant.js
> False No one to call alert (WEBAPP-4061)

- app/script/view_model/content/ContentViewModel.js
> Switch to team only if member is non-guest (WEBAPP-4028)

- app/script/view_model/list/ConversationListViewModel.js
> Use new localization for outgoing connect requests (WEBAPP-4063)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Call.js
> Add direction to call entity, joined and established event (WEBAPP-4006)

- app/script/calling/CallingRepository.js
> Join call from second device after leaving on first (WEBAPP-3972)

- app/script/system_notification/SystemNotificationRepository.js
> Refactor _should_hide_notification

- app/page/template/list/team-tabs.htm
> Show indicator on personal space if not selected

- app/script/main/app.js
- app/script/team/TeamEntity.js
- app/script/user/UserRepository.js
- app/script/util/PromiseQueue.js
> Ensure connections are retrieved before team members (WEBAPP-4030)

- app/script/entity/Conversation.js
- test/unit_tests/entity/ConversationSpec.js
> Filter duplicated messages before adding them to a conversation

- app/script/storage/StorageError.js
- app/script/storage/StorageService.js
- test/unit_tests/storage/StorageServiceSpec.js
Possible fix for "WEBAPP-3974"
> Prevent undefined values from being saved

- app/page/template/list/team-tabs.htm
- app/script/localization/webapp.js
- app/script/view_model/bindings/LocalizationBindings.js
- app/script/view_model/list/ConversationListViewModel.js
> Add preferences tooltip (WEBAPP-3876)

- app/script/entity/Conversation.js
- app/script/event/EventRepository.js
> Add messages without ID to conversation

- app/script/view_model/content/ContentViewModel.js
> Update active team before setting last active conversation (WEBAPP-4068)

- app/script/cryptography/CryptographyRepository.js
- app/script/event/EventRepository.js
- test/unit_tests/cryptography/CryptographyRepositorySpec.js
> Move decryption error handling logic

- app/page/template/content/conversation/participants.htm
- app/page/template/list/start-ui.htm
- app/page/template/partials/template-user-profile.htm
- app/script/components/userAvatar.js
- app/script/components/userList.js
- app/style/components/user-profile.less
> Show colored user avatars for team members (WEBAPP-4004)

- app/script/ui/Shortcut.js
> Changed shortcut to access start UI

- app/script/view_model/list/ListViewModel.js
Users reported that the context menu fails to open in some cases. This should fix one of them.
> Check for presence of user in context menu

- app/script/ui/Shortcut.js
- app/script/view_model/list/ListViewModel.js
> Improved shortcut to "mute" a conversation

- app/script/calling/SDPMapper.js
- app/script/calling/entities/Flow.js
> Store SDP when setting remote or local one

- app/script/conversation/ConversationError.js
- app/script/conversation/ConversationRepository.js
> Check for content message on upload failed update

- app/script/event/EventRepository.js
> Add GROUPLEAVE to forced calling events

- app/script/calling/CallingRepository.js
- app/script/connect/ConnectRepository.js
- app/script/connect/PhoneBook.js
- app/script/entity/User.js
- app/script/search/SearchRepository.js
- app/script/search/SearchResultMapper.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/list/StartUIViewModel.js
- removes old macOS implementation
- removes last references to mutual friends
- removes emails from upload as backend no longer matches based on these
- updates onboarding flow behavior as suggestions are no longer returned - but rather contains the same info as the auto-connects
> Address book upload cleanup

- app/script/view_model/MessageListViewModel.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/content/ContentViewModel.js
- app/script/view_model/list/TeamsTabViewModel.js
> Verify last active conversation is still in personal space (WEBAPP-4068)

- app/script/util/util.js
- test/unit_tests/util/UtilSpec.js
> Extension filtering for file transfers (WEBAPP-4087)

- app/script/auth/AuthView.js
- app/script/view_model/AuthViewModel.js
> Verify email on registration from invite

- app/script/view_model/AuthViewModel.js
> fix: Use invitation code instead of ID to register (WEBAPP-4103)

- app/script/calling/entities/Flow.js
- app/script/calling/entities/FlowAudio.js
- bower.json
> Deep merge using jQuery fails for MediaStream (WEBAPP-4114)

- app/script/service/BackendClient.js
- app/script/user/UserService.js
- app/script/view_model/AuthViewModel.js
> Requests with empty 201, 202, 204 responses are not considered failed (WEBAPP-4115)

- app/page/template/_dist/app.htm
> Change app initialization sequence (WEBAPP-4104, WEBAPP-4116)

- grunt/tasks/raygun.js
> staging bump 2017-06-22

- app/script/view_model/ConversationInputViewModel.js
> fix: FileList is not iteratable in MS Edge

- package.json
> chore(package): update jasmine-core to version 2.6.4

- app/script/conversation/ConversationRepository.js
- app/script/view_model/ConversationInputViewModel.js
> fix: Prevent ping without active conversation

- app/script/calling/entities/Flow.js
> fix: Ensure conflict resolution in group calls (WEBAPP-4119)

- app/page/template/content/preferences-account.htm
- app/page/template/content/preferences-options.htm
- app/page/template/list/preferences.htm
- app/page/template/warning.htm
- app/script/calling/SDPMapper.js
- app/script/client/ClientRepository.js
- app/script/conversation/ConversationRepository.js
- app/script/links/LinkPreviewRepository.js
- app/script/main/app.js
- app/script/media/MediaEmbeds.js
- app/script/media/MediaStreamHandler.js
- app/script/tracking/EventTrackingRepository.js
- app/script/tracking/Helpers.js
- app/script/ui/Shortcut.js
- app/script/util/Environment.js
- app/script/view_model/VideoCallingViewModel.js
> feat: Distinguish between Electron and Wire desktop

- app/page/template/content/conversation/participants.htm
- app/page/template/list/start-ui.htm
- app/script/components/userInput.js
- app/script/localization/webapp.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/bindings/ConversationListBindings.js
- app/style/components/user-input.less
- app/style/content/conversation/participants.less
- app/style/list/start-ui.less
> feat: Visual changes to user search input (WEBAPP-4121)

- package.json
> chore(package): update stylelint to version 7.12.0

- bower.json
> refactor: Moved antiscroll package

- .github/ISSUE_TEMPLATE.md
> docs: Link to feature request tracker

- app/script/event/EventRepository.js
- app/script/event/NotificationService.js
Fixes https://github.com/wireapp/wire-desktop/issues/655
Based on https://github.com/wireapp/wire-webapp/pull/1449
> Missed events message should only show once every 28 days (WEBAPP-4138)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Call.js
> Show unsuccessful outgoing calls (WEBAPP-4149)

- app/script/calling/CallingRepository.js
- app/script/client/ClientRepository.js
- app/script/conversation/ConversationRepository.js
- app/script/cryptography/CryptographyRepository.js
- app/script/cryptography/CryptographyService.js
- app/script/user/UserRepository.js
- test/unit_tests/conversation/ConversationRepositorySpec.js
- test/unit_tests/cryptography/CryptographyRepositorySpec.js
- test/unit_tests/user/UserRepositorySpec.js
> refactor: Rename user_client_map to recipients

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Call.js
- app/script/calling/entities/Flow.js
- app/script/calling/entities/FlowAudio.js
- app/script/calling/entities/Participant.js
- app/script/telemetry/calling/FlowTelemetry.js
> Call setup improvement: 'add_or_update participant' (WEBAPP-4145)

- app/script/view_model/content/PreferencesOptionsViewModel.js
> Ensure use of preview sending preference (WEBAPP-4148)

- app/script/links/LinkPreviewRepository.js
> Use first link preview only (WEBAPP-4120)

- app/script/client/ClientRepository.js
- app/script/event/EventRepository.js
- app/script/user/UserRepository.js
- app/script/view_model/AuthViewModel.js
> fix: Immediately log out user on account deletion (WEBAPP-4155) 

- app/image/emoji.json
- app/script/view_model/ConversationInputEmojiViewModel.js
Wait... more emojis, again?
Yes! 80 new emojis (not counting toned ones) and many more aliases were added to the list :smile: 
But most importantly, with the help from maintainer of this list I was finally able to fix the funny bug that you see below. In fact, this is the last known to me bug with regards to emojis :tada: 
Steps:
- Enter complex emoji, like `:family man girl boy`.
- Press <kbd>Backspace</kbd> multiple times.
Before:
After:
> Emoji: update list (80 new emojis), use full code points

- app/script/user/UserRepository.js
> Reflect user updates (WEBAPP-4157, WEBAPP-4158)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Call.js
- app/script/calling/entities/Flow.js
- app/script/calling/entities/Participant.js
- app/script/media/MediaDevicesHandler.js
- app/script/media/MediaStreamHandler.js
> Handle calling update events (WEBAPP-4130)

- app/script/telemetry/calling/CallTelemetry.js
> Add direction attribute to 'calling.ended_call' (WEBAPP-4159)

- app/page/template/_dist/app.htm
- app/script/calling/CallingRepository.js
- app/script/calling/entities/Flow.js
- app/script/media/MediaConstraintsHandler.js
- app/script/media/MediaDevicesHandler.js
- app/script/media/MediaElementHandler.js
- app/script/media/MediaError.js
- app/script/media/MediaRepository.js
- app/script/media/MediaStreamHandler.js
- app/script/media/VideoQualityMode.js
> Set proper constraints when requesting stream (WEBAPP-4130)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Call.js
- app/script/main/app.js
- app/script/util/DebugUtil.js
- test/api/TestFactory.js
- test/unit_tests/util/DebugUtilSpec.js
- add call message log
- ensure group check reset on call deactivation
> Prevent ghost group calls (WEBAPP-4145)

- app/script/calling/CallingRepository.js
- app/script/conversation/ConversationRepository.js
> fix: Link call message log to logging enabled state

- app/script/event/EventRepository.js
> fix: Set last event date if missing

- app/script/event/EventRepository.js
> staging bump 2017-07-05#2

- app/script/cryptography/CryptographyRepository.js
> fix: Incoming session reset should not create decryption error (WEBAPP-4164)

- app/script/calling/entities/Call.js
- app/script/calling/enum/TerminationReason.js
> fix: Ensure no group check is scheduled in dead call (WEBAPP-4163)

- app/script/calling/CallError.js
- app/script/calling/CallingRepository.js
> fix: Ignore rejection from second device in joined call (WEBAPP-4161)

- app/script/calling/CallError.js
- app/script/calling/entities/Call.js
- app/script/calling/entities/Flow.js
- app/script/calling/entities/Participant.js
> fix: Ensure proper call renegotiation on UPDATE message (WEBAPP-4162)

- app/script/view_model/content/PreferencesAVViewModel.js
> fix: MediaStream constraints creation in audio/video preferences (WEBAPP-4170)

- app/script/links/LinkPreviewRepository.js
- app/script/view_model/content/PreferencesAVViewModel.js
- package.json
> staging bump 2017-07-06#2

- app/page/template/list/start-ui.htm
- app/script/main/app.js
- app/script/search/SearchRepository.js
- app/script/team/TeamRepository.js
- app/script/user/UserRepository.js
- app/script/view_model/list/StartUIViewModel.js
- app/style/list/start-ui.less
- test/api/TestFactory.js
> feat: Search for team members (WEBAPP-4173, WEBAPP-4174)

- app/script/event/WebApp.js
- app/script/team/TeamRepository.js
- app/script/user/UserRepository.js
> fix: Account info update on user changes

- app/page/template/list/start-ui.htm
- app/script/event/WebApp.js
- app/script/team/TeamRepository.js
- app/script/user/UserRepository.js
> staging bump 2017-07-07#2

- app/script/team/TeamRepository.js
- app/script/user/UserRepository.js
- app/script/view_model/list/StartUIViewModel.js
> fix: Sort team members alphabetically (WEBAPP-4177)

- app/script/conversation/ConversationRepository.js
- app/script/main/app.js
- app/script/team/TeamRepository.js
> fix: Group search by participant in archived team conversations (WEBAPP-4185)

- app/script/event/WebApp.js
- app/script/team/TeamRepository.js
> feat: Handle team account deletion (WEBAPP-4154)

- app/page/template/partials/template-user-profile.htm
> fix: Show devices for team members (WEBAPP-4184)

- app/script/event/WebApp.js
- app/script/main/app.js
Pre-condition for https://github.com/wireapp/wire-desktop/pull/795
> feature: Publishing event after logout (WEBAPP-4201)

- app/script/user/UserRepository.js
> fix: Self user should not be shown as guest in team (WEBAPP-4202)

- app/script/media/MediaConstraintsHandler.js
> fix: Skip requesting default audio device

- app/page/template/list/start-ui.htm
- app/page/template/partials/template-user-profile.htm
- app/script/components/list/conversationListCell.js
- app/script/components/userList.js
- app/script/components/userProfile.js
- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/media/MediaConstraintsHandler.js
- app/script/user/UserRepository.js
- app/script/view_model/ParticipantsViewModel.js
- app/script/view_model/VideoCallingViewModel.js
- app/script/view_model/list/StartUIViewModel.js
- package.json
> staging bump 2017-07-13

- app/script/main/app.js
> fix: Add clear data to signed out life cycle event

- app/script/main/app.js
> staging bump 2017-07-13#2

- app/script/system_notification/SystemNotificationRepository.js
> fix: Clear notifications on page unload (WEBAPP-4208)

- app/script/ui/Shortcut.js
> feat: Change search shortcut to ctrl + alt + ,

- app/script/entity/Conversation.js
> fix: Do not hide messages with same ID from different users (WEBAPP-4231)

- app/script/conversation/ConversationRepository.js
- app/script/entity/User.js
- app/script/search/SearchRepository.js
- app/script/team/TeamRepository.js
- app/script/user/UserHandleGenerator.js
- app/script/user/UserRepository.js
- app/script/view_model/list/StartUIViewModel.js
- test/unit_tests/user/UserHandleGeneratorSpec.js
> fix: Skip username search for invalid handles (WEBAPP-4229)

- app/script/conversation/ConversationRepository.js
> fix: Do not create 1to1 conversation for connected users in teams (WEBAPP-4227)

- app/script/conversation/ConversationRepository.js
> fix: Disallow message overwrite from same user without edit flag (WEBAPP-4230)

- app/script/ui/Shortcut.js
> fix: Revert shortcut change for webapp on macOS (WEBAPP-4183)

- app/script/view_model/WindowTitleViewModel.js
> fix: Turn window title into observable

- bower.json
- yarn.lock
Switches from forked v10 speakingurl library to the original v13 one.
> refactor: Use original speakingurl

- app/script/conversation/ConversationRepository.js
- app/script/view_model/list/ListViewModel.js
> fix: Show watermark when archiving last conversation (WEBAPP-3807)

- app/script/conversation/ConversationMapper.js
- app/script/conversation/ConversationRepository.js
> chore: Conversation state loading cleanup

- app/script/conversation/ConversationRepository.js
> fix: Send delivery confirmation (WEBAPP-4248)

- app/script/conversation/ConversationRepository.js
- app/script/event/EventRepository.js
- app/script/localization/webapp.js
- app/script/main/app.js
- app/script/view_model/LoadingViewModel.js
> feat: Hide UI while handling messages from stream (WEBAPP-4219)

- app/script/conversation/ConversationRepository.js
- app/script/conversation/ConversationService.js
> fix: Mark assets as sent (WEBAPP-4246)

- app/script/conversation/ConversationRepository.js
> fix: Images can be liked and deleted for everyone (WEBAPP-4256)

- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- test/unit_tests/entity/ConversationSpec.js
> fix: Unmuting conversation should not unarchive it (WEBAPP-3398)

- app/script/conversation/ConversationRepository.js
> fix: Skip sent status update for reactions (WEBAPP-4260)

- app/script/conversation/ConversationRepository.js
> fix: Sent status updates (WEBAPP-4260)

- app/script/team/TeamRepository.js
> fix: Remove duplicates from team users

- app/script/conversation/ConversationRepository.js
- app/script/entity/Conversation.js
- app/script/team/TeamRepository.js
- test/unit_tests/entity/ConversationSpec.js
> staging bump 2017-08-02

- bower.json
> chore: Update bower dependencies

- README.md
> docs: Explanation how to login on production

- app/style/components/user-input.less
- yarn.lock
> fix: Fixed miscalculation of initial search input height (by Firefox)

- app/page/template/list/start-ui.htm
- app/script/view_model/list/StartUIViewModel.js
> fix: Show contact upload option for private account

- app/style/support.less
- aws/application.py
- grunt/config/less.js
> fix: Reduce number of server logs

- aws/application.py
> chore: Reduce number of server error logs

- app/script/conversation/ConversationRepository.js
> refactor: '_on_member_join' code cleanup

- app/script/conversation/ConversationError.js
- app/script/conversation/ConversationRepository.js
> fix: Handle attempted reaction update on wrong message

- app/script/conversation/ConversationRepository.js
> release 2017-08-08

- app/script/entity/message/DecryptErrorMessage.js
> fix: Show error message specific to remote identity change (WEBAPP-4270)

- app/script/entity/message/DecryptErrorMessage.js
> fix: Compare with proper Proteus error (WEBAPP-4271)

- app/script/calling/CallingRepository.js
> fix: Ensure local video on incoming video calls

- app/script/calling/entities/Flow.js
- app/script/components/list/conversationListCallingCell.js
- app/style/components/list/conversation-list-calling-cell.less
> fix: Participant avatars missing in group call (WEBAPP-4275)

- app/script/properties/PropertiesRepository.js
- app/script/tracking/EventTrackingRepository.js
> fix: Permission should always return the same result

- app/script/media/MediaStreamHandler.js
- app/script/util/Environment.js
> staging bump 2017-08-10

- app/script/client/ClientRepository.js
- app/script/conversation/ConversationRepository.js
- app/script/main/app.js
- test/api/TestFactory.js
> fix: Add fallback to logout removed clients on message sending

- app/script/conversation/ConversationService.js
- app/script/event/EventRepository.js
> fix: Avoid filtering system messages based on ID (WEBAPP-4284)

- app/script/client/ClientError.js
- app/script/client/ClientRepository.js
- app/script/cryptography/CryptographyRepository.js
- app/script/main/app.js
- app/script/view_model/AuthViewModel.js
- bower.json
- test/api/TestFactory.js
- test/unit_tests/client/ClientRepositorySpec.js
> chore: Bump wire-webapp-cryptobox to version '6.0.0'

- app/page/template/_dist/vendor.htm
- bower.json
- grunt/tasks/scripts.js
- yarn.lock
> chore: Update to libsodium v0.5.4

- bower.json
> chore: Update WebRTC adapter.js to version '4.2.2'

- app/script/client/ClientRepository.js
- app/script/view_model/AuthViewModel.js
> fix: Error handling on login with deleted client (WEBAPP-4289)

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Flow.js
> fix: Robust calling config retrieval

- app/script/calling/CallingRepository.js
- app/script/calling/entities/Flow.js
- app/script/conversation/ConversationService.js
- app/script/event/EventRepository.js
> staging bump 2017-08-22

- app/page/template/content/conversation/conversation-titlebar.htm
- app/script/localization/translations/webapp-de.js
- app/script/localization/translations/webapp-uk.js
- app/script/localization/webapp.js
Ads missing tooltip as reported in #1624
> fix: Add conversation search tooltip (WEBAPP-4297)

- app/script/calling/entities/Flow.js
- app/script/view_model/WarningsViewModel.js
> fix: Answering an audio call with video should send video (WEBAPP-4286)

- app/script/view_model/list/StartUIViewModel.js
> fix: Show no contacts copy for team creator on initial login (WEBAPP-4225)

- app/script/localization/translations/webapp-cs.js
- app/script/localization/translations/webapp-el.js
- app/script/localization/translations/webapp-es.js
- app/script/localization/translations/webapp-fr.js
- app/script/localization/translations/webapp-hu.js
- app/script/localization/translations/webapp-it.js
- app/script/localization/translations/webapp-lt.js
- app/script/localization/translations/webapp-nl.js
- app/script/localization/translations/webapp-pl.js
- app/script/localization/translations/webapp-pt.js
- app/script/localization/translations/webapp-ru.js
- app/script/localization/translations/webapp-sk.js
- app/script/localization/translations/webapp-tr.js
- app/script/localization/translations/webapp-uk.js
> feat: Update translations

- .gitignore
- app/script/localization/translations/webapp-cs.js
- app/script/localization/translations/webapp-el.js
- app/script/localization/translations/webapp-es.js
- app/script/localization/translations/webapp-fr.js
- app/script/localization/translations/webapp-hu.js
- app/script/localization/translations/webapp-it.js
- app/script/localization/translations/webapp-lt.js
- app/script/localization/translations/webapp-nl.js
- app/script/localization/translations/webapp-pl.js
- app/script/localization/translations/webapp-pt.js
- app/script/localization/translations/webapp-ru.js
- app/script/localization/translations/webapp-sk.js
- app/script/localization/translations/webapp-tr.js
- app/script/localization/translations/webapp-uk.js
- app/script/view_model/list/StartUIViewModel.js
- app/style/components/user-avatar.less
- app/style/content/conversation/message-list.less
- package.json
> staging bump 2017-08-30

- app/script/main/app.js
> chore: Remove obsolete v3 API switch reference

- bower.json
> chore: Bump speakingurl to version '14.0.1'

- app/page/template/_dist/vendor.htm
- bower.json
> chore: Reduce footprint by using pako_deflate
