wireapp/wire-webapp

aws/main.py
Fix for CSP issue:
> Refused to load the image 'file:///C:/Users/Benny/AppData/Local/wireinternal/app-2.9.2641/resources/app.asar/img/notification.png' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: https://*.giphy.com https://1-ps.googleusercontent.com https://*.localytics.com https://*.wire.com https://*.cloudfront.net https://*.zinfra.io https://csi.gstatic.com".
=> Allow images from filesystem

app/page/template/_dist/app.htm, app/script/conversation/ConversationRepository.coffee, app/script/conversation/ConversationService.coffee, app/script/conversation/EventMapper.coffee, app/script/entity/message/Asset.coffee, app/script/storage/StorageError.coffee, app/script/storage/StorageRepository.coffee, app/script/storage/StorageService.coffee, test/api/TestFactory.js, test/unit_tests/conversation/ConversationRepositorySpec.coffee, test/unit_tests/conversation/ConversationServiceSpec.coffee, test/unit_tests/conversation/EventMapperSpec.coffee, test/unit_tests/storage/StorageRepositorySpec.coffee
- https://wearezeta.atlassian.net/browse/WEBAPP-2581
- https://wearezeta.atlassian.net/browse/WEBAPP-2881
- https://wearezeta.atlassian.net/browse/WEBAPP-2970
Buggy:
```javascript
conversation_service.load_events_from_db
```
Call Chain:
```
get_events -> load_events_from_db -> _add_events_to_conversation -> map_json_events
```
```javascript
wire.app.repository.storage.storage_service.load_all('conversation_events','573b6978-7700-443e-9ce5-ff78b35ac590@0410795a-58dc-40d8-b216-cbc2360be21a')
.then(function(result){console.log(result);});
```
```javascript
wire.app.repository.conversation.conversation_service.load_events_from_db('573b6978-7700-443e-9ce5-ff78b35ac590', new Date('2016-06-02T21:57:59.316Z').getTime(), 30)
.then(function(info){console.log(info);});
```
Needs to fail if there is …
=> Extend storage tests

app/script/announce/AnnounceRepository.coffee, app/script/system_notification/SystemNotificationRepository.coffee
Notifications in MS Edge for Windows are only supported with the just released Anniversary update. We were missing the feature check for that in the `AnnounceRepository`
https://blogs.windows.com/msedgedev/2016/05/16/web-notifications-microsoft-edge/
=> Add feature check for window.Notification support in AnnounceRepository

app/script/auth/AuthService.coffee, app/script/conversation/ConversationRepository.coffee, app/script/event/WebSocketService.coffee, app/script/service/Client.coffee, app/script/user/UserRepository.coffee, app/script/view_model/ActionsViewModel.coffee, app/script/view_model/ConversationTitlebarViewModel.coffee, app/script/view_model/MessageListViewModel.coffee
- WebSocket fails to reconnect due to broken log message
- logging cleanup
- add 413 backend error to ignored list
- prevent exception when active_conversation is not set
- execute on_initial_rendering() only if set
- add safeguard for attempted calls from wrapper menus
- close archive after unarchiving last conversation
- execute menu actions on conversations only
=> Fixes for error reports

app/script/calling/entities/Flow.coffee, app/script/calling/handler/CallSignalingHandler.coffee
If a flow is gone on the backend it is gone. No point in keeping the flow locally, no point in trying to resend the SDP after send_sdp_timeout.
=> Reset flow if sending SDP fails in case it is gone on the backend

app/script/audio/AudioRepository.coffee, package.json, test/unit_tests/audio/AudioRepositorySpec.coffee
Turns out the bug in Karma was new in the latest release already filed and fixed:
https://github.com/karma-runner/karma/issues/2310
I also added backwards compatibility for Firefox for the non Promise based Audio.play()
=> Backwards compatibility and enabling unit tests for AudioRepository

app/script/view_model/bindings/CommonBindings.coffee
- previously the fullscreen alling UI was flickering on wrapper os x if window did not have focus and you hovered over it
- mouseenter, mousemove, and mouveleave all were fired
- mouseleave will now be ignored in this case for a smoother experience
=> Ignore 'mouseleave' if window does not have focus

app/script/main/app.coffee
- `wire.app.enable_debugging()` only eanbles all existing logggers
- later instances (eg. new call or flow entities) would fall back to defaults as noticed in https://github.com/wireapp/wire-desktop/issues/11
=> Override domain default on 'wire.app.enable_debugging()'

app/script/conversation/ConversationRepository.coffee, app/script/conversation/ConversationService.coffee, app/script/view_model/ConversationInputViewModel.coffee
- implemented the new backend endpoint to only send the confirmation to a specific user in a conversation
- disabled the sending completely due to the side effects found in nightly run
=> Send confirmation status only to other user

app/script/calling/entities/Flow.coffee, app/script/components/commonContacts.coffee
- SDP sending timeout gets cleared on sending and not on success to prevent duplicate sending
- positive states required for setting SDP instead of catching only a few negative ones
=> Clear timeout before sending SDP and improve gates for setting SDP

app/style/common/variables.less
Rendering of elements on non-integer boundary (position) produce a blurry element (including his content) on webkit browsers.
```css
.show-user .participants-transition {
transform: translateX(-104%); 
}
.group-user-profile {
top: 0px;
right: -104%;
}
.user-profile {
width: 288px;
....
}
```
.group-user-profile will be rendered on the X axis at 0 (top) - (288/(100/104)) = **299,52px** from the absolute right. As this position is not a integer it will render a blurry box.
Translation and right positionning at 100% or 125% will fix this issues with a 288px box width.
=> 👓 Content blurred 

app/script/localization/strings.coffee
Remove redundant ”fingerprint” copy
=> Sync settings copy across platforms

app/script/localization/strings-de.coffee, app/script/localization/strings.coffee
After the official release of macOS Sierra, all remaining “OS X” references in UI copy should be updated to use the new “macOS” name.
=> Update “OS X” name to “macOS”

app/script/view_model/MessageListViewModel.coffee
As discussed with design we will not start the timer until the window is in focus. People might see the message before that though.
=> Do not start ephemeral timer until window has focus

app/page/template/_dist/vendor.htm, bower.json, test/unit_tests/util/UtilSpec.coffee
remove speakingurl from webapp-module-external and make it a dependency in webapp. Created a PR on the speakingurl repo with the Omega fix we used to have in our repo. I also upgraded from 4.0.0 to 10.0.0. 
see https://github.com/pid/speakingurl/pull/86
=> include speakingurl

app/script/conversation/EventMapper.coffee, app/script/entity/message/Text.coffee, test/unit_tests/conversation/EventMapperSpec.coffee, test/unit_tests/entity/message/TextSpec.coffee
Cache already processed text (links, media embeds, markdown). This should increase performance when switching conversations and reduce memory allocation.
Possible Risks:
1. Text in the cache gets overwritten by a different message. Since the key to cache is a V4 UUID the possibility of having conflicts is not an issue.
2. User edits the text. Since the edited message is stored as a new message with a new nonce, it would create a new entry in the cache. The old one would be remove when new message are stored in the cache
I used an lru cache to store the processed text.
=> cached processed text

app/script/auth/AuthService.coffee
Backend needs to old access token to match incoming REST request and outgoing WebSocket connections
=> Send current access token on token refresh (WEBAPP-3390)

app/script/conversation/ConversationRepository.coffee, app/script/conversation/ConversationService.coffee, app/script/entity/Conversation.coffee, test/unit_tests/conversation/ConversationMapperSpec.coffee, test/unit_tests/conversation/ConversationServiceSpec.coffee, test/unit_tests/entity/ConversationSpec.coffee
I am trying to always pass proper values (which are of type `number`) to `load_events_from_db`. In cases where this fails (because of whatever reason), the old `_load_events_from_db_deprecated` function will be called. 
Because `_load_events_from_db_deprecated` is also called in the `catch` block, it will be used by Microsoft Edge (no explicit check for MS Edge needed).
=> Updated database query for conversation events

app/script/conversation/ConversationRepository.coffee, app/script/cryptography/CryptographyRepository.coffee, test/unit_tests/conversation/ConversationRepositorySpec.coffee
`_send_as_external_message` -> `should_send_as_external`
=> Message sending naming cleanup

app/page/template/partials/template-message.htm
Since the user avatar was removed using `display: none`, all knockout bindings where triggered. This can be avoided using the if binding.
=> hide avatar using knockouts virtual if binding

app/script/client/ClientRepository.coffee, app/script/cryptography/CryptographyRepository.coffee, app/script/main/app.coffee
This PR contains of two parts:
1. Never miss to add a client to the database:
The reason we have so many obsolete sessions in our database is that we map a session to each client in the db. We miss to initially store a client if a session is initiated from a message containing a pre-key during decryption. If the client was removed on the backend before we ever send a message to this user, we would never cleanup this session. This happens for example with clients that create many temporary clients like our internal bots before they used the service provider architecture.
This is fixed by storing a client locally when we create the session from a pre-key message during decryption just like we do when create a session from a pre-key during encryption.
2. Remove exisiting obsolete sessions: …
=> Properly cleanup outdated sessions

app/script/announce/AnnounceService.coffee, app/script/bot/BotRepository.coffee, app/script/bot/BotService.coffee, app/script/config.coffee, app/script/conversation/ConversationRepository.coffee, app/script/conversation/ConversationService.coffee, app/script/entity/User.coffee, app/script/localization/strings-de.coffee, app/script/localization/strings.coffee, app/script/util/Environment.coffee, app/script/view_model/AuthViewModel.coffee, app/script/view_model/ParticipantsViewModel.coffee, app/script/view_model/content/PreferencesAccountViewModel.coffee
- URLs are backend environment depending (bot and announcements API, password reset link)
- added the ability to remove a bot from a conversation
To remove a bot you currently need a little workaround, we have no meaning of identifying a user as a bot in a conversation right now. If you want to remove a bot you have to set such flag manually. In a 1to1 conversation you can simply do so with the following command from the console while in that conversation:
`wire.app.repository.conversation.active_conversation().participating_user_ets()[0].is_bot(true)`
=> Bots (WEBAPP-2077)

app/script/conversation/ConversationService.coffee, app/script/conversation/ConversationServiceNoCompound.coffee
Having a default value creates the issue that when querying for unread event it will always return up to 30 events.
=> limit should not have a default value

app/script/localization/strings-de.coffee, app/script/localization/strings-es.coffee, app/script/localization/strings-fr.coffee, app/script/localization/strings-it.coffee, app/script/localization/strings-pt.coffee, app/script/localization/strings-ro.coffee, app/script/localization/strings-ru.coffee, app/script/localization/strings-sl.coffee, app/script/localization/strings-tr.coffee, app/script/localization/strings-uk.coffee, app/script/localization/strings.coffee, app/script/message/SystemMessageType.coffee, app/script/system_notification/SystemNotificationRepository.coffee, app/script/user/UserRepository.coffee, test/unit_tests/system_notification/SystemNotificationRepositorySpec.coffee
If we had a new connection due to an auto-connect, the notification triggered would always look like our outgoing request was accepted. This PR fixes this and will show a more generic notification in this case instead that you are connected to a new contact.
=> Show appropriate notification for auto-connects (WEBAPP-3495)

app/page/index.html, app/page/template/warning.htm, app/script/announce/AnnounceRepository.coffee, app/script/announce/AnnounceService.coffee, app/script/auth/AuthRepository.coffee, app/script/client/ClientRepository.coffee, app/script/event/WebApp.coffee, app/script/localization/strings.coffee, app/script/main/app.coffee, app/script/util/Environment.coffee, app/script/view_model/WarningsViewModel.coffee, app/script/view_model/WindowTitleViewModel.coffee, app/script/view_model/bindings/ConversationListBindings.coffee, app/script/view_model/list/ConversationListViewModel.coffee, app/script/view_model/list/ListViewModel.coffee, app/style/warnings.less, aws/application.py, grunt/tasks/aws.coffee, test/unit_tests/announce/AnnounceRepositorySpec.coffee
Related to https://github.com/wireapp/wire-desktop/pull/336
- will listen to updated versions of the Wire for Windows version
- adds a current version reporting on the webapp server side
- browser will check against that version every 6 hours
- bar informing the user will be shown at that time
- click reloads the webapp or restarts the Windows wrapper
=> Improve auto-updater behavior on Windows (WEBAPP-3544)

app/script/announce/AnnounceRepository.coffee
It's been there since the initial commit months ago for no apparent reason
=> Remove unused local identity primary key from AnnounceRepository

app/page/template/partials/template-user-profile.htm, app/style/components/user-profile.less
Old click event remains as the arrow of the device card is bound to its existence
=> UX: Increase device click area

app/script/conversation/ConversationRepository.coffee, app/script/util/util.coffee, test/unit_tests/util/UtilSpec.coffee
Happended when two or more filse where saved with the same timestamp in the database, which would overwrite the previous one. Until we have a proper timestamp fix, deferring the fileupload should help.
=> defer file upload (WEBAPP-3322)

app/page/template/content/conversation/conversation-titlebar.htm, app/script/client/ClientRepository.coffee, app/script/components/userProfile.coffee, app/script/conversation/ConversationVerificationStateHandler.coffee, app/script/event/WebApp.coffee, app/script/user/UserRepository.coffee, test/unit_tests/conversation/ConversationVerificationStateHandlerSpec.coffee
Updated clients via popover should also trigger verificationstatehandler. Shield is now also bound to the verification state.
=> verificationstate (WEBAPP-3593)

app/script/cryptography/CryptographyRepository.coffee
No need to look up every message we decrypt. Proteus.errors.DecryptError.DuplicateMessage errors are handled and ignored anyway
=> skip local event check

app/script/conversation/ConversationRepository.coffee
Delete for everyone messages should always be granted as stated in the spec
=> Always grant delete for everyone messages (WEBAPP-3636)

app/page/template/list/conversations.htm, app/page/template/video-calling.htm, app/script/view_model/VideoCallingViewModel.coffee, app/script/view_model/list/ConversationListViewModel.coffee
The initial release of calling v3 does not support renegoatiation. In order to avoid broken functionality in 1:1 calls, the following will be disabled in the UI:
- screen sharing is not an available option
- camera cannot be switched during video calls
- audio calls cannot be upgraded to video calls
Changes need to be made to call UI in both conversation list and full screen mode
=> Disable calling features currently defunct in v3 (WEBAPP-3711)

app/script/conversation/ConversationRepository.coffee
Incoming v3 call events triggered call degradation warnings in verified chats.
Pulled all the checks related to the conversation verification state into one location for cleaner code.
=> Incoming call in verified conversation should not show warning (WEBAPP-3600)

app/script/calling/entities/EFlow.coffee, app/script/calling/entities/Flow.coffee
Parts of the RtcRtpSender support are implemented in latest Chrome versions. ReplaceTrack is not yet part of that implementation though. Thus the current feature check failed.
=> Extended RtcRtpSender.replaceTrack feature check (WEBAPP-3700

app/script/calling/CallingRepository.coffee, test/unit_tests/calling/CallingRepositorySpec.coffee
=> Always use v3 for 1to1 calls (WEBAPP-3727)

app/script/calling/v3/CallCenter.coffee
- in v3 we do not need to be aware of calls ongoing on any of our other devices
- if a call was accepted on another device we need to ensure to stop the ringtone locally and delete the call
=> Handle calls accepted on other clients (WEBAPP-3729)

app/script/entity/Conversation.coffee
- dont overwrite participant with connection.to
- debounce state updates
=> state saving improvements

app/script/calling/mapper/SDPMapper.coffee
=> Add temporary workaround for Chrome 57 to AVS incompatibility (WEBAPP-3742)

grunt/config/copy.coffee, grunt/config/watch.coffee
So simply instead of creating `.coffee` files inside the `app/script` directory we can now create `.js` files and the rest remain the same.
=> Support JavaScript for writing source files

app/script/media/MediaElementHandler.coffee, app/script/media/MediaRepository.coffee, app/script/media/MediaStreamHandler.coffee
- when starting an audio call we would not use the preselected audio output device, only subsequent changes to this were properly set to the audio element
=> Use preselected audio input/output devices (WEBAPP-3466)

app/page/template/content/preferences-av.htm, app/script/media/MediaElementHandler.coffee, app/script/util/Environment.coffee
Audio output device selection is not supported on Firefox
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
=> Disable audio output selection on Firefox (WEBAPP-3466)

app/script/event/EventRepository.coffee, app/script/main/app.coffee
If we delete a known session with a client for which we have not decrypted all events, ' `Proteus.errors.DecryptError.InvalidMessage` will be thrown when handling those events from the notification stream. This error was also mapped to `Proteus.errors.DecryptError.InvalidSignature` for no good reason.
=> Do not delete self user sessions before handling notification stream (WEBAPP-3784)

app/script/event/EventRepository.coffee, test/unit_tests/event/EventRepositorySpec.coffee
we should not store transient notification ids as last notification id since this results in an 404 error next time we ask for notifications with this id. Since the resulting error looks similar to what we would get in case of missed messages, we show the "you havent used this... " message
=> dont update last notification id with tansient notifications (WEBAPP-3799)

app/style/common/variables.less
@Dexwell  In order to avoid font change on Windows, references to Segoe UI Emoji have been removed. This works fine on Windows. Please retest on macOS.
https://github.com/wireapp/wire-webapp/pull/1040
=> Support latest emoji on macOS

app/script/conversation/ConversationRepository.coffee, app/script/conversation/EventBuilder.coffee, test/unit_tests/conversation/EventBuilderSpec.coffee
Notification stream is handled at the same time as users are mapped onto the conversations. Thus you end up in a race condition where self on the conversation might be undefined.
=> Explicitly pass self user to missed message event builder (WEBAPP-3834)

app/style/base.less, app/style/content/preferences/options.less, package.json
I realized that we don't lint our LESS files when running `yarn lint`. We only lint LESS files when executing `yarn test`. That's why I created separate tasks (`lint-scripts` & `lint-styles`) to lint scripts or styles and a generic task (`lint`) which lints both (scripts & styles).
I also removed the `lint-fix` script as it was just a copy of the previous `lint` task including `--fix`. But you can pass additional arguments to `npm` or `yarn` by using `--`. Please note the necessary `--`. So if you want to run `yarn lint-scripts` with automatic fixes, just do:
```bash
yarn lint-scripts -- --fix
```
=> Lint scripts & styles together

.eslintrc.yaml, app/script/assets/AssetRemoteData.js, app/script/assets/AssetService.js, app/script/audio/AudioRepository.js, app/script/auth/AuthRepository.js, app/script/auth/AuthService.js, app/script/bot/BotRepository.js, app/script/cache/CacheRepository.js, app/script/client/ClientRepository.js, app/script/client/ClientService.js, app/script/event/EventRepository.js, app/script/event/NotificationService.js, app/script/event/WebSocketService.js, app/script/extension/GiphyRepository.js, app/script/extension/GiphyService.js, app/script/links/LinkPreviewHelpers.js, app/script/location/GeoLocation.js, app/script/media/MediaDevicesHandler.js, app/script/media/MediaEmbeds.js, app/script/media/MediaRepository.js, app/script/media/MediaStreamHandler.js, app/script/properties/PropertiesRepository.js, app/script/search/SearchRepository.js, app/script/search/SearchService.js, app/script/system_notification/SystemNotificationRepository.js, app/script/telemetry/calling/CallTelemetry.js, app/script/telemetry/calling/FlowTelemetry.js, app/script/tracking/EventTrackingRepository.js
In JSDoc 3 (and TypeScript definitions) the common practice is to use types with lowercase (like `number` and `string`). The only exception is `Object`. 
As a rule of thumb, use lowercase for [primitives](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) and uppercase for objects and object equivalents.
You can also follow along the issue on this topic here: https://github.com/jsdoc3/jsdoc3.github.com/issues/149
=> Enforce valid JSDoc 3 types

app/script/view_model/ConversationInputEmojiViewModel.js
1. `remove_emoji_list` is executed multiple times on click, even if emoji popup is closed.
This happens because `this.remove_emoji_list.bind(this)` creates a new function every time, and `window.removeEventListener('click', this.bound_remove_emoji_list)` is trying to unassign a different function and silently fails to do so. The fix is to create a bound function and use it to assign and unassign a click-listener, so that `addEventListener` and `removeEventListener` are operating on exactly the same function.
2. Unable to fix typo while typing emoji name
Previously if you entered a typo (like `winn`), emoji popup was closed, but as soon as you removed the second `n` it reappeared with suggestions like `wink`. Now it doesn't reappear, so you have to remove everything and start from scratch. …
=> Fix some recent bugs with emoji autocomplete

app/script/util/keycode.js, app/script/view_model/ConversationInputEmojiViewModel.js, app/script/view_model/ConversationInputViewModel.coffee
The code is based on #1139, do not spend time reviewing the code until that one is merged.
------------
@bennyn this is what you wanted 🎉 
I don't know if you want to keep this list short or to make it as extensive as possible (in which case we need to think about potential false positives, where users actually didn't want the replacement). 
So to start with something, I made a simple short list which covers my personal needs. 
Do you have any additions / adjustments?
- `:)` => 🙂
- `:(` => 🙁
- `:D` => 😄
- `;)` => 😉
- `:*` => 😘
- `:P` => 😛
- `;P` => 😜
- `:/` => 😕
-----
One thing to keep in mind. The replacement list must only contain capital letters after colon, otherwise it would prevent user from searching an emoji. Better shown with a gif:
=> Emoji inline replacement

app/script/util/StringUtil.js
Since the spread operator splits the string into symbols this should give the expected result for all kind of unicode strings.
`z.util.StringUtil.get_first_character("🤔") === "🤔"`
=> Use array spread to get first character

app/script/components/list/conversationListCell.js, app/script/user/UserService.js
Since in case of a connect request the actual user is later applied to the participating_user_ets, the component would render with user undefined and never rerender. So for this case we check if the user is present.
=> Only render avatar if user is present

app/style/common/variables.less
This is a follow-up on what we discussed in Linux Feedback Group. With the current order of fonts, when a user doesn't have either of `BlinkMacSystemFont, -apple-system, Helvetica Neue`, the `emoji` font is attempted to be used to render all text. In particular, this makes it render space character as a zero-width space, like so:
Defining the emoji font as the very last seems to solve the issue.
=> Use emoji font only after text fonts

app/style/content/conversation/conversation-input.less
This is a funny bug. Apparently the `width` of the emoji icon column in the popup is too narrow, and when that happens the "complex" emojis (those that consist of 2+ unicode characters) are rendered as 2+ separate emojis.
Look at the gif:
The fix is simple: to let the column expand and consume however much space it requires to render emojis, while preserving the `40px` "real" width.
-------
Before:
After: 
------
P.S. This does not fix #1267, that one is still a valid bug.
=> Fix "complex" emoji display in popup

app/script/view_model/ConversationInputEmojiViewModel.js
One more addition for complex emojis besides #1277 and #1282.
Code assumed that emoji always consists of one character, but as I now know, this is not correct.
Before:
After:
---------------
Still not perfect, you see extra wide spaces and generally Chrome treats emojis as separate characters. I know why this happens, but I need to speak to EmojiOne maintainer first, he might assist creating a generic solution, not specific only for Wire.
> 🏌️‍♀️ is really 🏌️ and ♀️
> :family_man_boy_boy:  is really 👨, 👦 and 👦
=> Fix cursor position after inserting complex emoji

app/script/team/TeamRepository.js
* On `team.create` we now receive the data of the created team, so no extra request to backend needed.
* On `member_join` you didn't get the list of members immediately. Fixed.
* Fixed wrong error message.
=> on_member_join fix + on_create simplification

.travis.yml, bin/deployment_notification.js
Our Webapp Release Bot always created a new identity when posting a deployment notification. This is an attempt to have a sticky identity for our release bot.
=> Release bot keeps its identity

app/script/view_model/content/CollectionDetailsViewModel.js
Fixes a regression from the es6 migration: https://github.com/wireapp/wire-webapp/pull/1235/files#diff-01ce0e6da5f969dcb1bfd096ff6d4f3eL73
=> Show proper collection date headers (WEBAPP-4035)

app/script/main/app.js, app/script/view_model/AuthViewModel.js
- pinned tabs in Firefox preserve the session and do not call onunload, when closing the browser
- thus the session cookie was never cleared, using an expiring cookie and onunberforeunload seems to be the better approach
Fixes #1440
=> fix: Use expiring cookie for multiple tabs check

app/script/util/Environment.js, test/unit_tests/util/EnvironmentSpec.js
There is no need to set the electron version using the wrapper since it can be obtained from the user agent. For sake of testability i create a helper function that is exposed under 'z.util.Environment._electron_version'
=> refactor: obtain electron version from user agent

app/script/ui/Shortcut.js
Relates to https://github.com/wireapp/wire-desktop/pull/779
=> revert: Change shortcut to access start UI (from #1392)

app/script/conversation/ConversationRepository.js
Thanks to @daehn we can go ahead and implement and improvement to decrease the number of messages to encrypt/decrypt. If you have not received your client for a long time, we currently send delivery confirmations for every individual message received. While there are other optimizations we could do down the road, we opt for the simple threshold of x days (currently 7) to check whether a confirmation should be send.
=> feat: Send confirmations only for messages received in last 7 days

app/script/conversation/ConversationRepository.js
Object.entries() is only supported on Chrome 54 and up
=> fix: Remove dependency on Object.entries (WEBAPP-4267)

app/style/components/user-avatar.less, app/style/content/conversation/message-list.less
Prevent a selection start in message timestamps and avatars. Chrome currently does allow it to be part of the selection when you start before the blocked section. This should be aligned with the CSS spec at some point.
=> fix: Set user-select to none for certain message parts

package.json
=> chore: Bump grunt-contrib-uglify to version 'harmony-v2.8.22'

bower.json
=> chore: Bump generic-mesage-proto to version '1.19.0'

grunt/config/uglify.js, package.json
Based on version '3.0.1'
Using uglifyjs2 'harmony-v3.0.28'
=> chore: Bump grunt-contrib-uglify to version 'harmony-v3.0.28'

karma.conf.js
The `ChromeHeadless` launcher became a default in [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher/tree/v2.2.0#available-browsers) and therefore doesn't need a custom configuration anymore.
=> chore: Chrome custom launcher cleanup

app/script/lifecycle/UpdateSource.js
Needed until https://github.com/wireapp/wire-desktop/pull/964 has reached most production users
=> fix: Expose z.announce.UPDATE_SOURCE for backwards compatibility

app/script/view_model/ConversationInputEmojiViewModel.js
This addresses two issues in the current design:
**Emoji popup would open if you type `this:1`**
Previous
Now
**Word boundary is respected resulting earlier invalid match dismissal**
Previous
Now
=> fix: Trigger emoji popup after word boundary only (WEBAPP-4327)

app/style/common/variables.less
According to [wiki](https://en.wikipedia.org/wiki/Segoe#Variations), `Segoe UI Symbol` was first added in Windows 7. According to @fichtennadel in #1733, there is also a `Segoe UI Emoji` on Windows 7. So apparently they both exist since Windows 7.
Further experiments in #1733 show that:
1. Simply defining `Segoe UI Symbol` makes it take precedence over `Segoe UI Emoji`, rendering emojis in black and white (in Firefox).
2. Chrome doesn't seem to support `Segoe UI Emoji`, but removing `Segoe UI Symbol` doesn't have any effect, the emojis are still rendered with `Segoe UI Symbol`.
Therefore, it seems safe to remove `Segoe UI Symbol` from the list. Would be nice if someone with a Windows 7 could actually test this PR before merging.
/cc @fichtennadel
=> Remove "Segoe UI Symbol" from the list of emoji fonts

app/script/auth/AuthService.js
Only a cleanup. This parameter was introduced in the scope of https://github.com/wearezeta/backend-issues/issues/350 and is no longer necessary nor supported.
=> challenge_cookie parameter is no longer necessary

.eslintrc.yaml
To avoid duplication since they are already there: https://github.com/wireapp/wire-webapp/blob/dev/.prettierrc.yaml
=> cleaup: Remove Prettier rules from eslint

app/script/view_model/bindings/CommonBindings.js
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9551546/
=> fix: File constructor not implemented in MS Edge (WEBAPP-3471)

app/script/auth/configureWrapper.js, app/script/auth/main.js
Opted for doing this in code instead of html as it adds another layer of protection. If the html loads but the js file fails, we will still have a proper check that would trigger a reload incase it is not there.
=> feat: Expose wire in global namespace for wrapper check

app/script/auth/util/RuntimeUtil.js, app/script/util/Environment.js
1. In `app/script/util/Environment.js` we are using `window.platform` and `navigator.platform`. To prevent confusion between these two I prefixed them (either with `window` or with `navigator`).
2. I replaced some `navigator.platform` calls in favor of `window.platform` because `window.platform` is defined by [platform.js](https://github.com/bestiejs/platform.js) and platform.js is a superset of `navigator`, so there is no need to keep the pure `navigator`.
3. I made `RuntimeUtil.js` independant of `app/script/util/Environment.js` because on the long run `RuntimeUtil.js` will replace `app/script/util/Environment.js` (when moving fully to React). The short-term benefit is, that testing React components becomes much easier because the `RuntimeUtil.js` imports only …
=> refactor: Using platform module where possible

app/script/auth/page/Index.js, app/script/auth/util/urlUtil.js, app/script/view_model/AuthViewModel.js
Every page navigation on the wrapper will reset the hash to `#login`
As the navigation from the react based index page to `#register` breaks due to this and the user ends up on the login form instead we are repurposing name to mitigate the situation.
=> fix: Enable personal account creation from wrapper (WEBAPP-4522)

app/script/auth/page/Index.js, app/script/auth/page/Verify.js
Adds another workaround on top of the workaround for the desktop application test framework. The former workaround broke the navigation in Firefox.
=> fix: Make login link clickable in Firefox again

app/script/auth/util/urlUtil.js
From #2037, went missing in conflict resolution during the reverse merge.
=> fix: Remove undefined match from searchparams

app/script/components/fullSearch.js
Fix regression introduced by https://github.com/wireapp/wire-webapp/pull/2273/files#diff-db6327a5050e237a103a5712439d6d46R145
=> fix: Show full text match count only when > 1 (WEBAPP-4637)

app/script/util/util.js
https://stackoverflow.com/questions/13972385/invalidstateerror-while-opening-indexeddb-in-firefox
=> fix: Disallow FF error to escape try/catch

app/script/cryptography/CryptographyRepository.js
`DecryptError.InvalidMessage` always had error code "2" (Unknown decryption error). It now uses error code "213" which makes clear that the error is based on a encryption error from the sender side.
=> fix: Specifying decryption error 213

app/script/conversation/ConversationStateHandler.js, app/script/entity/Conversation.js, app/script/view_model/list/StartUIViewModel.js, app/script/view_model/panel/ConversationDetailsViewModel.js, app/script/view_model/panel/GuestOptionsViewModel.js
The guest options feature should not only be linked to the fact that a conversation is a team conversation but also whether you are a guest in that particular conversation.
=> fix: Hide guest options for guest conversations

app/script/localization/Localizer.js
Specially for greek when you changing the text to uppercase with CSS it renders it wrong if the languages is not set.
Wrong:
Correct:
https://jsbin.com/zobisuziso/1/edit?html,css,output
=> fix: Set the correct lang in <html>

app/script/entity/Conversation.js
When reading a message, the unread count is updated but not persisted in db
=> fix: unread messages count update (WEBAPP-5038)

app/script/calling/CallingRepository.js
As pointed out by @infotexture we were using the title strings for the modal messages as well.
=> fix: Use expected strings for second call modal

.travis.yml
After the api-client was fixed in https://github.com/wireapp/wire-web-packages/pull/590, we can revert the downgrade.
This reverts commit 382b250126a5b5316fbdc65f15612287eafa45f5.
=> chore: Upgrade "travis-bot" to latest version

app/script/calling/CallingRepository.js, app/script/entity/Conversation.js, app/script/media/MediaStreamHandler.js
Two small fixes here:
- do not show the `join` button when the group call is picked up from another device
- actually release the mediaStream when the call is picked up somewhere else
=> fix: release media streams when call is picked up from another device

app/script/conversation/ConversationRepository.js
While we are changing the calling UI logic, this ensures a more reliable way to leave the app as a temporary guest. Previously this would fail if there was an active call.
=> fix: Leave guestroom during call

app/script/calling/CallingRepository.js, app/script/calling/entities/CallEntity.js, app/script/telemetry/calling/CallTelemetry.js, app/script/tracking/Helpers.js
@gregor this is a WIP, but most of the properties are done.
Here is the general state:
`calling.initiated_call` :heavy_check_mark: 
`calling.joined_call`  :heavy_check_mark: 
`calling.established_call` :heavy_check_mark: 
`calling.received_call` :heavy_check_mark: 
`calling.ended_call` :heavy_check_mark: 
~~for the `joined_call`, I added a property on the `callEntity` with the media type used when the call is created (so that it's immutable, and we are garantied we cannot mess with the value).~~
~~The side effect is that, if you wait for the `timeout` before picking up and then join (with audio), the call would have been created with the `video` property to `true` (I guess the call is not destroyed between the timeout and the join action).~~
~~For the `ended_call` we used to track …
=> feat: update calling tracking (WEBAPP-4991)

app/script/calling/entities/FlowEntity.js, app/script/media/MediaElementHandler.js, app/script/media/MediaStreamHandler.js, app/script/media/MediaStreamInfo.js, test/unit_tests/media/MediaStreamHandlerSpec.js
Fixes an issue (on Firefox) where the stream tracks are not released when switching video devices during the call and hanging up
=> fix: track-wise local media stream tracks replacement

app/script/tracking/EventTrackingRepository.js, package.json, test/unit_tests/tracking/EventTrackingRepositorySpec.js, yarn.lock
Raygun finally added unhandled Promise rejection handling to their feature set. We can update the dependency and remove our code and tests.
=> chore: Update raygun4js to version 2.10.0

app/script/localization/webapp.js
Since the number of participants shown in the conversation does not include the current user, we need to change this copy to prevent confusion when the conversation shows “4 people” and the Video Call icon is not available.
=> Clarify GVC limitation

package.json
Most of our projects have a `yarn dist` goal. It's very handy if you just want to compile code before running the tests. To streamline our projects, I also added `yarn dist` to the webapp. 
It offers us the following possiblity:
```bash
yarn dist
grunt test_run:util/TimeUtil
```
In the long run the idea is to execute individual tests just by working with Jasmine's `fdescribe` and `fit`. Then a test run with the latest code will be as simple as this:
```bash
yarn dist
yarn test
```
=> chore: Add "yarn dist" script

app/script/localization/webapp.js
These headlines should use the same verb form as the others in the app, and the guests message should be aligned to use the same copy as the mobile clients.
=> Fix verb form in headlines & align guests message

app/page/template/partials/template-message.htm
Applicability to timer update system message still needs to be confirmed with design.
=> fix: Icon color of rename and timer update system messages (WEBAPP-5224)

app/script/auth/AuthService.js
Context:
When trying to get an access token on the server, if the server replies with a forbidden code, there is no need to retry. 
Previously, the app would resend a request, now it just stops
=> fix: Stops access token fetching attempt if the request is forbidden

app/page/template/panel/add-participants.htm, app/script/event/WebApp.js, app/script/view_model/MainViewModel.js, app/script/view_model/PanelViewModel.js, app/script/view_model/content/MessageListViewModel.js, app/script/view_model/content/TitleBarViewModel.js, app/script/view_model/panel/BasePanelViewModel.js, app/script/view_model/panel/ConversationDetailsViewModel.js, app/script/view_model/panel/ConversationParticipantsViewModel.js, app/script/view_model/panel/GroupParticipantServiceViewModel.js, app/script/view_model/panel/GroupParticipantUserViewModel.js, app/script/view_model/panel/ParticipantDevicesViewModel.js
Mainly an attempt to remove the circular dependency between the `switchState` and the `_openPanel` method and to clarify the api of the `PanelViewModel`
=> refactor: simplify PanelViewModel api (WEBAPP-5248, WEBAPP-5249)

app/script/conversation/ConversationRepository.js, app/script/entity/Conversation.js, app/script/event/EventRepository.js, test/unit_tests/entity/ConversationSpec.js, test/unit_tests/event/EventRepositorySpec.js
Quick explanation:
- the EventRepository merges the event with the previous text message already in DB (if found)
- the EventRepository save this "new" event in DB (so there are 2 duplicates in DB right now)
- the ConversationRepo takes the relay and delete the previous event (supposedly the text event).
Work well in most of the cases, but will actually delete the `linkPreview` event if there is no `textEvent` already in DB (which could occur if, say, a client send a `linkPreviewEvent` before the actual `textEvent`)
- the EventRepository merges the event with the previous text message already in DB (if found) ;
- the EventRepository **updates** the event in DB if found ;
- the ConversationRepo is no more responsible for touching the DB (deleting the previous event).
=> fix: Explicitely update event in DB when receiving a link preview message (WEBAPP-4366)

app/script/calling/entities/FlowEntity.js
I am still seeing cases of the MediaStream being undefined when we start negotiating a call. Added a proper error in order to get to the bottom of this.
=> fix: Throw error if stream is missing

app/script/conversation/EventMapper.js
From the logs it seems like we have 'conversation.member-update' events in the database. Those should not be there. Let's figure out where they stem from.
=>  chore: Improve error for failed event mapping

app/script/ui/Shortcut.js
This shortcut is not supposed to be there anymore.
Fixes a conflict between the `mute call` and the `mute conversation` shortcuts.
=> fix: remove deprecated mute call shortcut (WEBAPP-4210)

app/script/event/EventRepository.js, app/script/util/DebugUtil.js, test/unit_tests/event/EventRepositorySpec.js
Events there did not pass validation because they are being ignored (`conversation.is-typing`) or because of outdated timestamps were no longer properly handled and resulted in lots of errors in the console.
=> fix: Handle events that fail validation

app/script/conversation/ConversationRepository.js, app/script/entity/Conversation.js, app/script/event/EventRepository.js
Ok so, this is a first step toward freeing the `ConversationRepository` from persisting events in the DB.
Here I migrated the `edit message` functionality. Now the `EventRepository` is responsible for checking if there are duplicates in the DB and updates them accordingly. 
This avoids multiple writes to the DB when an event arrives. Previously the `EventRepo` would save most of the event, and, eventually, the `ConversationRepo` would remove them from there (which triggered the bug fixed here https://github.com/wireapp/wire-webapp/pull/4079).
There is still one place where the `ConversationRepository` stores events, for the `asset` handling. 
I might need the help of @gregor on this one, since I am not sure how to reproduce the case where it happens. …
=>  refactor: move DB updates from ConversationRepository to the EventRepository

app/script/event/EventRepository.js, test/unit_tests/event/EventRepositorySpec.js
Here is a little graph of the workflow when a new event arrives in the event repository handler.
=> fix: Differentiate link preview updates and edit messages (WEBAPP-5300)

app/script/util/ArrayUtil.js
Uploading huge MP3 files (~80 MB) produce heavy load on the browser and can crash the render process because of an inperformant array chunking implementation. 
The implementation of this PR solves the performance issue and has the benefit of using [array.slice](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) which doesn't modify the source array. Because of the nature of "array.splice" we don't need to create a `temporaryArray` anymore before starting the chunking process. It also uses a for-loop with a cached length which brings an additional 3-6% of performance.
For the future we should consider enforcing for-loops with cached lengths because it's easy to implement and brings extra bits of performance. There are ESLint plugins like …
=> refactor: Improve performance of "z.util.ArrayUtil.chunk" (WEBAPP-5336)

app/script/util/ArrayUtil.js, app/script/util/Crypto.js, test/unit_tests/util/ArrayUtilSpec.js
In our code we use `z.util.ArrayUtil.getNextItem` only in `get_next_conversation` of the `ConversationRepository` class. There we use it without a third parameter (the filter option), so we can simplify the `getNextItem` util by removing it's filter functionality.
=> refactor: Remove filter option from "ArrayUtil.getNextItem"

app/script/conversation/ConversationEphemeralHandler.js, app/script/conversation/ConversationRepository.js, app/script/event/EventRepository.js, app/script/event/EventService.js, test/unit_tests/event/EventRepositorySpec.js, test/unit_tests/event/EventServiceCommon.js
The idea is to have a little dumber `EventService`. 
To do that I removed the knowledge of the `Message` entity class from the API of the `EventService`. 
My view on this would be that `Entities` should stay on the application level (view + repositories) and low level classes should not be aware of those classes (if possible of course)
Here is the current state of the `EventService` API
=> refactor: Remove traces of the Message entity in the EventService

app/page/template/panel/add-participants.htm, app/page/template/panel/conversation-participants.htm
This *might* fix the issue of occasional flicker when opening the side panel by clicking on show more.
I was not able to reproduce it reliably, but suspect it to be a timing issue/race condition.
By extending the time this should not happen anymore.
=> fix: longer focusDelay to avoid flicker (WEBAPP-5387)

app/script/localization/webapp.js
The “Full house” dialog title that appears when a conversation reaches the maximum number of participants is a remnant of our earlier informal tone.
This should be revised to adapt to our recent B2B tone.
See https://github.com/wireapp/copywriting/issues/37.
=> fix: Change “Full house” dialog title

app/script/calling/SDPMapper.js
- adds a workaround for AVS incompatibility when Firefox sends 0 as ports
- Removes obsolete SDP rewrite; no clients in the wild still use AVS 3.3.x
=> fix: Set active ports on outgoing SDP for Firefox (WEBAPP-5322)

app/script/media/MediaStreamHandler.js
Because we didn't give a precise type when replacing the content of the media stream, we would fallback to a replacement of `audio/video` BUT we would feed in only a `video` track.
Which means the `audio` track will be released but not replaced, resulting in audio loss on the receiver side
=> fix: Only release media stream that are being replaced (WEBAPP-5419)

app/script/auth/main.js
Ok, hold on to your socks, this is a tough one.
On the webapp side, we need (Dexie needs to be precise) both `setImmediate` and `clearImmediate`. 
Dexies uses a polyfill to actually declare both of them if the browser doesn't have them.
So in the case of a browser `setImmediate` AND `clearImmediate` are not defined so Dexie's polyfill triggers and define both
In the case of the desktop app, we actually set ONLY `setImmediate` in the preload script (see https://github.com/wireapp/wire-desktop/blob/796ab90f104861697d0cd662b63b6c5836242d68/electron/renderer/static/webview-preload.js#L195). 
Which means that when Dexie loads its polyfill, `setImmediate` is defined (but not `clearImmediate`) so the polyfill doesn't do anything and we end up in the bug we current have on the login page.
This …
=> fix: Force loading the polyfills for setImmediate and clearImmediate (WEBAPP-5440)

app/page/template/_dist/app.htm, app/script/calling/entities/FlowEntity.js, app/script/util/PeerConnectionUtil.js, test/unit_tests/util/PeerConnectionUtilSpec.js
Previous behavior:
- waiting 5 seconds for ICE candidate gathering
- after 5 seconds, if the SDP contains relays ICE candidate we send the SDP else we wait 1 second and replay this timeout as long as we don't have relay candidates
New behavior:
- we only wait 1 second for the ICE candidate gathering (and loop until we have a bunch of relays candidate in the SDP).
This PR also adds a log with the types of candidates we have gathered
=> refactor: Simplify the sdp sending timeout protocol

package.json, yarn.lock
Reverts wireapp/wire-webapp#4599
=> build(deps-dev): Revert "bump uglifyjs-webpack-plugin from 1.3.0 to 2.0.1"

app/script/conversation/ConversationCellState.js
This PR will
* correct the priority order of icons shown next to the conversation title in the conversation list
* correct the priority order of the subtitle string in the conversation list
Correct order:
1. Missed call
2. Ping
3. Normal message
=> fix: Priortize types in secondary line alert state

app/script/conversation/ConversationCellState.js
This PR will
* always check if a message is of type "content" before checking if it has self mentions.
=> fix: Add missing content type checks on incoming messages

app/script/conversation/ConversationCellState.js
We are changing the cases for the summary to show:
- the conversation is muted
_OR_
- the conversation contains one mention of the self user and at least one other text message
_OR_
- the conversation contains at least 2 mentions of the self user
_OR_
- the conversation contains at least 1 missed call or 1 ping
=> feat: Improve secondary line behavior related to mentions (WEBAPP-5478, WEBAPP-5484)

app/script/message/MentionEntity.js
When constructing `z.message.MentionEntity`, its `userEntity` observable is `undefined` and can break the access on `this.userEntity().is_me`. 
That's why I added the check for `this.userEntity()`.
=> fix: Mentioning the same user twice (WEBAPP-5483)

app/script/view_model/content/InputBarViewModel.js
The `isOverValidMentionString` test now matches mentions which **don't include whitespaces** (`\S`). That's the same pattern which iOS and Android use and it allows us to look for mentions that include umlauts, accented characters and/or chinese characters.
=> fix: Close mention suggestions on whitespace character (WEBAPP-5487)

app/script/conversation/ConversationRepository.js, app/script/message/MentionEntity.js
This changes a bit the `MentionEntity` API.
It doesn't need a full userEntity now and has a new method that set who is going to read the message
It also crash if we ask it if it's a self mention while the reader is not set
=> fix: Do no fail silently if it is not possible to determine if mention is self mention (WEBAPP-5496)

app/page/template/partials/template-message.htm, app/script/conversation/ConversationCellState.js, app/script/conversation/ConversationRepository.js, app/script/entity/Conversation.js, app/script/entity/message/ContentMessage.js, app/script/entity/message/Text.js, app/script/main/app.js, app/script/message/MentionEntity.js, app/script/notification/NotificationRepository.js, app/script/util/util.js, test/api/TestFactory.js, test/unit_tests/util/UtilSpec.js
We now explicitly pass the selfUserId when we need to compare against it and not rely on previous piece of code to have set it.
This will allow us to avoid running into temporal coupling.
=> refactor: Move to a stateless MentionEntity (WEBAPP-5516)

app/script/view_model/content/EmojiInputViewModel.js
Instead of querying the DOM on every single keydown event to know if the emojipicker is there, we just keep track of the visibility of the emojipicker and check that boolean during keydowns.
This class will need refactoring at some point and a few perf optimization can be done here
=> fix: Avoid querying the DOM on every keydown

package.json
`husky` 1.0.0 has changed the way of adding precommit hooks. See https://github.com/typicode/husky#upgrading-from-014.
Follow-up to https://github.com/wireapp/wire-web-packages/pull/1162
=> fix: Add new husky precommit hook

app/page/template/content/conversation/input-bar.htm, app/script/view_model/bindings/CommonBindings.js, app/style/content/conversation/input-bar.less
This will be a game changer in term of performance.
Resizing textarea to its content is pretty expensive because the way to do that is:
- resize the textarea to 0 ;
- compute the scrollHeight (trigger a complete reflow) ;
- set the new size to the computed scrollHeight (will trigger another reflow) ;
Because the visible content is displayed by a div, which do not need any reflow to know their size, the idea is to use this div to know how to size the textarea:
- when text change, we read the height of the div (basically a free operation) ;
- if the size is different than the size of the textarea, we set the textarea with the new size.
So now we trigger a reflow (and some costy operations) **only** when a new line is added to the textarea
=> fix: Use the shadow input as the ground truth for textarea height

app/script/extension/GiphyRepository.js, app/script/extension/GiphyService.js
Calling the giphy proxy with
```ts
{
q: 'cat',
sort: 'recent'
}
```
returns results since there are new cat GIFs every day, while
```ts
{
q: 'elon musk weed',
sort: 'recent'
}
```
returns no results since usually there are no recent GIFs for Elon Musk smoking weed.
I suggest we don't randomly switch the sorting so we never have an empty giphy selection window.
Related: https://github.com/wireapp/wire-desktop/issues/1748
=> fix: Keep giphy sorting option

app/page/template/list/start-ui.htm, app/page/template/modal/group-creation.htm, app/page/template/panel/add-participants.htm, app/page/template/panel/conversation-details.htm, app/page/template/panel/conversation-participants.htm, app/script/components/userList.js, app/script/search/SearchRepository.js, app/script/team/TeamRepository.js, app/script/user/UserRepository.js, app/script/util/StringUtil.js, app/script/view_model/content/GroupCreationViewModel.js, app/script/view_model/list/StartUIViewModel.js, app/script/view_model/panel/AddParticipantsViewModel.js, app/script/view_model/panel/ConversationDetailsViewModel.js, app/script/view_model/panel/ConversationParticipantsViewModel.js, test/unit_tests/search/SearchRepositorySpec.js, test/unit_tests/user/UserRepositorySpec.js
Main changes:
- we can match handles with patterns that are in between the handle (`ichel` matches `michel`)
- the results are now sorted with the following priorities
- first name matches from the start
- last name matches from the start
- first name matches in between
- last name matches in between
Here are a few examples that give different results
=> feat: Use the local user search algorithm everywhere (WEBAPP-5475)

app/script/conversation/ConversationCellState.js, test/unit_tests/conversation/ConversationCellStateSpec.js
These are not exhaustive tests.
It covers the basic scenarios for 1:1 conversations but is missing a lot of combinations.
=> test: Bootstrap ConversationCellState tests

app/script/localization/webapp.js
This better supports relative timestamps like “just now”.
=> chore: Remove “on” from device activation timestamp string

app/script/assets/AssetRemoteData.js
I believe service worker does cache the images. But, at app's load time, we send a bunch of requests to the server (could be a lot), and I don't think service worker helps on this.... (?)
=> feat: Add caching mechanism to load image once

app/script/tracking/EventTrackingRepository.js, test/unit_tests/tracking/EventTrackingRepositorySpec.js
PR looks more complex than it is. The underlying issue was that we called `detach()` on Raygun without ever calling `attach()` in case the domain was blocked from analytics. Due to the difference in `init()` and `updatePrivacyPreference()` in the former Raygun was not attached while later when re-enabling Raygun after toggling the setting it would be attached. Thus https://github.com/MindscapeHQ/raygun4js/issues/302 would only occur when first initiating Rayung on a domain where reporting was disabled.
I aligned the enabling/disabling behavior for a more structured approach.
=> fix: Attach error reporting despite URL param (WEBAPP-5604)

app/script/auth/module/action/ClientAction.ts
Previously we checked for the presence of the password when creating a client on registration/login in order to detect if the client will be the first one of the user. This worked due to the fact that a password is only required for subsequent client creations.
With the introduction of SSO users, client creation will never require a password for this kind of users. With that the simple check for the password is not sufficient anymore. Thus an additional request to the backend is needed since we never know if the user will create an additional or a first client. 
This might not be necessary if only considering client handling within the webapp but account creations on team-settings, which happen without creating any clients, lead to the problem that at the point of a login on the webapp …
=> fix: Check for first client on client creation (WEBAPP-5643)

app/script/entity/message/Message.js, app/script/view_model/content/InputBarViewModel.js
As a follow-up to https://github.com/wireapp/wire-webapp/pull/5015#discussion_r229745265 @atomrc and I agreed to remove the `isEditing` state from the message entity (it was not used in any conditions anyway).
=> chore: Remove isEditing state from message entity

app/script/links/LinkPreviewRepository.js, test/unit_tests/links/LinkPreviewRepositorySpec.js
Our wrappers can generate link previews. To make this work, the wrapper exposes an open graph library to the `window.openGraph` namespace. This library is then being used from the webapp code when calling `wire.app.repository.links.getLinkPreview` which calls the underlying `_fetchOpenGraphData` function.
In some cases (for example when entering an invalid URI), the `window.openGraph` library (which uses a Promise interface) throws an error but we never catched that error inside of `_fetchOpenGraphData`. Now we do.
This addresses the following crash report:
- https://app.raygun.com/crashreporting/8785p7/errors/3014612384
=> fix: Catch invalid URIs on link preview generation (WEBAPP-5661)

app/page/template/content/conversation/message-list.htm, app/script/view_model/content/MessageListViewModel.js
This PR changes the scroll behavior quite a bit.
The basic idea is:
- if the container is not scrollable (the content is smaller than the container), then the `mousewheel` event handles loading the messages depending on the direction the user wants to scroll.
- if the container is scrollable, we just load messages depending on whether we hit the top of the bottom of the message list
=> fix: Improve extra messages loading behavior (WEBAPP-5621)

app/script/message/MessageHasher.js, test/unit_tests/message/MessageHasherSpec.js
Internally we use milliseconds for the event date, but all teams agreed to use seconds for hashing.
=> runfix: Convert message timestamp to seconds before hashing

app/script/event/preprocessor/QuotedMessageMiddleware.js
When receiving an `edit` message for a non-existing original message an error was thrown because of a wrong return value. The return value was corrected and the correct warning fallback will appear instead.
=> runfix: Return original event if no quote found

app/page/template/_dist/app.htm, app/page/template/_dist/component.htm, app/script/ui/Modal.js, app/script/view_model/AuthViewModel.js, app/script/view_model/ImageDetailViewViewModel.js, app/script/view_model/ModalsViewModel.js, app/script/view_model/content/GiphyViewModel.js, app/script/view_model/content/GroupCreationViewModel.js, app/style/auth/auth.less, app/style/common/modal.less, app/style/main.less, package.json, yarn.lock
With this PR the external dependency to the modal module is removed.
It is now written is es6 rather than coffee script and introduces an additional callback for the end of the hiding transition as the `transitionend` event might not fire under rare circumstances.
=> fix: Modals sometimes wouldn't be removed from view (WEBAPP-5709)

app/script/media/MediaEmbeds.js, test/unit_tests/media/MediaEmbedsSpec.js
The old regex can't match playlists from users with usernames including dots or special characters (e.g. `user.name`).
Old regex: https://regex101.com/r/8HQneV/1
New regex: https://regex101.com/r/KyQT67/3
=> fix: Spotify playlist links

app/script/links/LinkPreviewBlackList.js, app/script/media/MediaEmbeds.js, test/unit_tests/links/LinkPreviewBlackListSpec.js, test/unit_tests/links/LinkPreviewRepositorySpec.js, test/unit_tests/media/MediaEmbedsSpec.js
This PR will
* add link preview rendering for static SoundCloud, YouTube, Vimeo and Spotify pages
* allow embedding all vimeo channel videos, not only from staff picks
* close #529
=> fix: Link embedding

app/script/links/LinkPreviewHelpers.js, test/unit_tests/links/LinkPreviewHelpersSpec.js
Follow-up to https://github.com/wireapp/wire-webapp/pull/5180.
<details closed>
<summary>Regex comparison</summary>
---
**Old regex**
---
**New regex**
</details>
=> runfix: Don't create link previews for links in code blocks

app/script/main/app.js
Current wrappers (v3.4 and below) rely on the following namespaces:
- window.wire.app.service.connectGoogle._authenticate
- window.wire.app.service.connect_google._authenticate
We removed them (https://github.com/wireapp/wire-webapp/pull/5198) but this requires to have new wrappers out because that have this change included: https://github.com/wireapp/wire-desktop/pull/1938
Until then we still need to stick around with the namespace exposure so I am bringing these back.
=> fix: Add backward compatibility for wire-desktop v3.4

app/script/conversation/ConversationRepository.js
In the first iteration we will test this by sending read receipts every time.
=> feat: Always send a read receipt for new messages (WEBAPP-5760)

app/script/auth/main.tsx
This can be merged once this fix https://github.com/wireapp/wire-desktop/pull/1715 is released and adopted
=> fix: clear unnecessary forced polyfill for setImmediate (WEBAPP-5442)

app/script/components/message.js, app/script/localization/webapp.js
This will now always be shown. We need to update the condition as soon as our conversations know about the receipt settings.
=> feat: Show system message after creation with read receipt turned on (WEBAPP-5759)

app/page/template/panel/conversation-details.htm, app/script/entity/Conversation.js, app/script/view_model/panel/ConversationDetailsViewModel.js
With this PR the read receipts system message and read receipts conversation setting will only show up when:
- It's a 1:1 conversation
- It's a team conversation
=> fix: Show read receipts setting in team conversations (WEBAPP-5797)

app/script/util/objectUtil.js, test/unit_tests/util/objectUtilSpec.js
We were treating array like object when merging 2 entities. 
Meaning that we would `delete` properties that are in the destination object and not in the source object.
So if we have 2 arrays
destination : [<RemoteAsset>]
source : []
We will end up with 
[undefined] (thus the errors with link previews and assets)
=> runfix: Merge arrays as primitive values when merging two entities (WEBAPP-5853 WEBAPP-5854)

app/script/conversation/ConversationRepository.js, app/script/entity/Conversation.js, test/unit_tests/entity/ConversationSpec.js
Because updates of message already loaded in memory is now made automatically by the DB listener, we don't need to manually replace them in the message list. 
Next step would be to automatically add messages when they are added in the DB (that will remove even more code here).
Next step would be to automatically delete messages when they are deleted in DB. 
When we reach that step, we will have a single place that handles add/update/delete events: The event repository.
=> refactor: Remove unecessary manual updates of messages in message list

app/script/auth/page/Login.tsx
The `catch` clause receives all kinds of errors but from the implementation it thinks that they are all of kind `BackendError` and do have a `label` which is not true. 
So far the TypeScript code assumed that error is of type `any` which we always want to avoid, so I type-casted the errors because I ran into a scenario where I received an error in the `catch` clause which did NOT have a `label` and caused another error because the `default` case of the `switch` block failed when executing `backendError.label.endsWith(errorType)`.
=> fix: Typecasting for incoming login errors

app/script/conversation/ConversationRepository.js, app/script/conversation/EventMapper.js, app/script/entity/Conversation.js, app/script/util/objectUtil.js, test/unit_tests/util/objectUtilSpec.js
The current generic entities merger is powerful but starts to need to many special cases (mainly due to observables being nested and object being shared across multiple entities).
This solution is aware what kind of entity it's merging and can act smart about it.
=> fix: Use a less generic method to replace live message entities

app/script/user/UserRepository.js
We need to subscribe to updates on the `marketingConsent` property but the subscriber has only been added when consent was already given. 
When the user did not give consent from the beginning, then we would also not attach a subscriber on the UI property, so if the user then changes the consent value in the UI, nothing happens. 
This will be fixed with the PR you are currently reviewing. 😺
=> fix: Attach marketing consent subscriber (WEBAPP-5846)

src/script/components/message.js
The idea is to wrap nested observables into a pureComputed to end up with primitive values that knockout will filter by itself
=> fix: Avoid flickering of embed media when liked (WEBAPP-5866)

src/script/auth/module/action/ClientAction.ts
As agreed with @Yserz and @bennyn, we can remove the internal check as it's causing too many problems.
`Environment.ENVIRONMENT.PRODUCTION` will be removed as a next step soon.
=> fix: Remove internal check for wrapper device name

src/script/main/app.js
This PR will
* log the error message immediately behind the info message
* switch to a warning log instead of the info log
---
**Reason**
Currently we see logs like
```json
{
"level": "info",
"message": "z.main.App | 11:08:33.752 | Could not initialize app version '2019.01.24.1302' - Electron 'OS X' '3.4.2872-internal'",
"timestamp": "2019-01-28T10:21:33.752Z"
}
```
but the actual error is not logged.
=> fix: Log error message when init fails

src/script/links/LinkPreviewProtoBuilder.js
Fix for a bug introduced in https://github.com/wireapp/wire-webapp/pull/5598.
=> fix: Use Tweet description as title

src/script/auth/page/SingleSignOn.tsx, src/script/auth/route.ts
This:
- http://localhost:8081/auth/?sso_code=wire-26233198-77f3-4aac-97ad-03de41168ab7#sso
Will become:
- http://localhost:8081/auth/#sso/wire-26233198-77f3-4aac-97ad-03de41168ab7
=> refactor: Use hash instead of URL param for SSO links

test/api/knockoutHelpers.js, test/unit_tests/components/participantAvatarSpec.js, test/unit_tests/components/receiptModeToggleSpec.js
The `instantiateComponent` test helper method doesn't need a "param" parameter now. It deduces the params to give the component automatically from the view model given
=> test: Simplify the method to instantiate components in tests

karma.conf.js, src/script/util/marked.js, src/script/util/util.js, webpack.config.common.js
This will give us the possibility to finally use `async` & `await`, [Object destructuring](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) and many other sweets while shipping for MS Edge 17.
=> chore: Use Babel for complete app

.travis.yml
[Tagging suggestion](https://github.com/wireapp/wire-webapp/releases/new) from GitHub:
> If the tag isn’t meant for production use, add a pre-release version after the version name. Some good pre-release versions might be v0.2-alpha or v5.9-beta.3.
In the long run we would like to name releases like `v1.5.7-staging` but for now we can go with `2019-02-11-staging`.
=> chore: Trigger staging releases based on tags

src/script/calling/entities/FlowEntity.js
As discussed with @jspittka we decided to increase the timeout after which we send the SPD payload (even if no relay candidates have been found).
This will prevent call from simply dropping in really bad networks while keeping a decent amount of waiting time.
=> feat: Increase the ice candidates gathering timeout to 10 seconds

src/script/main/app.js
In our `_logoutOnBackend` function we catch potential logout errors:
```js
.then(() => _logout())
.catch(() => _redirectToLogin());
```
When the signout reason is immediate, then we call `_logout()` without catching it, so I added a catch there too because I ran into a scenario where I had an error during that logout call and where I was not being redirected to the login page:
=> fix: Redirect to login page on logout error

.copyconfigrc.js
`path.join` is not needed as the full path will be resolved by `copy-config`.
=> chore: Remove path.join from copy config

src/script/conversation/ConversationRepository.js, src/script/notification/NotificationRepository.js, src/script/view_model/content/MessageListViewModel.js
As of the Read Receipt feature (https://github.com/wireapp/wire-webapp/pull/5411) we have a mechanism to reliably detect when a message has been read.
This is a perfect opportunity to rethink the way the `last_read_timestamp` of the conversation is handled.
This PR brings the power of the read detection to update the timestamp. Which means we will now update this timestamp live while the user scrolls the message list.
Another benefit of this is that we have a single place where we send the message that synchronizes all the clients.
=> refactor: Centralize handling of conversations' last read timestamp (WEBAPP-5967)

src/script/ui/overlayedObserver.js, test/unit_tests/ui/overlayedObserverSpec.js
The previous implementation needed a DOM modification to actually check for visible elements.
(which means a CSS transition, for example, will not trigger a check and can cause visible elements not to be detected).
The new implementation is based on interval. Probably a bit less efficient but will cover way more cases and will be more scalable in the future
=> runfix: Use interval instead of mutation events to detect overlayed elements (WEBAPP-5970)

src/script/calling/entities/FlowEntity.js, src/script/main/globals.js, src/script/util/PeerConnectionUtil.js, test/unit_tests/util/PeerConnectionUtilSpec.js
Currently when send the SDP only if we have more than 2 ICE candidates (or the timeout has been reached).
As discussed with AVS, it's perfectly fine to send the SDP when we have a single ICE candidate.
=> feat: Allow the SDP to be sent whenever a single relay is found (WEBAPP-5974)

src/script/links/LinkPreviewRepository.js
Introducing an async version of `openGraph()` (https://github.com/wireapp/wire-desktop/pull/2269)
=> refactor: Use openGraphAsync if possible

src/script/conversation/ConversationRepository.js
Currently, if we receive a `join` event, we will check that the sender is already in the conversation participants. If not we will manually add it. But this step is also done by actually parsing the `join` event.
Thus we can filter `join` events that are sent by the actual user joining the conversation.
=> fix: Improve detection of missing members when an event is received (WEBAPP-5975)

.travis.yml
This will create a GitHub release as a draft everytime we create a staging tag or merge to `prod`.
Unfortunately due to https://github.com/travis-ci/dpl/issues/155 it is not possible to automatically fill the description with the changelog but instead a changelog file is attached which needs to be copied into the description field ~~and deleted from the release~~.
=> chore: Add automatic GitHub releases

.travis.yml
I noticed that we were
* setting a commit range when we merge to `prod`, but Travis should have it already
* not setting a commit range when creating a tag, but Travis won't have it either
* always setting a tag with git even if we didn't need to
=> chore: fix automatic GitHub release

src/script/broadcast/BroadcastRepository.js, src/script/config/dependenciesGraph.js, src/script/conversation/ConversationRepository.js, src/script/main/app.js, src/script/message/MessageSender.js, src/script/service/BackendClient.js, src/script/user/UserRepository.js, test/api/TestFactory.js, test/unit_tests/message/MessageSenderSpec.js
This is a first step to factorizing the way we send messages in Wire. 
Right now, we have 2 methods that, basically, have the same logic `ConversationRepository._sendEncryptedMessage` and `BroadcastRepository._sendEncryptedMessage`. 
Harmonizing this will be a long journey of identifying patterns and resolving cyclic dependencies but we will get there.
=> refactor: First step to resolve cyclic dependencies

src/script/util/LoggerUtil.js, test/unit_tests/util/LoggerUtilSpec.js
The first method is polyfilled by `url-search-params-polyfill` but the second method is not
=> fix: Use URLSearchParams class instead of URL().searchParams (WEBAPP-6017)

package.json, src/script/main/app.js, src/script/router/Router.js, test/unit_tests/router/RouterSpec.js, yarn.lock
Ok, this is a very rough draft that enables switching to a conversation by using the `history.replaceState` method.
This PR is mostly to allow the wrapper to make use of that method.
The code will be further refactored in follow up PRs.
=> feat: Bootstrap a router that listens to history.replaceState calls

src/script/router/Router.js, test/unit_tests/router/RouterSpec.js
This will allow the wrapper and the end to end tests to use standard url changes to trigger conversation switching.
From the wrapper, doing `window.location.hash = '/conversation/....';` will trigger the conversation switching
=> feat: Make the router listen to standard hashchange event

src/script/router/Router.js, test/unit_tests/router/RouterSpec.js
This conflicted with Raygun's internals (which is also replacing this method). We don't need that overwrite anymore since the wrapper is going to use the more standard window.location.hash directly
=> runfix: Do not use ovewritten replaceState method (WEBAPP-6028)

src/script/main/app.js, src/script/view_model/content/UserModalViewModel.js
Will allow the top level components to change the hash back to `/` when a user modal is closed (so that it can be reopened later on)
=> runfix: Reset location hash when the user modal has been closed (WEBAPP-6044)

src/script/user/UserRepository.js
When people land on `app.wire.com/#/user/wrongid`  then it's a valid case that we log an error for it but it should be warning since it's not severe.
=> runfix: Warn when a user cannot be found

src/script/main/app.js, src/script/view_model/LoadingViewModel.js, src/script/view_model/MainViewModel.js
In the current state of the app, we instantiate **all** the views of the app at bootstrap time. 
This part of the app's bootstrap is pretty expensive (because it does all the bindings between the view models and the real DOM).
**But** when the app loads the data it needs (conversations, users, crypto...) we just need a single view model (namely the `LoadingViewModel`).
This PR will start loading the data of the app **before** loading all the other views.
=> refactor: Optimize loading view performances

src/script/components/list/conversationListCallingCell.js, src/script/view_model/list/ConversationListViewModel.js
Because I recently delayed the instantiation of all the views to when we actually need them, we were missing the event `NOTIFICATION_HANDLING_STATE` in the `ConversationListViewModel` (this class is instantiated after the event is fired).
Thus we need to explicitly read the value of the handling state when the class is build and then subscribe to changes.
This remove an implicit temporal coupling.
=> runfix: Avoid temporal coupling with the notification_handling_state

src/script/event/WebApp.js, src/script/main/app.js, src/script/main/globals.js, src/script/util/DebugUtil.js, src/script/view_model/ContentViewModel.js, src/script/view_model/MainViewModel.js, src/script/view_model/ThemeViewModel.js, src/script/view_model/content/EmojiInputViewModel.js, src/script/view_model/content/PreferencesAccountViewModel.js, src/script/view_model/content/PreferencesOptionsViewModel.js
This is how the app bootstrapped before:
- setting up repositories
- setting up all the view models
- the properties repository initiate its values and sends an event
- the instantiated view models react to that event
New behavior:
- setting up repo
- properties repo initiate its values
- when view models are initiated, they read the values they need from the properties repo
=> no more temporal coupling (we can initiate the values of the properties repo **before** or **after** the views has been instantiated)
=> runfix: Force perferences linked view model to read the initial values

babel.config.js, package.json, yarn.lock
The latest babel version asks you to add either `core-js@2` or `core-js@3`. 
We saw issues with `core-js@3` (https://github.com/wireapp/wire-web-packages/pull/1717#issuecomment-479007175), so we stick with `core-js@2` for now.
Read more: https://babeljs.io/blog/2019/03/19/7.4.0#core-js-3-7646-https-githubcom-babel-babel-pull-7646
=> refactor: Add polyfills based on usage

package.json, src/script/auth/config.ts, src/script/calling/CallingRepository.js, src/script/conversation/EventBuilder.js, src/script/entity/Conversation.js
This limits importing the full CallingRepository in classes that only need to read config values from it
=> refactor: Extract global app config from the CallingRepository

src/script/auth/page/Login.tsx
=> fix: Margin for the login button in the auth page

src/page/template/content/preferences-av.htm, src/script/media/MediaDevicesHandler.js, src/script/media/MediaStreamHandler.js, src/script/view_model/bindings/VideoCallingBindings.js, src/script/view_model/content/PreferencesAVViewModel.js
Previously, mediaStream were shared accross the preferences page and a potential current call. Which lead to hard-to-find mediaStream leaks (because it's hard to know if you need to release the tracks of the media stream from the call and/or the preference page).
Now, we have discinct workflow for both the page and a call. Which means they are both responsible for cleaning their own mediaStream, but never the media stream of someone else. It makes the dataflow easier to understand and to scale in the future
=> fix: Decorrelate AV Preferences' mediaStream from the one used in a call (WEBAPP-6227)

src/script/view_model/content/PreferencesAVViewModel.js
When a device change occurs we, unconditionally, request a media stream from the user (even when this media stream is not needed anywhere).
=> runfix: Do not request media streams when it is not needed

karma.conf.js
Will allow to run a single test file from the cli regardless of if the test is in `test/unit_tests` directory or in `src/components/**/*.test.ts`.
example:
```
yarn test:app --specs=assets/AssetCrypto
```
=> chore: Enable the --specs flag for *.test.ts files

src/script/conversation/ConversationRepository.js, src/script/main/app.js
At app load time, we update the conversations (fetch the users and make sure everything is there). But since we did not wait for this to be over when loading the app, we would also load those users again when displaying the conversation. 
This resulted in 2 requests being sent in parallel and 2 user entities being created for the same user
=> runfix: Avoid race condition when fetching users (WEBAPP-6282)

src/script/view_model/content/PreferencesAVViewModel.js
This will allow the browser to give the device label when enumerating the devices (see https://stackoverflow.com/a/46659819/2745879)
=> fix: Refresh device list when permission are granted by the user (WEBAPP-6341)

karma.conf.js
Since more and more sources are being build before the tests actually start, Karma eventually think that nothing is happening during the building process thus triggering the noActivityTimeout
=> chore: Increase karma noActivity timeout

src/script/calling/CallingRepository.ts
This allows the code that unarchive conversation to trigger when a call event happens
=> runfix: Fix source of live calling events (WEBAPP-6388)

src/script/team/TeamRepository.js, test/unit_tests/team/TeamRepositorySpec.js
This reverts `TeamRepository.js` from https://github.com/wireapp/wire-webapp/pull/6904 and now returns the data (currently only used for the test).
=> chore: Revert unneded team logo changes

src/script/calling/CallingRepository.ts
This will warn the UI that it doesn't need to ring anymore. Right now it's not detected because the call is removed from the list and KO doesn't warn the UI of this change.
=> runfix: Reset calling state before removing an incoming ringing call (WEBAPP-6407)

src/style/common/mixins.less
The value `1000` was invalid, so I am using `revert` now
=> fix: Replace incorrect CSS perspective property

package.json, yarn.lock
This will enable dependabot to fetch the right version upgrade for @wireapp/avs package
=> chore: use release-5.1 dist-tag for avs dependency

src/script/util/LoggerUtil.js
This could be due to a Firefox regression where, when cookies are not enabled, firefox does not throw an error but instead gives back a null object
=> fix: Safer localStorage access from logger (WEBAPP-6423)

src/script/conversation/ConversationRepository.js, src/script/view_model/ContentViewModel.js
Right now, every error in `showConversation` causes the "conversation not found" modal to appear and is being swallowed then.
To be able to find and fix errors within this function, we will only swallow the `CONVERSATION_NOT_FOUND` error and surface the others. Since the promise inside the function is floating, it should not break the flow of other functions.
=> fix: Display conversation not found modal at the right time

src/script/media/MediaStreamHandler.ts
`navigator.mediaDevices` can be undefined, for example [if the current document isn't loaded securely](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) (this is the case when testing locally in a VM)
=> fix: Check for navigator.mediaDevices

src/script/view_model/content/emoji.json
Pulling in fix for emoji codepoints as released in https://github.com/joypixels/emoji-assets/releases/tag/v5.0.3
To test:
1. Enter emoji `:couple with heart ww` and press `Enter`
1. Press `Backspace`
Expected: emoji is gone
Actual: emoji is broken down in its components
=> fix: pull patch for incorrect emoji codepoints

server/ServerConfig.ts, server/config.ts, src/script/global.d.ts, src/script/view_model/content/InputBarViewModel.js
Right now setting the env variable `FEATURE_ALLOWED_FILE_UPLOAD_EXTENSIONS` to this:
```
.xls, .doc, .txt
```
will not work. You had to explicitly remove the spaces:
```
.xls,.doc,.txt
```
This PR will allow setting the env variable with spaces to make it better readable.
=> runfix: Allow spaces in upload extension filter

src/script/user/UserRepository.ts
[`getAllClientsFromDb()`](https://github.com/wireapp/wire-webapp/blob/2b5ec4cf474a088f5dffcef84558a18ba6963ae5/src/script/client/ClientRepository.js#L99)  in `ClientRepository` returns an object of the following form:
```ts
{
// userEntity
'3db4b337-bb12-4352-ac27-8c3dae0dc053': [
{
// ClientEntity
meta: {
// metadata
}
}
],
// userEntity
'8b2a7f55-e49b-4b04-9e5d-773b5d25ea26': [
{
// ClientEntity
meta: {
// metadata
}
]
}
```
But `_assignAllClients()` takes one of the `userEntity` entries and checks if it's larger than 8, which makes no sense. Instead, we need to check the length of the `userEntity` array.
=> fix: Check clientEntities array length

src/script/links/LinkPreviewRepository.js, test/unit_tests/links/LinkPreviewRepositorySpec.js
Follow-up to https://github.com/wireapp/wire-desktop/pull/3158.
This removes the usage of `window.openGraph` which was provided by the Wrapper but is already replaced by `window.openGraphAsync` for 8 months.
=> refactor: Remove synchronous openGraph

server/package.json, server/yarn.lock
They are not needed anymore [since v8.2.0](https://github.com/motdotla/dotenv/compare/v8.1.0...v8.2.0).
=> chore: Remove dotenv types

server/tsconfig.json, tsconfig.json
This will add `'use strict';` to transpiled JS files.
Citing [an answer](https://stackoverflow.com/a/31395185) from StackOverflow:
> For my money, **yes**, `"use strict";` should be included in TypeScript files.
>
> Disregarding the *compile time* effects of "use strict"; on Typescript, there is likely a runtime *impact* when the generated javascript is executed:
> 
> - [MDN identifies performance improvements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript) in avoiding boxing `this` in function calls, and the removal of the `function.caller` and `function.arguments` properties.
> 
> - Jeff Walden of Mozilla has also hinted at opportunities for performance gains in [this StackOverflow …
=> fix: Set alwaysStrict option in TypeScript

test/unit_tests/calling/videoGridHandlerSpec.js, test/unit_tests/components/panel/userActionsSpec.js, test/unit_tests/event/EventRepositorySpec.js
Fixes the following warnings:
> /unit_tests/calling/videoGridHandlerSpec.js
154:5  warning  Spy declared outside of before/after/it block  jasmine/no-unsafe-spy
/unit_tests/components/panel/userActionsSpec.js
39:11  warning  Spy declared outside of before/after/it block  jasmine/no-unsafe-spy
60:11  warning  Spy declared outside of before/after/it block  jasmine/no-unsafe-spy
/unit_tests/event/EventRepositorySpec.js
141:7  warning  Expect must have a corresponding matcher call  jasmine/expect-matcher
=> test: Fix Jasmine linter warnings

package.json, yarn.lock
Reverting this change as per request from @z-dule. We need more test coverage for v5.3.36.
=> Revert "chore(deps): bump @wireapp/avs from 5.3.29 to 5.3.36"

src/script/assets/AssetCrypto.ts, src/script/assets/AssetService.ts, src/script/broadcast/BroadcastService.ts, src/script/conversation/ConversationEphemeralHandler.js, src/script/conversation/ConversationRepository.js, src/script/conversation/EventMapper.js, src/script/cryptography/CryptographyMapper.js, src/script/cryptography/CryptographyRepository.js, src/script/event/EventRepository.js, src/script/event/preprocessor/QuotedMessageMiddleware.js, src/script/links/LinkPreviewRepository.js, src/script/storage/StorageSchemata.ts, src/script/util/util.ts, src/script/view_model/content/MessageListViewModel.js, test/unit_tests/conversation/EventMapperSpec.js, test/unit_tests/cryptography/CryptographyMapperSpec.js, test/unit_tests/cryptography/CryptographyRepositorySpec.js, test/unit_tests/event/EventRepositorySpec.js, test/unit_tests/event/preprocessor/QuotedMessageMiddlewareSpec.js, test/unit_tests/message/MentionEntitySpec.js, test/unit_tests/util/UtilSpec.js, yarn.lock
This PR will
- use `libsodium` to convert arrays to base64 and vice-versa
- make the conversion functions asynchronous so they don't block the whole I/O
- thus refactoring some normal functions to `async`
- refactor some promise-returning functions to `async` to make them more readable
- rename the synchronous version of `base64ToArray()` to `base64ToArraySync()` since we need it in the `StorageSchemata`
Best viewed [without whitespace changes](https://github.com/wireapp/wire-webapp/pull/7740/files?w=1).
=> fix: Speed up base64 to array conversion

package.json, yarn.lock
=> revert: Downgrade AVS from 5.3.29 to 5.1.40

package.json, yarn.lock
=> chore(deps): bump @wireapp/avs from 5.1.40 to 5.3.44

src/page/template/content/preferences-account.htm, src/script/cryptography/CryptographyRepository.js, src/script/event/NotificationService.ts, src/script/main/app.js, src/script/storage/StorageService.ts, src/script/util/util.ts, src/script/view_model/AuthViewModel.js, src/script/view_model/content/PreferencesAccountViewModel.js
Although `isTemporaryClientAndNonPersistent` is written in TypeScript there might be some JavaScript code calling that method with an `undefined` value, so I am throwing an error now in this particular case.
=> runfix: Throw error if client type is unspecified

src/script/conversation/ConversationRoleRepository.ts
This was in place to correct a bug on the backend. This is now fixed and temporary guest users should now have the correct role of a member.
=> runfix: Don't force the role on the temporary guest

.copyconfigrc.js, bin/push_docker.js, server/bin/create_commit_sha_file.js
The configuration file for `copy-config` tries to read the current branch via git. If the directory is not a git repository (e.g. downloaded as an archive), the command fails and the configuration files are not downloaded.
This fixes https://github.com/wireapp/wire-webapp/issues/7985.
=> chore: Enable copy-config without git

src/script/util/KeyboardUtil.ts, src/script/view_model/bindings/MessageListBindings.js, src/script/view_model/content/InputBarViewModel.js
This is an attempt to help with #549, although I couldn't make it work 100%, so feedback and ideas are welcome 🙂 
**What works:** Click somewhere in the middle of the conversation view. Pressing PageUp and PageDown will scroll through the history. Press "hello" and it will be entered in the text area. Press PageUp / PageDown again and it will scroll conversation history again.
**What doesn't work:** Click in the text area. Pressing PageUp / PageDown will **not** scroll conversation history 🙁 I was trying different things, focusing on `#conversation` div or `body`, adding `tabindex`, nothing helps 😞 
In my mind, even this state is already a significant improvement, annoying, but better than nothing.
Let me know your thoughts.
P.S. I noticed a small leak, in `MessageListBindings.js` …
=> Scroll conversation view without using a mouse

src/script/strings.ts
error message phrasing
I just ran into the error message after deploying the wire-server
in demo mode for learning purposes. I found the phrasing a bit
misleading, since it could have referred to a broken server
installation instead. I admit, it't a very edgy case, but
I guess a bit more explicit phasing doesnt do any harm.
in case of acceptance, there is still some work to do,
because the i18n is missing
=> Rephrase error message about local browser storage not being available

src/style/common/variables.less
EmojiOne was rebranded to JoyPixels almost a year ago.
To be honest, I would have just removed the `local('Emoji One')`, but I wasn't sure if you prefer to keep it for some legacy reasons?
=> Add JoyPixels to the list of local emoji fonts

bin/translations_upload.ts
The app is build automatically before uploading translations. Thus the extra prompt is not necessary anymore.
=> chore: Directly upload translations

README.md
There is no need for `--specs` anymore since we can use `fdescribe` and `fit`.
=> docs: Remove outdated hint to --specs

src/script/assets/AssetService.ts, src/script/assets/AssetUploader.ts, src/script/conversation/ConversationRepository.js, test/unit_tests/assets/AssetUploaderSpec.js
We will be slowly phasing out the `AssetService`. As a first step we will replace file uploads (audio, video, pdf, zip, ...) with a version from API client. 
Next PRs:
- Adjust legacy file upload tests
- Remove legacy file upload
- Replace image upload
- Adjust legacy image upload tests
- Remove legacy image upload code
=> refactor: Use API client for file uploads

bin/push_docker.js
Windows cannot combine commands using `&&` so I am storing commands in a JavaScript array to read them from there.
=> refactor: Improve Windows compatibility for Docker push

.eslintrc.json, package.json, test/helper/TestFactory.js, yarn.lock
We disabled most of the rules and it's not part of our [original config](https://github.com/wireapp/wire-web-packages/blob/master/packages/eslint-config/eslintrc.json) so we are better off without it.
=> chore: Remove Jasmine ESLint plugin

src/script/backup/BackupRepository.ts
> Loading a string is asking for troubles.
— https://stuk.github.io/jszip/documentation/limitations.html
---
This PR will
- let JSZip load an `Uint8Array` and use the browser's native `TextDecoder` to do the heavy lifting.
This makes importing backups ~3 times faster.
=> fix: Speed up backup importing

bin/release_tag.ts, package.json, src/script/extension/GiphyRepository.ts, src/script/extension/GiphyService.ts, yarn.lock
With the latest version of "@wireapp/core" we seem to have some logout issues. That's why I preemptively revert the core version to the one on "master". This also means that the Giphy improvements will be reverted but proper login/logout is more important than Giphy. We will focus on Giphy and logout fixes again with the upcoming releases.
Reverted PR is:
- feat: Update giphy API (#8737)
=> runfix: Reset @wireapp/core to 16.6.14

src/script/main/SingleInstanceHandler.ts, test/unit_tests/main/SingleInstanceHandlerSpec.js
It seems browsers handle the default value for SameSite cookie differently (also across versions). In order to prevent browser specific bugs we set the SameSite attribute explicitly.
=> fix: Explicitly set `SameSite=Lax` for SingleInstanceHandler cookie (WEBAPP-6865)

package.json, src/script/Config.ts, src/script/components/infoToggle.ts, src/script/util/util.ts, yarn.lock
We are switching the UUID generation library because of: https://github.com/rse/pure-uuid/issues/17
=> fix: Exchange UUID library due to broken message IDs (WEBAPP-6898)

src/page/template/content/preferences-av.htm, src/script/calling/CallingRepository.ts, src/script/media/MediaStreamHandler.ts, src/script/view_model/ContentViewModel.js, src/script/view_model/content/PreferencesAVViewModel.ts, test/unit_tests/calling/CallingRepositorySpec.js
**Fixes:**
1. It is now possible to select a different webcam when one of your webcams is not working
1. When hosting a screenshare and select a different webcam in A/V preferences, the webcam won't replace/break your screensharing session anymore
1. Microphones & webcams can be changed on-the-fly when being in a call and switching devices in A/V preferences
1. Switching to a broken webcam during a videocall session won't crash the videocall anymore
1. Changing your audio input in A/V preferences won't trigger a new media request for your video device (avoids webcam preview flickering)
1. Changing your video input in A/V preferences won't trigger a new media request for your audio device
=> fix: Don't update screenshare when changing webcam

src/script/auth/Runtime.ts
Note: A previous `platform` version was detecting `chromium` as `chrome`.
=> runfix: Handle Chromium explicitly (WEBAPP-6996)

src/script/auth/route.ts, src/script/calling/CallingRepository.ts
**How to use the parameter?**
- Use a URL like `https://local.zinfra.io:8081/?enable_sft_calling=true`
- Check with JavaScript code `wire.app.repository.calling.useSftCalling()` if it worked
=> feat: Enable Beta program SFT calling via `enable_sft_calling` URL parameter (WEBAPP-7025)

server/Server.ts, server/ServerConfig.ts, server/config.ts, src/page/template/graph.htm, src/page/template/meta.htm, src/script/main/globals.ts
---
---
This needs setting the environment variable `CHROME_ORIGIN_TRIAL_TOKEN` to a token from https://developers.chrome.com/origintrials/.
=> feat: Add Chrome Origin Trial for WebRTC insertable streams (WEBAPP-7049)

src/script/view_model/content/GiphyViewModel.ts
This fixes https://github.com/wireapp/wire-webapp/issues/5826.
=> fix: Cleanup Giphy Modal after closing

package.json, yarn.lock
=> chore: Bump @wireapp/avs from 6.2.23 to 6.2.26 (#6282)

src/page/template/meta.htm, src/script/main/app.ts, src/script/util/Environment.ts
Since the introduction of the config file approach, there is no more need to read the "version" from our HTML code.
=> refactor: Remove version from HTML

server/package.json, server/routes/error/ErrorRoutes.ts
After seeing these errors:
```
0|Webapp  | TypeError: Cannot read property 'date' of undefined
0|Webapp  |     at /var/app/routes/error/ErrorRoutes.ts:41:23
0|Webapp  |     at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
0|Webapp  |     at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
0|Webapp  |     at /var/app/current/node_modules/express/lib/router/index.js:284:7
0|Webapp  |     at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
0|Webapp  |     at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
0|Webapp  |     at /var/app/current/node_modules/express/lib/router/index.js:635:15
0|Webapp  |     at next …
```
=> fix(server): Add date to request only if the value exists

src/script/conversation/ConversationStateHandler.ts
Missing return, was introduced in https://github.com/wireapp/wire-webapp/pull/10088.
=> runfix: Return after changing conversation access state

package.json, src/script/media/MediaEmbeds.ts, src/script/util/LoggerUtil.ts
Since all current browser versions [support](https://caniuse.com/?search=URLSearchParams) `URLSearchParams`, we can now remove the polyfill.
=> refactor: Remove url-search-params-polyfill

src/script/Config.ts
**Current situation**
The current config code sets `URL` to what is given by `env.URL` or a set of default values. 
**Problem**
When you are now launching the webapp with a very old configuration, then `env.URL` might not have entries like `URL.SUPPORT.HISTORY`, so our code fails at statements like `Config.getConfig().URL.SUPPORT.HISTORY`.
**Solution**
To make new Wire web app versions compatible with old configs, we can set `URL` to a set of defaults first and then spread the config properties of our custom (old) config into the config object. Thus it will be guaranteed that we have a config with meaningful default values.
**Real-World Scenario**
I ran into this problem by using a webapp version (commit ID 14ee262578ec98843cfd48bf1bcd9edd0074d611) from 2021 with a config from 2020.
- My …
=> feat: Make recent webapps compatible with old URL configs

.github/workflows/test_build_deploy.yml
Since we are neither building nor publishing from pull requests with `DISTRIBUTION != wire` we can also disable running `yarn` and `yarn test --coverage` in those action runs.
=> chore: Shorten PR build times

package.json, yarn.lock
Reverts wireapp/wire-webapp#10509
=> Revert "chore: bump highlight.js from 10.5.0 to 10.6.0"

.github/dependabot.yml
Trying to ignore: https://github.com/wireapp/wire-webapp/pull/10586
=> chore: Ignore husky v5 update

webpack.config.common.js
Webpack 5 introduced **persistent caching** which allows to save its cache on the disk (fileystem). Saving webpack's cache on disk, rather than saving it in-memory, speeds up webpack's compilation on consecutive starts by a lot.
When running our webapp, the compile step of webpack takes around 25 seconds on my machine:
> webpack 5.24.0 compiled with 1 warning in 24502ms
> webpack built 0c5abf71da034c869f6c in 734ms
Using webpack's filesystem cache, the first start will still take 25 seconds on my machine but following starts (using the cache from the first start) just take 2.5 seconds:
> webpack 5.24.0 compiled with 1 warning in 2232 ms
> webpack built 0c5abf71da034c869f6c in 758ms
Read more about it here: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#persistent-caching
=> chore: Use filesystem caching with webpack 5

.github/workflows/test_build_deploy.yml
We just need the Clover output to get the "Coverage Report" from GitHub Actions, so we can ommit this table:
=> chore: Skip coverage table in CI builds

package.json, yarn.lock
Reverts wireapp/wire-webapp#10719
=> Revert "chore: bump ts-jest from 26.5.2 to 26.5.3"

.github/workflows/test_build_deploy.yml
Since [dependabot can't read the repository's secret anymore](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/), we need to check for `matrix.DISTRIBUTION` instead of checking for the secret to distinguish if an actions' step should be executed or not.
=> chore: Check for DISTRIBUTION_0 in GitHub Actions

src/script/conversation/EventInfoEntity.ts, src/script/conversation/MessageRepository.ts, src/script/storage/record/EventRecord.ts, test/unit_tests/conversation/ClientMismatchHandlerSpec.js
before:
`new Date('1461926303002') -> Invalid Date`
after:
`new Date(1461926303002) -> 2016-04-29T10:38:23.002Z`
=> test: Use ISO date when using `EventInfoEntity.setTimestamp()`

.github/workflows/test_build_deploy.yml, bin/push_docker.js
*This change set aims to fix the naming scheme if container image tags with a focus on release versions.*
1. refactor: make script used to push Docker images a bit more readable
* remove dashes from values and add them inline when needed
* remove obsolete variables along the way
2. ci: change container image tag names to reflect
* before, image tags did not indicate actual releases
* before, `pkg.version` was a) meaningless and b) kept being static '0.2.0'
This way, it's a one-step lookup to the corresponding webapp release
If CI is triggered via release tag, the tags are, e.g.:
* 2021-04-01-production.0-v0.28.3-254d51 - '${RELEASE_NAME}-${COMMIT_ID_SHORT}-${CONFIG_VERSION}'
* edge - '${STAGE}'
If CI is triggered via dev or edge branch, the tag is, e.g.:
* dev - '${STAGE}'
This allows to …
=> chore: CI change docker tag name scheme

src/script/conversation/MessageRepository.ts, src/script/util/TypePredicateUtil.test.ts, src/script/util/TypePredicateUtil.ts
Errors are by default of `any` type, so they can be `undefined` or of type `string` which will cause a check on `error.code` to fail.
=> fix: Check if errors are backend errors

.github/workflows/test_build_deploy.yml
This change-set is meant to keep the webapp Helm chart in wire-server
up-to-date. To accomplish that, it adds two new blocks of steps (one
of which actually incorporates a new job).
(1) following the naming scheme in ./bin/push_docker.js:59, a step
assembles the image tag name (not the release tag) - and so the
naming clash begins. A second one write the information to an 'artifact'.
This way, its possible to access the information from another job.
(2) this new job reads the image tag from the artifact and opens a
new PR over at wire-server. This PR is supposed to only update the
webapp chart - more precisely it only changes the value of 'image.tag'
in wire-server/charts/webapp/values.yaml
Finally, the artifact is removed by the general clean up job 'cleanup_artifacts'.
Furthermore, the …
=> chore(ci): Add job to update image tag in corresponding Helm chart

.github/workflows/test_build_deploy.yml
This comment aims to explain possible erroring and tries to clarify the
reasoning behind that design.
=> chore: Add comment to explain why Helm chart update job might throw an error

bin/push_docker.js
As a result of a discussion in 'wire-account' [1], this change set ports
the proposed changes - simply for reasons of consistency, and:
[...] because 'app-config/package.json' only contains the 'dependencies'
field, not all the others like 'devDependencies' or 'peerDependencies'.
[1] https://github.com/wireapp/wire-account/pull/2865#discussion_r644025507
=> chore: Remove references of non-existing keys in app-config

bin/push_docker.js
The container image tag information are now solely defined by the script input.
Due to the fact that branch information are not available during the release
process (because it indicated by a tag), it make sense to rather base the tag
determination on the stageParam, which is set i the respective pipeline step.
This also allows to further simplify the script assembling that tag and pushing
the images. Alongside, some variables have been renamed to clarify the meaning
of their values.
The pipelines uses 7 characters while the script only used 6 (second param of
substring behaves exclusive). This has been aligned.
*Owner: @arianvp*
=> chore: Base tag information on script input rather than branch name

src/script/team/TeamRepository.ts
If a user logs into two different accounts sequentially on the same webapp instance the feature config would be compared to the feature config state of the previous account. This PR scopes the feature config state to a specific account.
=> runfix: Handle multi-user feature config state comparison

src/page/template/content/collection-details.htm, src/page/template/content/collection.htm
Current:
Expected:
Every audio asset should be on a new line
=> runfix: Audio asset collection arrangement

src/script/components/toggle/ReceiptModeToggle.test.ts, src/script/components/toggle/ReceiptModeToggle.tsx, src/script/properties/PropertiesRepository.ts, src/script/view_model/content/PreferencesAccountViewModel.ts, test/unit_tests/user/UserRepositorySpec.js
Follow-up to https://github.com/wireapp/wire-webapp/pull/11748.
=> refactor(core): Fix missing conversation receipt mode typings
